const DB_NAME="lizhi-local-cloud";
const DB_VERSION=1;
const IS_CLOUD_SITE=location.hostname.endsWith("github.io")||new URLSearchParams(location.search).has("cloud");
const CLOUD_APP_URL="https://lihuany635-create.github.io/lizhi-cloud-laptop-6s8a4kuk/";
const RELEASE_BASE="https://github.com/lihuany635-create/lizhi-cloud-laptop-6s8a4kuk/releases/download/media-2026-08-23/";
const queryParams=new URLSearchParams(location.search);
const OPEN_ROUTES=["home","knowledge","weave","finance","media","chat","study","a4","trash","settings","uploads"];
const requestedRoute=queryParams.get("open");
const state={route:OPEN_ROUTES.includes(requestedRoute)?requestedRoute:"home",records:[],cloudMedia:[],query:"",mediaType:"all",modal:null,sidebar:!requestedRoute||requestedRoute==="home",urls:[]};
const app=document.querySelector("#app");
const knowledgeInput=document.querySelector("#knowledge-file-input");
const mediaInput=document.querySelector("#media-file-input");
const restoreInput=document.querySelector("#restore-input");

const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const formatDate=value=>new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value));
const formatBytes=bytes=>bytes>=1073741824?`${(bytes/1073741824).toFixed(2)} GB`:bytes>=1048576?`${(bytes/1048576).toFixed(1)} MB`:bytes>=1024?`${(bytes/1024).toFixed(1)} KB`:`${bytes} B`;
function syncRouteUrl(route){const url=new URL(location.href);if(route==="home")url.searchParams.delete("open");else url.searchParams.set("open",route);url.searchParams.delete("room");history.replaceState(null,"",url)}

const CHAT_DEVICE_ID_KEY="lizhi-realtime-device-id";
const CHAT_DEVICE_NAME_KEY="lizhi-realtime-device-name";
const CHAT_HISTORY_PREFIX="lizhi-realtime-history:";
const chat={started:false,roomCode:"",deviceId:"",deviceName:"",status:"connecting",messages:[],retryTimer:null,autoSendTimer:null,copiedId:""};
const chatTime=value=>new Intl.DateTimeFormat("zh-TW",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));
function initializeChatIdentity(){chat.roomCode="public-cloud-v18";chat.deviceId=localStorage.getItem(CHAT_DEVICE_ID_KEY)||uid();localStorage.setItem(CHAT_DEVICE_ID_KEY,chat.deviceId);chat.deviceName=localStorage.getItem(CHAT_DEVICE_NAME_KEY)||(/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent)?"我的手機":"我的電腦");try{chat.messages=JSON.parse(localStorage.getItem(CHAT_HISTORY_PREFIX+chat.roomCode)||"[]").slice(-80);}catch{chat.messages=[];}}
function saveChatHistory(){try{localStorage.setItem(CHAT_HISTORY_PREFIX+chat.roomCode,JSON.stringify(chat.messages.slice(-80)));}catch{toast("本機對話儲存空間不足");}}
function chatInviteUrl(){const url=new URL(IS_CLOUD_SITE?location.href:CLOUD_APP_URL);url.search="";url.hash="";url.searchParams.set("open","chat");url.searchParams.set("v","18");return url.href;}
function addChatMessage(message){if(!message?.id||chat.messages.some(item=>item.id===message.id))return;chat.messages=[...chat.messages,message].slice(-80);saveChatHistory();if(state.route==="chat")render();}
function updateChatStatus(status){chat.status=status;if(state.route==="chat")render();}
function scheduleChatReconnect(){retryChatConnection();}
async function startRealtimeChat(){return startReliableChat();}
function sendChatMessage(text){return queueChatText(text);}
function scheduleChatAutoSend(text,immediate=false){autoQueueChat(text,immediate);}

function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("records"))db.createObjectStore("records",{keyPath:"id"});if(!db.objectStoreNames.contains("blobs"))db.createObjectStore("blobs",{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function store(mode,name="records"){const db=await openDb();return db.transaction(name,mode).objectStore(name);}
async function allRecords(){return new Promise(async(resolve,reject)=>{const request=(await store("readonly")).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function putRecord(record){return new Promise(async(resolve,reject)=>{const request=(await store("readwrite")).put(record);request.onsuccess=()=>resolve(record);request.onerror=()=>reject(request.error);});}
async function removeRecord(id){return new Promise(async(resolve,reject)=>{const request=(await store("readwrite")).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);});}
async function putBlob(id,blob){return new Promise(async(resolve,reject)=>{const request=(await store("readwrite","blobs")).put({id,blob});request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);});}
async function getBlob(id){return new Promise(async(resolve,reject)=>{const request=(await store("readonly","blobs")).get(id);request.onsuccess=()=>resolve(request.result?.blob);request.onerror=()=>reject(request.error);});}
async function removeBlob(id){return new Promise(async(resolve,reject)=>{const request=(await store("readwrite","blobs")).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);});}

async function seed(){const rows=await allRecords();if(rows.length)return;const created=now();await putRecord({id:uid(),kind:"folder",title:"我的第一個資料夾",createdAt:created,updatedAt:created});await putRecord({id:uid(),kind:"note",title:"歡迎使用立之雲端庫",body:"這一版只屬於這台電腦。\n\n你可以建立筆記、上傳文件與影音、整理 Podcast 專案，也能從這裡直接進入立之讀書室。",tags:["開始"],createdAt:created,updatedAt:created});}
async function loadCloudMedia(){if(!IS_CLOUD_SITE)return;const response=await fetch("./media-manifest.json",{cache:"no-store"});if(!response.ok)throw new Error("無法載入雲端影音目錄");const items=await response.json();state.cloudMedia=items.map((item,index)=>({id:`cloud-${index+1}`,kind:"media",mediaType:item.type?.startsWith("video/")?"video":"audio",title:item.title,fileName:item.fileName,type:item.type,size:item.size,remoteUrl:RELEASE_BASE+encodeURIComponent(item.assetName||item.fileName),favorite:false,createdAt:item.createdAt,updatedAt:item.createdAt,cloud:true}));}
async function refresh(){const rows=await allRecords();state.records=IS_CLOUD_SITE?[...rows.filter(row=>row.kind!=="media"),...state.cloudMedia]:rows;render();}
const active=kind=>state.records.filter(row=>row.kind===kind&&!row.deletedAt);
const trashed=()=>state.records.filter(row=>row.deletedAt);
function toast(message){document.querySelector(".toast")?.remove();const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2600);}

const navItems=[
  ["home","⌂","封面"],["knowledge","知","知識庫"],["weave","織","知識編織室"],["finance","財","理財管家"],["media","影","影音庫"],["chat","↔","即時對話"],["study","✎","立之讀書室"],["a4","頁","A4 文件編輯器"],["uploads","↑","上傳狀態"],["trash","♲","回收桶"],["settings","⚙","本機設定"]
];
function navDescription(route){return route==="knowledge"?"文件、筆記與搜尋":route==="weave"?"Proposal 與人工審核":route==="finance"?"離線記帳與財務整理":route==="media"?"影片、音訊與已生成 Podcast":route==="chat"?"手機與電腦即時傳字":route==="study"?"畫布提問與教學模式":route==="a4"?"固定格子、模板與 Word／PDF":route==="trash"?"復原已刪除內容":route==="uploads"?"最近回報、待上傳與失敗原因":route==="settings"?"備份與裝置資料":"返回收藏入口";}
function layout(content){return `<div class="shell route-${state.route} ${state.sidebar?"drawer-open":""}"><header class="topbar"><a class="brand" href="#" data-route="home"><span class="brand-mark">立</span><span><b>立之雲端庫</b><small>${IS_CLOUD_SITE?"THIS LAPTOP CLOUD ARCHIVE":"LOCAL PRIVATE ARCHIVE"}</small></span></a><span class="local-pill">● ${IS_CLOUD_SITE?"21 集雲端同步":"本機資料庫"}</span><button class="button library-menu-button" data-action="toggle-menu">選擇收藏庫</button></header><button class="drawer-handle" data-action="toggle-menu" aria-label="${state.sidebar?"關閉收藏庫選單":"拉出收藏庫選單"}">${state.sidebar?"›":"‹"}</button><aside class="sidebar ${state.sidebar?"open":""}" aria-label="雲端庫入口"><div class="drawer-head"><div><div class="nav-title">LIBRARY MENU</div><h2>選擇收藏庫</h2></div><button class="drawer-close" data-action="toggle-menu" aria-label="關閉選單">×</button></div><nav class="nav-list">${navItems.map(([route,icon,label],index)=>`<button class="nav-link ${state.route===route?"active":""}" data-route="${route}"><span>${icon}</span><b><small>${String(index+1).padStart(2,"0")}</small>${label}<em>${navDescription(route)}</em></b><i>進入 →</i></button>`).join("")}</nav><div class="side-note">KNOWLEDGE · FINANCE · MEDIA · CHAT · STUDY · A4<br>${IS_CLOUD_SITE?"AVAILABLE ON EVERY DEVICE":"PRIVATE BY DESIGN"}</div></aside><main class="main">${content}</main></div>${renderModal()}`;}
function head(eyebrow,title,description,actions=""){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div><div class="actions">${actions}</div></div>`;}

function renderHome(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">PRIVATE CLOUD ARCHIVE · ${IS_CLOUD_SITE?"THIS LAPTOP EDITION":"LOCAL EDITION"}</div><h1><span>立之</span>雲端庫</h1><p>一個入口，收藏知識、影音、Podcast 與學習軌跡。<br>從右側拉出選單，選擇要進入的空間。</p><div class="home-local-note">● ${IS_CLOUD_SITE?"CLOUD MEDIA · 不同網路與多裝置皆可使用":"LOCAL DATABASE · 只屬於這台電腦"}</div></div><div class="hero-visual" aria-hidden="true"></div></section>`;}

function matches(row){const query=state.query.trim().toLowerCase();if(!query)return true;return [row.title,row.body,row.name,(row.tags||[]).join(" "),row.description].some(value=>String(value||"").toLowerCase().includes(query));}
function renderKnowledge(){const folders=active("folder").filter(matches),notes=active("note").filter(matches),documents=active("document").filter(matches),tags=[...new Set(active("note").flatMap(row=>row.tags||[]))];return `${head("KNOWLEDGE LIBRARY","私人知識庫","資料夾、筆記與文件都保存在本機。",`<button class="button" data-action="upload-knowledge">↑ 上傳文件</button><button class="button" data-action="new-folder">＋ 資料夾</button><button class="button primary" data-action="new-note">＋ 新筆記</button>`)}<div class="stats"><div class="stat"><b>${folders.length}</b><small>資料夾</small></div><div class="stat"><b>${notes.length}</b><small>筆記</small></div><div class="stat"><b>${documents.length}</b><small>文件</small></div><div class="stat"><b>${tags.length}</b><small>標籤</small></div></div><div class="toolbar"><input class="field search" data-search placeholder="搜尋筆記、文件或標籤" value="${escapeHtml(state.query)}"><button class="button" data-action="clear-search">清除</button></div><section class="section"><div class="section-head"><h2>資料夾</h2><span class="count">${folders.length} 個</span></div><div class="grid">${folders.length?folders.map(folder=>`<article class="card"><div class="card-top"><span>📁</span><button class="icon-button" title="移到回收桶" data-trash="${folder.id}">×</button></div><h3>${escapeHtml(folder.title)}</h3><p>建立於 ${formatDate(folder.createdAt)}</p></article>`).join(""):`<div class="empty">尚未建立資料夾</div>`}</div></section><section class="section"><div class="section-head"><h2>筆記</h2><span class="count">${notes.length} 份</span></div><div class="grid">${notes.length?notes.map(note=>`<article class="card"><div class="card-top"><span>✎</span><button class="icon-button" title="移到回收桶" data-trash="${note.id}">×</button></div><h3>${escapeHtml(note.title)}</h3><p class="note-body">${escapeHtml(note.body)}</p><div class="meta">${(note.tags||[]).map(tag=>`<span class="chip"># ${escapeHtml(tag)}</span>`).join("")}</div><div class="card-actions"><button class="button" data-edit-note="${note.id}">編輯</button></div></article>`).join(""):`<div class="empty">尚未建立筆記</div>`}</div></section><section class="section"><div class="section-head"><h2>文件與圖片</h2><span class="count">${documents.length} 份</span></div>${documents.length?`<div class="grid">${documents.map(doc=>`<article class="card"><div class="card-top"><span>${doc.type?.startsWith("image/")?"▧":"▤"}</span><button class="icon-button" title="移到回收桶" data-trash="${doc.id}">×</button></div><h3>${escapeHtml(doc.title)}</h3><p>${escapeHtml(doc.type||"檔案")} · ${formatBytes(doc.size||0)}</p><div class="card-actions"><button class="button" data-download="${doc.id}">下載／查看</button></div></article>`).join("")}</div>`:`<div class="dropzone" data-action="upload-knowledge"><strong>上傳文件或圖片</strong><small>支援常用文件格式與多個檔案</small></div>`}</section>`;}

function renderMedia(){let media=active("media").filter(matches);if(state.mediaType==="favorite")media=media.filter(row=>row.favorite);else if(state.mediaType!=="all")media=media.filter(row=>row.mediaType===state.mediaType);const fav=active("media").filter(row=>row.favorite).length,total=active("media").reduce((sum,row)=>sum+(row.size||0),0),actions=IS_CLOUD_SITE?`<span class="chip">由這台筆電更新雲端內容</span>`:`<button class="button primary" data-action="upload-media">↑ 上傳影音／Podcast</button>`;return `${head("PRIVATE MEDIA LIBRARY","私人影音庫","影片、音訊與已經生成完成的 Podcast 都集中在這裡。",actions)}<div class="stats"><div class="stat"><b>${media.length}</b><small>目前顯示</small></div><div class="stat"><b>${active("media").filter(row=>row.mediaType==="audio").length}</b><small>Podcast／音訊</small></div><div class="stat"><b>${active("media").filter(row=>row.mediaType==="video").length}</b><small>影片</small></div><div class="stat"><b>${formatBytes(total)}</b><small>${IS_CLOUD_SITE?"雲端影音":"本機容量"}</small></div></div><div class="toolbar"><input class="field search" data-search placeholder="搜尋影音或 Podcast 名稱" value="${escapeHtml(state.query)}"><select data-media-filter><option value="all" ${state.mediaType==="all"?"selected":""}>全部類型</option><option value="audio" ${state.mediaType==="audio"?"selected":""}>Podcast／音訊</option><option value="video" ${state.mediaType==="video"?"selected":""}>影片</option><option value="favorite" ${state.mediaType==="favorite"?"selected":""}>我的收藏</option></select><button class="button" data-action="clear-search">清除</button></div><section class="section"><div class="section-head"><h2>影音與已生成 Podcast</h2><span class="count">${media.length} 項 · ${fav} 收藏</span></div>${media.length?`<div class="grid">${media.map(row=>`<article class="card media-card" data-media-card="${row.id}"><div class="media-icon">${row.mediaType==="video"?"▶":"♫"}</div><div class="card-top"><div><span class="chip">${row.mediaType==="video"?"影片":"Podcast／音訊"}</span><h3>${escapeHtml(row.title)}</h3></div>${row.cloud?"":`<button class="icon-button" title="收藏" data-favorite="${row.id}">${row.favorite?"★":"☆"}</button>`}</div><p>${formatBytes(row.size||0)} · ${formatDate(row.createdAt)}</p><div class="player-slot" data-player="${row.id}"></div><div class="card-actions"><select class="rate" data-rate="${row.id}"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select>${row.cloud?`<a class="button" href="${row.remoteUrl}" download>下載</a>`:`<button class="button danger" data-trash="${row.id}">移到回收桶</button>`}</div></article>`).join("")}</div>`:`<div class="dropzone" data-action="upload-media"><strong>上傳已生成的 Podcast、音訊或影片</strong><small>點此選擇 MP3、M4A、WAV、MP4、MOV 或其他瀏覽器支援格式</small></div>`}</section>`;}

function renderPodcasts(){const rows=active("podcast").filter(matches);return `${head("PODCAST PROJECTS","每日 Podcast 專案","在本機管理主題、關鍵字與排程；不會自行發布到外部平台。",`<button class="button primary" data-action="new-podcast">＋ 建立專案</button>`)}<div class="toolbar"><input class="field search" data-search placeholder="搜尋 Podcast 專案" value="${escapeHtml(state.query)}"><button class="button" data-action="clear-search">清除</button></div><section class="section"><div class="section-head"><h2>我的專案</h2><span class="count">${rows.length} 個</span></div>${rows.length?`<div class="grid">${rows.map(row=>`<article class="card podcast-card ${row.status==="paused"?"paused":""}"><div class="card-top"><span class="status">${row.status==="paused"?"已暫停":"執行中"}</span><button class="icon-button" data-trash="${row.id}">×</button></div><h3>${escapeHtml(row.title)}</h3><p>${escapeHtml(row.description||"尚未填寫說明")}</p><dl><dt>排程</dt><dd class="schedule">${escapeHtml(row.schedule||"尚未設定")}</dd><dt>關鍵字</dt><dd>${escapeHtml((row.keywords||[]).join("、")||"尚未設定")}</dd></dl><div class="card-actions"><button class="button" data-edit-podcast="${row.id}">查看／編輯</button><button class="button" data-toggle-podcast="${row.id}">${row.status==="paused"?"恢復":"暫停"}</button></div></article>`).join("")}</div>`:`<div class="empty">目前沒有 Podcast 專案。建立第一個主題後，就能保存來源規劃、關鍵字與排程。</div>`}</section>`;}

function renderStudy(){return `<section class="study-embedded" aria-label="立之讀書室"><header class="study-embedded-toolbar"><div><div class="eyebrow">DRAWING STUDY ROOM</div><h1>立之讀書室</h1></div><div class="actions"><span class="study-online">讀書室載入中</span><button class="button" data-action="reload-study">重新載入</button></div></header><div class="study-frame-wrap"><iframe id="study-room-frame" title="立之讀書室" src="https://drawing-codex-assistant.vercel.app/" allow="clipboard-read; clipboard-write" referrerpolicy="strict-origin-when-cross-origin"></iframe></div></section>`;}
function renderA4Editor(){return `<section class="study-embedded a4-embedded" aria-label="A4 文件編輯器"><div class="study-frame-wrap"><iframe id="a4-editor-frame" title="A4 文件編輯器" src="./a4-editor/?v=14" allow="clipboard-read; clipboard-write"></iframe></div></section>`;}
function renderChat(){return `${head("CLOUD CHAT · 共用對話","即時對話","所有裝置開啟網站即可接續，不用登入或配對。",'<span class="chat-status" role="status"></span>')}<section class="chat-public-notice"><b>公開對話 · 版本 18</b><p>任何開啟網站的人都能閱讀及留言，請勿傳送密碼或私人資料。名稱僅供辨識，並非身分驗證。</p></section><section class="chat-window"><div class="chat-device-row"><label>這台裝置 <input data-chat-device maxlength="40" value="${escapeHtml(chat.deviceName)}"></label><button class="button" data-action="retry-chat">重新同步</button></div><div class="chat-messages" aria-live="polite">${chat.messages.length?chat.messages.map(message=>{const mine=message.deviceId===chat.deviceId;return `<article class="chat-message ${mine?"mine":"theirs"}"><header><b>${mine?"這台裝置":escapeHtml(message.deviceName||"其他裝置")}</b><time>${chatTime(message.createdAt)}</time></header><p>${escapeHtml(message.content)}</p><button data-copy-chat="${escapeHtml(message.id)}">${chat.copiedId===message.id?"已複製 ✓":"複製"}</button></article>`;}).join(""):'<div class="chat-empty"><span>↔</span><h2>共用對話</h2><p>在下方輸入文字，會自動存到雲端，其他裝置也能看到。</p><p>舊版配對紀錄仍保留在原裝置，不會自動公開。</p></div>'}</div><form class="chat-compose" data-form="chat"><textarea name="message" maxlength="10000" rows="4" placeholder="輸入或貼上文字，自動同步…" aria-label="要傳送的文字"></textarea><div><small>貼上或打字停頓後自動傳送</small></div></form></section>`;}
function renderTrash(){const rows=trashed();return `${head("RECYCLE BIN","回收桶","刪除的內容會先放在這裡，可以復原或永久刪除。")}`+`<section class="section">${rows.length?rows.map(row=>`<div class="trash-row"><div><b>${escapeHtml(row.title||row.name||"未命名")}</b><div class="count">${escapeHtml(row.kind)} · ${formatDate(row.deletedAt)}</div></div><div class="actions"><button class="button" data-restore="${row.id}">復原</button><button class="button danger" data-purge="${row.id}">永久刪除</button></div></div>`).join(""):`<div class="empty">回收桶是空的</div>`}</section>`;}
function renderSettings(){return `${head("LOCAL SETTINGS","本機設定","管理本機資料、備份與使用方式。")}`+`<section class="section settings-list"><div class="settings-item"><div><b>匯出資料目錄</b><p>備份筆記、資料夾、影音中繼資料與 Podcast 設定；不包含影音檔本體。</p></div><button class="button" data-action="export">匯出 JSON</button></div><div class="settings-item"><div><b>匯入資料目錄</b><p>從先前匯出的 JSON 恢復資料，不會刪除現有內容。</p></div><button class="button" data-action="restore">選擇備份</button></div><div class="settings-item"><div><b>儲存位置</b><p>瀏覽器 IndexedDB：${DB_NAME}</p></div><span class="chip">僅限本機</span></div><div class="settings-item"><div><b>啟動方式</b><p>雙擊專案資料夾內的「啟動立之雲端庫.cmd」。</p></div><span class="chip">127.0.0.1:4180</span></div></section>`;}

function renderModal(){if(!state.modal)return"";const row=state.modal.id?state.records.find(item=>item.id===state.modal.id):null;if(state.modal.type==="note")return `<div class="modal-backdrop"><form class="modal" data-form="note"><h2>${row?"編輯筆記":"建立筆記"}</h2><input type="hidden" name="id" value="${row?.id||""}"><div class="form-grid"><label>標題<input name="title" required value="${escapeHtml(row?.title||"")}"></label><label>標籤（用逗號分隔）<input name="tags" value="${escapeHtml((row?.tags||[]).join(", "))}"></label><label>內容<textarea name="body" required>${escapeHtml(row?.body||"")}</textarea></label></div><footer><button type="button" class="button" data-action="close-modal">取消</button><button class="button primary">儲存筆記</button></footer></form></div>`;if(state.modal.type==="folder")return `<div class="modal-backdrop"><form class="modal" data-form="folder"><h2>建立資料夾</h2><div class="form-grid"><label>資料夾名稱<input name="title" required autofocus></label></div><footer><button type="button" class="button" data-action="close-modal">取消</button><button class="button primary">建立</button></footer></form></div>`;if(state.modal.type==="podcast")return `<div class="modal-backdrop"><form class="modal" data-form="podcast"><h2>${row?"編輯 Podcast 專案":"建立 Podcast 專案"}</h2><input type="hidden" name="id" value="${row?.id||""}"><div class="form-grid"><label>專案名稱<input name="title" required value="${escapeHtml(row?.title||"")}"></label><label>說明<textarea name="description">${escapeHtml(row?.description||"")}</textarea></label><label>關鍵字（用逗號分隔）<input name="keywords" value="${escapeHtml((row?.keywords||[]).join(", "))}"></label><label>排程（Cron 或文字）<input name="schedule" placeholder="例如：每天 10:00" value="${escapeHtml(row?.schedule||"")}"></label></div><footer><button type="button" class="button" data-action="close-modal">取消</button><button class="button primary">儲存專案</button></footer></form></div>`;return"";}

function render(){renderWorkspace();}
async function hydrateMedia(){const panel=workspacePanels.get("media");if(panel)await hydrateStableMedia(panel);}

app.addEventListener("click",async event=>{const target=event.target.closest("button,a");if(!target)return;if(target.dataset.route){event.preventDefault();state.route=target.dataset.route;state.query="";state.sidebar=false;syncRouteUrl(state.route);render();return;}const action=target.dataset.action;if(action==="toggle-menu"){state.sidebar=!state.sidebar;render();}if(action==="new-note"){state.modal={type:"note"};render();}if(action==="new-folder"){state.modal={type:"folder"};render();}if(action==="new-podcast"){state.modal={type:"podcast"};render();}if(action==="close-modal"){state.modal=null;render();}if(action==="upload-knowledge")knowledgeInput.click();if(action==="upload-media")mediaInput.click();if(action==="clear-search"){state.query="";render();}if(action==="export")exportBackup();if(action==="restore")restoreInput.click();if(target.dataset.editNote){state.modal={type:"note",id:target.dataset.editNote};render();}if(target.dataset.editPodcast){state.modal={type:"podcast",id:target.dataset.editPodcast};render();}if(target.dataset.trash){const row=state.records.find(item=>item.id===target.dataset.trash);await putRecord({...row,deletedAt:now(),updatedAt:now()});await refresh();toast("已移到回收桶");}if(target.dataset.restore){const row=state.records.find(item=>item.id===target.dataset.restore);const copy={...row,updatedAt:now()};delete copy.deletedAt;await putRecord(copy);await refresh();toast("已復原");}if(target.dataset.purge){if(!confirm("永久刪除後無法復原，確定繼續？"))return;const row=state.records.find(item=>item.id===target.dataset.purge);await removeRecord(row.id);if(row.kind==="media"||row.kind==="document")await removeBlob(row.id);await refresh();toast("已永久刪除");}if(target.dataset.favorite){const row=state.records.find(item=>item.id===target.dataset.favorite);await putRecord({...row,favorite:!row.favorite,updatedAt:now()});await refresh();}if(target.dataset.togglePodcast){const row=state.records.find(item=>item.id===target.dataset.togglePodcast);await putRecord({...row,status:row.status==="paused"?"active":"paused",updatedAt:now()});await refresh();}if(target.dataset.download){const row=state.records.find(item=>item.id===target.dataset.download);const blob=await getBlob(row.id);if(!blob)return toast("找不到檔案內容");const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=row.title;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
app.addEventListener("click",async event=>{const target=event.target.closest("button");if(!target)return;if(target.dataset.action==="copy-chat-link"){await navigator.clipboard.writeText(chatInviteUrl());toast("已複製共用對話網址");}if(target.dataset.action==="clear-chat"){if(!confirm("只清除這台裝置上的即時對話紀錄，確定繼續？"))return;chat.messages=[];saveChatHistory();render();}if(target.dataset.copyChat){const message=[...chat.messages,...chat.outbox].find(item=>item.id===target.dataset.copyChat);if(message){await navigator.clipboard.writeText(message.content);chat.copiedId=message.id;render();setTimeout(()=>{chat.copiedId="";if(state.route==="chat")render();},1200);}}});
app.addEventListener("input",event=>{if(event.target.matches("[data-search]")){state.query=event.target.value;clearTimeout(window.__searchTimer);window.__searchTimer=setTimeout(render,180);}});
app.addEventListener("input",event=>{if(event.target.matches("[data-chat-device]")){chat.deviceName=event.target.value;localStorage.setItem(CHAT_DEVICE_NAME_KEY,chat.deviceName);}if(event.target.matches('.chat-compose textarea'))scheduleChatAutoSend(event.target.value,event.inputType==="insertFromPaste");});
app.addEventListener("keydown",event=>{if(event.target.matches('.chat-compose textarea')&&event.key==="Enter"&&!event.shiftKey&&!event.isComposing){event.preventDefault();event.target.form?.requestSubmit();}});
app.addEventListener("submit",event=>{if(event.target.dataset.form!=="chat")return;event.preventDefault();event.stopImmediatePropagation();const form=event.target;const data=new FormData(form);if(sendChatMessage(data.get("message")))form.reset();},true);
app.addEventListener("click",event=>{const button=event.target.closest('[data-action="reload-study"]');if(!button)return;const frame=document.querySelector("#study-room-frame");if(frame){frame.src=frame.src;toast("正在重新載入讀書室");}});
app.addEventListener("click",event=>{const button=event.target.closest('[data-action="reload-a4"]');if(!button)return;const frame=document.querySelector("#a4-editor-frame");if(frame){frame.src=frame.src;toast("正在重新載入 A4 編輯器");}});
app.addEventListener("change",event=>{if(event.target.matches("[data-media-filter]")){state.mediaType=event.target.value;render();}if(event.target.matches("[data-rate]")){const player=document.querySelector(`[data-player-element="${event.target.dataset.rate}"]`);if(player)player.playbackRate=Number(event.target.value);}});
app.addEventListener("submit",async event=>{event.preventDefault();const form=event.target;const data=Object.fromEntries(new FormData(form));if(form.dataset.form==="note"){const existing=data.id?state.records.find(row=>row.id===data.id):null;await putRecord({...(existing||{}),id:data.id||uid(),kind:"note",title:data.title.trim(),body:data.body.trim(),tags:data.tags.split(",").map(x=>x.trim()).filter(Boolean),createdAt:existing?.createdAt||now(),updatedAt:now()});}if(form.dataset.form==="folder")await putRecord({id:uid(),kind:"folder",title:data.title.trim(),createdAt:now(),updatedAt:now()});if(form.dataset.form==="podcast"){const existing=data.id?state.records.find(row=>row.id===data.id):null;await putRecord({...(existing||{}),id:data.id||uid(),kind:"podcast",title:data.title.trim(),description:data.description.trim(),keywords:data.keywords.split(",").map(x=>x.trim()).filter(Boolean),schedule:data.schedule.trim(),status:existing?.status||"active",createdAt:existing?.createdAt||now(),updatedAt:now()});}state.modal=null;await refresh();toast("已儲存");});

knowledgeInput.addEventListener("change",async()=>{for(const file of knowledgeInput.files){const id=uid();await putBlob(id,file);await putRecord({id,kind:"document",title:file.name,type:file.type,size:file.size,createdAt:now(),updatedAt:now()});}knowledgeInput.value="";await refresh();toast("文件已保存到本機");});
mediaInput.addEventListener("change",async()=>{for(const file of mediaInput.files){const title=file.name.replace(/\.[^.]+$/,""),existing=state.records.find(row=>row.kind==="media"&&!row.deletedAt&&row.title===title),id=existing?.id||uid(),mediaType=file.type.startsWith("video/")?"video":"audio";await putBlob(id,file);await putRecord({...(existing||{}),id,kind:"media",mediaType,title,fileName:file.name,type:file.type,size:file.size,favorite:existing?.favorite||false,createdAt:existing?.createdAt||now(),updatedAt:now()});}mediaInput.value="";await refresh();toast("影音已保存到本機");});
function exportBackup(){const payload={app:"立之雲端庫・本機版",version:1,exportedAt:now(),records:state.records};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`立之雲端庫-資料目錄-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("已匯出資料目錄");}
restoreInput.addEventListener("change",async()=>{const file=restoreInput.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(!Array.isArray(payload.records))throw new Error("格式不正確");for(const row of payload.records)await putRecord(row);await refresh();toast("資料目錄已匯入");}catch{toast("備份檔格式不正確");}restoreInput.value="";});

async function boot(){
  if(IS_CLOUD_SITE&&window.LizhiAuth&&!await window.LizhiAuth.requireUser())return;
  initializeChatIdentity();
  initializeDelivery();
  installWorkspaceEvents();
  KnowledgeWeaving.installEvents(app);
  FinanceHome.installEvents(app);
  const knowledgeService=new KnowledgeService({
    local:new LocalKnowledgeAdapter({records:()=>state.records,put:putRecord,afterSave:refresh}),
    vault:new VaultKnowledgeAdapter({enabled:!IS_CLOUD_SITE})
  });
  KnowledgeHome.configure({service:knowledgeService,rerender:()=>{if(state.route==="knowledge")render();}});
  KnowledgeHome.installEvents(app);
  KnowledgeEditor.configure({service:knowledgeService,rerender:()=>{if(state.route==="knowledge")render();}});
  KnowledgeEditor.installEvents(app);
  KnowledgeEditor.restore();
  if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").then(registration=>registration.update()).catch(()=>{});
  seed().then(loadCloudMedia).then(refresh).catch(error=>{app.innerHTML=`<div class="empty">無法開啟資料庫：${escapeHtml(error.message)}</div>`;});
}
boot();
