(function(root,factory){const isNode=typeof module==="object"&&module.exports,api=factory(isNode?require("./quote-model.js"):root.EngineeringQuoteModel);if(isNode)module.exports=api;else root.EngineeringQuoteService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(Model){
  "use strict";class QuoteServiceError extends Error{constructor(code,message,details={},cause){super(message,{cause});this.name="QuoteServiceError";this.code=code;this.details=Object.freeze({...details});}}const id=()=>globalThis.crypto?.randomUUID?.()||`quote-${Date.now()}-${Math.random().toString(16).slice(2)}`,round=value=>Math.round(Number(value)),stampDate=value=>String(value).slice(0,10).replaceAll("-","");
  const latestPrices=entries=>{const map=new Map();for(const entry of entries||[]){const current=map.get(entry.bom_item_id);if(!current||entry.version>current.version)map.set(entry.bom_item_id,entry);}return map;};
  function priceLines(bom,entries){const prices=latestPrices(entries);return bom.items.map(item=>{const price=prices.get(item.id),unitPrice=price?price.unit_price:null;return{id:item.id,source_bom_item_id:item.id,logical_part_key:item.logical_part_key,description:item.description,quantity:item.quantity,unit:"piece",unit_price:unitPrice,line_total:unitPrice==null?null:round(item.quantity*unitPrice),price_source:price?.source||null,price_entry_id:price?.id||null,material_label:item.material_label||"",metadata:{dimensions:item.dimensions}};});}
  function totals(lines){if(lines.some(line=>line.unit_price==null))return{subtotal:null,tax:0,total:null};const subtotal=round(lines.reduce((sum,line)=>sum+line.line_total,0));return{subtotal,tax:0,total:subtotal};}
  function create({repository,now=()=>new Date().toISOString(),idGenerator=id}={}){if(!repository)throw new TypeError("Quote Service repository is required");
    const build=(bom,entries,{quoteId=idGenerator(),version=1,createdAt=now(),rootId=null}={})=>{const lines=priceLines(bom,entries),amounts=totals(lines),quoteNumber=`Q-${stampDate(createdAt)}-${String(rootId||quoteId).replace(/[^a-z0-9]/gi,"").slice(0,8).toUpperCase()}-R${version}`;return Model.create({id:quoteId,quote_number:quoteNumber,project_id:bom.project_id,design_id:bom.design_id,bom_id:bom.id,version,status:"draft",currency:"TWD",lines,...amounts,adjustments:[],rounding_policy:"TWD-0-HALF-UP",snapshot:null,created_at:createdAt,updated_at:createdAt,published_at:null,metadata:{root_quote_id:rootId||quoteId,bom_version:bom.version,design_revision:bom.design_revision,template_id:bom.template_id,template_version:bom.template_version}});};
    async function owned(projectId,quoteId){const quote=await repository.getById(quoteId);if(!quote||quote.project_id!==String(projectId))throw new QuoteServiceError("QUOTE_NOT_FOUND","找不到此專案的 Quote。");return quote;}
    return Object.freeze({async createDraft(projectId,bom,entries=[]){if(!bom||bom.project_id!==String(projectId))throw new QuoteServiceError("BOM_NOT_FOUND","找不到此專案的 BOM。");const draft=build(bom,entries);try{return await repository.create(draft);}catch(error){throw new QuoteServiceError("QUOTE_SAVE_FAILED","Quote Draft 保存失敗。",{draft},error);}},async repriceDraft(projectId,quoteId,bom,entries){const current=await owned(projectId,quoteId);if(current.status!=="draft")throw new QuoteServiceError("QUOTE_IMMUTABLE","Published Quote 不可重新計價。");const lines=priceLines(bom,entries),amounts=totals(lines),updated=Model.create({...current,lines,...amounts,updated_at:now()});try{return await repository.updateDraft(updated);}catch(error){throw new QuoteServiceError("QUOTE_SAVE_FAILED","Quote Draft 保存失敗。",{draft:updated},error);}},async newRevision(projectId,published,bom,entries=[]){if(published.status!=="published"||published.project_id!==String(projectId))throw new QuoteServiceError("QUOTE_REVISION_SOURCE_INVALID","只能從已發布 Quote 建立新版本。");const draft=build(bom,entries,{version:published.version+1,rootId:published.metadata.root_quote_id});return repository.create(draft);},get:owned,listByProject:projectId=>repository.listByProject(String(projectId)),validateForPublish(quote){const issues=[];if(quote.status!=="draft")issues.push({code:"QUOTE_NOT_DRAFT",message:"只有 Draft 可以發布。"});for(const line of quote.lines){if(line.unit_price==null)issues.push({code:"PRICE_MISSING",lineId:line.id,message:`${line.description} 尚未輸入人工單價。`});if(!Number.isInteger(line.quantity)||line.quantity<=0)issues.push({code:"QUANTITY_INVALID",lineId:line.id,message:"數量不正確。"});}if(quote.total==null)issues.push({code:"TOTAL_UNRESOLVED",message:"報價總額尚未完成。"});return Object.freeze(issues);}});
  }
  return Object.freeze({QuoteServiceError,create,priceLines,totals,ROUNDING_POLICY:"TWD-0-HALF-UP"});
});
