(() => {
  "use strict";
  let PAGE_W = 794, PAGE_H = 1123;
  const GRID = 16;
  const clone = value => JSON.parse(JSON.stringify(value));
  const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
  const snap = v => state.snap ? Math.round(v / GRID) * GRID : Math.round(v);
  const uid = () => `text-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const escapeHtml = text => text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const $ = id => document.getElementById(id);
  function tableWeights(values,count){const safe=Array.isArray(values)?values.slice(0,count).map(value=>Math.max(.05,Number(value)||1)):[];const average=safe.length?safe.reduce((sum,value)=>sum+value,0)/safe.length:1;while(safe.length<count)safe.push(average);return safe}
  function tableTracks(values,total){const sum=values.reduce((amount,value)=>amount+value,0)||1,sizes=values.map(value=>value/sum*total),offsets=[0];sizes.forEach(size=>offsets.push(offsets[offsets.length-1]+size));return{sizes,offsets}}
  function addTableDividers(block,b){if(b.id!==state.selectedId||b.locked)return;const columns=tableTracks(b.colWidths,b.w).offsets,rows=tableTracks(b.rowHeights,b.h).offsets;for(let index=1;index<columns.length-1;index++){const divider=document.createElement("button");divider.className="table-divider column-divider";divider.style.left=`${columns[index]/b.w*100}%`;divider.ariaLabel=`拖曳第 ${index} 欄分隔線`;divider.addEventListener("pointerdown",event=>startTableDivider(event,b,"column",index-1));block.append(divider)}for(let index=1;index<rows.length-1;index++){const divider=document.createElement("button");divider.className="table-divider row-divider";divider.style.top=`${rows[index]/b.h*100}%`;divider.ariaLabel=`拖曳第 ${index} 列分隔線`;divider.addEventListener("pointerdown",event=>startTableDivider(event,b,"row",index-1));block.append(divider)}}
  function updateTableGeometry(b){const block=[...document.querySelectorAll(".table-block")].find(element=>element.dataset.id===b.id);if(!block)return;const columns=tableTracks(b.colWidths,b.w),rows=tableTracks(b.rowHeights,b.h),grid=block.querySelector(".table-grid");grid.style.gridTemplateColumns=b.colWidths.map(value=>`${value}fr`).join(" ");grid.style.gridTemplateRows=b.rowHeights.map(value=>`${value}fr`).join(" ");block.querySelectorAll(".column-divider").forEach((divider,index)=>divider.style.left=`${columns.offsets[index+1]/b.w*100}%`);block.querySelectorAll(".row-divider").forEach((divider,index)=>divider.style.top=`${rows.offsets[index+1]/b.h*100}%`);save()}
  function tableMerges(b){if(!Array.isArray(b.merges))b.merges=[];b.merges=b.merges.filter(m=>m&&m.row>=0&&m.col>=0&&m.row<b.rows&&m.col<b.cols&&m.rowSpan>0&&m.colSpan>0);b.merges.forEach(m=>{m.rowSpan=Math.min(m.rowSpan,b.rows-m.row);m.colSpan=Math.min(m.colSpan,b.cols-m.col)});return b.merges}
  function cellRegion(b,index){const row=Math.floor(index/b.cols),col=index%b.cols,merge=tableMerges(b).find(m=>row>=m.row&&row<m.row+m.rowSpan&&col>=m.col&&col<m.col+m.colSpan);return merge||{row,col,rowSpan:1,colSpan:1}}
  function masterIndex(b,index){const region=cellRegion(b,index);return region.row*b.cols+region.col}
  function cellIsHidden(b,index){return masterIndex(b,index)!==index}
  function documentData(){return{blocks:state.blocks,title:$("doc-title").value,orientation:state.orientation,editingTemplateId:state.editingTemplateId,pageCount:state.pageCount,currentPage:state.currentPage,headerText:state.headerText,footerText:state.footerText,showPageNumber:state.showPageNumber,pageNumberAlign:state.pageNumberAlign}}

  const starters = [
    {id:"title",x:64,y:70,w:666,h:62,text:"未命名文件",fontSize:32,fontFamily:"Noto Serif TC",bold:true,italic:false,align:"left",color:"#17212b",lineHeight:1.2},
    {id:"meta",x:64,y:142,w:666,h:34,text:"A4 GRID DOCUMENT  ·  2026",fontSize:10,fontFamily:"Arial",bold:true,italic:false,align:"left",color:"#74808b",lineHeight:1.4},
    {id:"heading-1",x:64,y:224,w:206,h:44,text:"01  文件摘要",fontSize:15,fontFamily:"Noto Sans TC",bold:true,italic:false,align:"left",color:"#167d78",lineHeight:1.35},
    {id:"body-1",x:288,y:224,w:442,h:182,text:"點擊這段文字即可開始輸入。每個文字框都有自己的固定位置與大小，因此輸入內容時，不會推擠或移動頁面上的其他文字。\n\n拖曳文字框上方的把手可以自由移動；右下角則可以調整文字框大小。",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.72},
    {id:"heading-2",x:64,y:454,w:206,h:44,text:"02  重點內容",fontSize:15,fontFamily:"Noto Sans TC",bold:true,italic:false,align:"left",color:"#167d78",lineHeight:1.35},
    {id:"body-2",x:288,y:454,w:442,h:246,text:"在這裡整理你的內容：\n\n• 使用左側工具新增文字框\n• 開啟吸附功能，快速對齊網格\n• 選取文字框後，可調整字型、尺寸與對齊\n• 完成後，從右上角匯出 Word 或 PDF",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.78},
    {id:"quote",x:64,y:762,w:666,h:142,text:"「好的版面，讓每一段內容都待在它應該在的位置。」",fontSize:21,fontFamily:"Noto Serif TC",bold:false,italic:false,align:"center",color:"#17212b",lineHeight:1.6},
    {id:"footer",x:64,y:1040,w:666,h:28,text:"A4 · 210 × 297 mm                                            01",fontSize:9,fontFamily:"Arial",bold:false,italic:false,align:"left",color:"#98a0a8",lineHeight:1.4}
  ];
  const builtInTemplate={id:"built-in-summary",name:"A4 專案摘要",blocks:clone(starters),orientation:"portrait",createdAt:"內建模板",builtIn:true};
  let savedTemplates=[];try{savedTemplates=JSON.parse(localStorage.getItem("paper-grid-templates-v4"))||[]}catch{}
  const state = {blocks:clone(starters),selectedId:"body-1",activeCell:null,orientation:"portrait",zoom:innerWidth<520?.44:innerWidth<820?.62:.72,grid:true,snap:true,history:[],future:[],drag:null,templates:[builtInTemplate,...savedTemplates],editingTemplateId:null,clipboard:null,findIndex:-1,pageCount:1,currentPage:0,headerText:"",footerText:"",showPageNumber:true,pageNumberAlign:"right",batchFiles:[],batchTargetId:null,batchPreviewUrls:[]};
  try { const saved=JSON.parse(localStorage.getItem("paper-grid-studio-v4")); if(saved?.blocks?.length) state.blocks=saved.blocks; if(saved?.title) $("doc-title").value=saved.title; if(saved?.orientation==="landscape"){state.orientation="landscape";PAGE_W=1123;PAGE_H=794} if(saved?.editingTemplateId&&state.templates.some(t=>t.id===saved.editingTemplateId))state.editingTemplateId=saved.editingTemplateId;state.pageCount=Math.max(1,+saved?.pageCount||1);state.currentPage=clamp(+saved?.currentPage||0,0,state.pageCount-1);state.headerText=saved?.headerText||"";state.footerText=saved?.footerText||"";state.showPageNumber=saved?.showPageNumber!==false;state.pageNumberAlign=["left","center","right"].includes(saved?.pageNumberAlign)?saved.pageNumberAlign:"right"; } catch {}
  state.blocks.forEach(b=>{if(!Number.isInteger(b.page))b.page=0});
  $("header-text").value=state.headerText;$("footer-text").value=state.footerText;$("show-page-number").checked=state.showPageNumber;$("page-number-align").value=state.pageNumberAlign;

  function selected(){ return state.blocks.find(b=>b.id===state.selectedId); }
  function save(){ clearTimeout(save.timer); save.timer=setTimeout(()=>{try{localStorage.setItem("paper-grid-studio-v4",JSON.stringify(documentData()))}catch(error){console.error(error);notify("儲存空間不足，請刪除部分大型圖片")}},250); }
  function checkpoint(){ state.history.push(clone(state.blocks)); if(state.history.length>40) state.history.shift(); state.future=[]; updateUndo(); }
  function updateUndo(){ $("undo").disabled=!state.history.length; $("redo").disabled=!state.future.length; }
  function updateZoom(){ $("page").style.width=`${PAGE_W}px`;$("page").style.height=`${PAGE_H}px`;$("page").style.transform=`scale(${state.zoom})`; $("page-shell").style.width=`${PAGE_W*state.zoom}px`; $("page-shell").style.height=`${PAGE_H*state.zoom}px`; $("zoom-value").textContent=`${Math.round(state.zoom*100)}%`;$("page-size").textContent=state.orientation==="portrait"?"210 × 297 mm · 直向":"297 × 210 mm · 橫向";$("orientation-status").textContent=state.orientation==="portrait"?"直向":"橫向";$("orientation-label").textContent=state.orientation==="portrait"?"切換橫向":"切換直向";$("page-indicator").textContent=`第 ${state.currentPage+1} / ${state.pageCount} 頁`;$("previous-page").disabled=state.currentPage===0;$("next-page").disabled=state.currentPage===state.pageCount-1; }
  function styleTextarea(area,b){ const decorations=[b.underline?"underline":"",b.strike?"line-through":""].filter(Boolean).join(" ");Object.assign(area.style,{fontFamily:`"${b.fontFamily}",sans-serif`,fontSize:`${b.fontSize}px`,fontWeight:b.bold?"700":"400",fontStyle:b.italic?"italic":"normal",textDecoration:decorations||"none",textAlign:b.align,color:b.color,backgroundColor:b.highlight||"transparent",lineHeight:b.lineHeight,paddingLeft:`${8+(b.indent||0)}px`}); }
  function render(){
    document.querySelectorAll(".text-block,.page-header,.page-footer").forEach(el=>el.remove());
    if(state.headerText){const header=document.createElement("div");header.className="page-header";header.textContent=state.headerText;$("page").append(header)}
    if(state.footerText||state.showPageNumber){const footer=document.createElement("div");footer.className="page-footer";if(state.footerText){const text=document.createElement("span");text.textContent=state.footerText;footer.append(text)}if(state.showPageNumber){const number=document.createElement("span");number.className=`page-footer-number ${state.pageNumberAlign}`;number.textContent=String(state.currentPage+1);footer.append(number)}$("page").append(footer)}
    state.blocks.filter(b=>(b.page||0)===state.currentPage).forEach(b=>{
      const block=document.createElement("div"); block.className=`text-block${b.id===state.selectedId?" selected":""}${b.locked?" locked":""}${b.border?" grid-cell":""}${b.type==="table"?" table-block":""}${b.type==="table"&&b.photoTarget?" photo-target":""}${b.type==="image"?" image-block":""}${b.type==="image"&&b.wrap==="behind"?" behind-text":""}`; block.dataset.id=b.id; Object.assign(block.style,{left:`${b.x}px`,top:`${b.y}px`,width:`${b.w}px`,height:`${b.h}px`});
      if(b.id===state.selectedId){ const handle=document.createElement("button"); handle.className="drag-handle"; handle.ariaLabel="拖曳物件"; handle.innerHTML="<i></i><i></i><i></i>"; handle.addEventListener("pointerdown",e=>startDrag(e,b,"move")); block.append(handle); }
      if(b.type==="image"){
        const image=document.createElement("img");image.src=b.src;image.alt=b.name||"插入圖片";image.draggable=false;image.classList.toggle("fit-cover",b.fit==="cover");image.style.objectPosition=`${b.positionX??50}% ${b.positionY??50}%`;block.append(image);
      }else if(b.type==="table"){
        const grid=document.createElement("div");grid.className="table-grid";b.colWidths=tableWeights(b.colWidths,b.cols);b.rowHeights=tableWeights(b.rowHeights,b.rows);grid.style.gridTemplateColumns=b.colWidths.map(value=>`${value}fr`).join(" ");grid.style.gridTemplateRows=b.rowHeights.map(value=>`${value}fr`).join(" ");
        const total=b.rows*b.cols;if(!Array.isArray(b.cells))b.cells=[];while(b.cells.length<total)b.cells.push("");b.cells=b.cells.slice(0,total);if(!Array.isArray(b.cellImages))b.cellImages=[];b.cellImages=b.cellImages.slice(0,total);
        b.cells.forEach((value,index)=>{if(cellIsHidden(b,index))return;const region=cellRegion(b,index),wrap=document.createElement("div"),cell=document.createElement("textarea"),cellImage=b.cellImages[index];wrap.className=`table-cell-wrap${cellImage?" has-image":""}${cellImage&&b.photoTarget?" batch-photo-filled":""}${region.rowSpan>1||region.colSpan>1?" merged-cell":""}${state.activeCell?.blockId===b.id&&masterIndex(b,state.activeCell.index)===index?" active-cell":""}`;wrap.style.gridRow=`${region.row+1} / span ${region.rowSpan}`;wrap.style.gridColumn=`${region.col+1} / span ${region.colSpan}`;wrap.addEventListener("pointerdown",()=>{state.activeCell={blockId:b.id,index}});if(cellImage){const image=document.createElement("img");image.className="cell-image";image.src=cellImage.src;image.alt=cellImage.name||"儲存格圖片";image.draggable=false;wrap.append(image)}cell.className="table-cell";cell.value=value;cell.readOnly=!!b.locked;cell.ariaLabel=`表格第 ${region.row+1} 列第 ${region.col+1} 欄`;styleTextarea(cell,b);cell.addEventListener("focus",()=>{state.activeCell={blockId:b.id,index};select(b.id)});cell.addEventListener("input",()=>{b.cells[index]=cell.value;save()});wrap.append(cell);grid.append(wrap)});block.append(grid);addTableDividers(block,b);
      }else{
        const area=document.createElement("textarea"); area.value=b.text; area.readOnly=!!b.locked; area.ariaLabel="文字內容"; styleTextarea(area,b); area.addEventListener("focus",()=>select(b.id)); area.addEventListener("input",()=>{b.text=area.value;save()}); block.append(area);
      }
      if(b.id===state.selectedId&&!b.locked){ const resize=document.createElement("button"); resize.className="resize-handle"; resize.ariaLabel="調整文字框大小"; resize.addEventListener("pointerdown",e=>startDrag(e,b,"resize")); block.append(resize); }
      block.addEventListener("pointerdown",e=>{e.stopPropagation();if(state.selectedId!==b.id)select(b.id)}); $("page").append(block);
    });
    $("block-count").textContent=`本頁 ${state.blocks.filter(b=>(b.page||0)===state.currentPage).length} 個物件 · 共 ${state.pageCount} 頁`;updateZoom(); renderInspector(); save();
  }
  function select(id){ if(state.selectedId===id)return; state.selectedId=id;if(state.activeCell?.blockId!==id)state.activeCell=null; render(); }
  function renderInspector(){
    const b=selected(), empty=$("empty-inspector"), props=$("properties"),isImage=b?.type==="image",isTable=b?.type==="table"; empty.hidden=!!b; props.hidden=!b; $("lock").disabled=!b;$("text-properties").hidden=!!isImage;$("table-properties").hidden=!isTable;$("image-properties").hidden=!isImage;props.classList.toggle("image-mode",!!isImage);
    renderRibbon();if(!b){document.querySelector(".inspector-head h2").textContent="文字設定";return}document.querySelector(".inspector-head h2").textContent=isImage?"圖片設定":isTable?"表格文字設定":"文字設定";$("pos-x").value=Math.round(b.x); $("pos-y").value=Math.round(b.y); $("width").value=Math.round(b.w); $("height").value=Math.round(b.h);$("lock").classList.toggle("active",!!b.locked);if(isTable){$("selected-table-rows").value=b.rows;$("selected-table-cols").value=b.cols;$("mark-photo-table").classList.toggle("active",!!b.photoTarget);$("mark-photo-table").textContent=b.photoTarget?"✓ 模板照片表格":"設為模板照片表格"}if(isImage){$("image-fit").value=b.fit||"contain";$("image-position-x").value=b.positionX??50;$("image-position-y").value=b.positionY??50;$("image-wrap").value=b.wrap||"front";return}$("font-family").value=b.fontFamily; $("font-size").value=b.fontSize; $("line-height").value=b.lineHeight; $("color").value=b.color; $("color-code").textContent=b.color.toUpperCase(); $("bold").classList.toggle("active",b.bold); $("italic").classList.toggle("active",b.italic); document.querySelectorAll("[data-align]").forEach(btn=>btn.classList.toggle("active",btn.dataset.align===b.align));
  }
  function renderRibbon(){const b=selected(),textBlock=b&&b.type!=="image",objectIds=["cut-block","copy-block"],textIds=["font-smaller","font-larger","ribbon-bold","ribbon-italic","ribbon-underline","ribbon-strike","bullet-list","number-list","outdent","indent"];objectIds.forEach(id=>$(id).disabled=!b);textIds.forEach(id=>$(id).disabled=!textBlock);$("paste-block").disabled=!state.clipboard;$("ribbon-font").disabled=!textBlock;$("ribbon-size").disabled=!textBlock;$("ribbon-line-height").disabled=!textBlock;$("ribbon-color").disabled=!textBlock;$("ribbon-highlight").disabled=!textBlock;document.querySelectorAll("[data-ribbon-align]").forEach(btn=>btn.disabled=!textBlock);if(!textBlock)return;$("ribbon-font").value=b.fontFamily;$("ribbon-size").value=b.fontSize;$("ribbon-line-height").value=String([1,1.2,1.5,1.75,2].reduce((a,v)=>Math.abs(v-b.lineHeight)<Math.abs(a-b.lineHeight)?v:a,1));$("ribbon-color").value=b.color||"#263541";$("ribbon-highlight").value=b.highlight||"#fff2a8";$("ribbon-bold").classList.toggle("active",!!b.bold);$("ribbon-italic").classList.toggle("active",!!b.italic);$("ribbon-underline").classList.toggle("active",!!b.underline);$("ribbon-strike").classList.toggle("active",!!b.strike);document.querySelectorAll("[data-ribbon-align]").forEach(btn=>btn.classList.toggle("active",btn.dataset.ribbonAlign===b.align))}
  function saveNow(){try{localStorage.setItem("paper-grid-studio-v4",JSON.stringify(documentData()));notify("文件已儲存")}catch(error){console.error(error);notify("儲存空間不足，請刪除部分大型圖片")}}
  function setOrientation(orientation,fitBlocks=false){const nextW=orientation==="landscape"?1123:794,nextH=orientation==="landscape"?794:1123;if(fitBlocks&&(nextW!==PAGE_W||nextH!==PAGE_H)){const rx=nextW/PAGE_W,ry=nextH/PAGE_H;state.blocks.forEach(b=>{b.x=Math.round(b.x*rx);b.y=Math.round(b.y*ry);b.w=Math.max(80,Math.round(b.w*rx));b.h=Math.max(b.type==="table"?b.rows*28:40,Math.round(b.h*ry))})}PAGE_W=nextW;PAGE_H=nextH;state.orientation=orientation;updateZoom()}
  function toggleOrientation(){checkpoint();setOrientation(state.orientation==="portrait"?"landscape":"portrait",true);render();notify(`已切換為 A4 ${state.orientation==="portrait"?"直向":"橫向"}`)}
  function newDocument(){if(!confirm("建立新文件會清除目前畫布，確定繼續嗎？"))return;checkpoint();state.editingTemplateId=null;state.pageCount=1;state.currentPage=0;state.headerText="";state.footerText="";state.showPageNumber=true;state.pageNumberAlign="right";$("header-text").value="";$("footer-text").value="";$("show-page-number").checked=true;$("page-number-align").value="right";setOrientation("portrait");state.blocks=[{id:uid(),page:0,x:64,y:64,w:666,h:64,text:"未命名文件",fontSize:32,fontFamily:"Noto Serif TC",bold:true,italic:false,align:"left",color:"#17212b",lineHeight:1.2}];state.selectedId=state.blocks[0].id;$("doc-title").value="未命名文件";updateEditingUI();render();saveNow()}
  function saveProject(){const title=$("doc-title").value||"A4文件",data={format:"paper-grid-a4",version:3,...documentData()};delete data.editingTemplateId;delete data.currentPage;download(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),`${title}.a4doc`);notify("可編輯專案檔已下載")}
  function openProjectFile(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.format!=="paper-grid-a4"||!Array.isArray(data.blocks))throw new Error();checkpoint();state.editingTemplateId=null;setOrientation(data.orientation==="landscape"?"landscape":"portrait");state.blocks=data.blocks;state.blocks.forEach(b=>{if(!Number.isInteger(b.page))b.page=0});state.pageCount=Math.max(1,+data.pageCount||1,1+Math.max(0,...state.blocks.map(b=>b.page||0)));state.currentPage=0;state.headerText=data.headerText||"";state.footerText=data.footerText||"";state.showPageNumber=data.showPageNumber!==false;state.pageNumberAlign=["left","center","right"].includes(data.pageNumberAlign)?data.pageNumberAlign:"right";$("header-text").value=state.headerText;$("footer-text").value=state.footerText;$("show-page-number").checked=state.showPageNumber;$("page-number-align").value=state.pageNumberAlign;state.selectedId=state.blocks.find(b=>(b.page||0)===0)?.id||"";$("doc-title").value=data.title||"已開啟文件";updateEditingUI();render();saveNow()}catch{notify("無法開啟此專案檔")}};reader.readAsText(file)}
  function goToPage(page){state.currentPage=clamp(page,0,state.pageCount-1);state.selectedId="";state.activeCell=null;render()}
  function addPage(){checkpoint();state.pageCount+=1;state.currentPage=state.pageCount-1;state.selectedId="";state.activeCell=null;render();notify(`已新增第 ${state.pageCount} 頁`)}
  function duplicatePage(){checkpoint();const source=state.currentPage,newPage=source+1;state.blocks.forEach(b=>{if((b.page||0)>source)b.page+=1});const copies=state.blocks.filter(b=>(b.page||0)===source).map(b=>({...clone(b),id:uid(),page:newPage,locked:false}));state.blocks.push(...copies);state.pageCount+=1;state.currentPage=newPage;state.selectedId=copies[0]?.id||"";render();notify("目前頁面已複製")}
  function deletePage(){if(state.pageCount===1){notify("文件至少需要保留一頁");return}if(!confirm(`確定刪除第 ${state.currentPage+1} 頁？`))return;checkpoint();const removed=state.currentPage;state.blocks=state.blocks.filter(b=>(b.page||0)!==removed);state.blocks.forEach(b=>{if((b.page||0)>removed)b.page-=1});state.pageCount-=1;state.currentPage=Math.min(removed,state.pageCount-1);state.selectedId="";state.activeCell=null;render();notify("頁面已刪除")}
  const blockText=b=>b.type==="table"?(b.cells||[]).join("\n"):String(b.text||"");
  function findMatches(){const term=$("find-text").value;if(!term)return[];return state.blocks.map((b,index)=>({b,index,count:blockText(b).split(term).length-1})).filter(item=>item.count>0)}
  function findNext(){const matches=findMatches();if(!matches.length){$("find-result").textContent="找不到符合的文字。";return}state.findIndex=(state.findIndex+1)%matches.length;state.selectedId=matches[state.findIndex].b.id;render();$("find-result").textContent=`找到 ${matches.reduce((n,m)=>n+m.count,0)} 處，目前位於第 ${state.findIndex+1} 個文字框。`}
  function replaceAll(){const term=$("find-text").value,replacement=$("replace-text").value;if(!term)return;const matches=findMatches(),total=matches.reduce((n,m)=>n+m.count,0);if(!total){$("find-result").textContent="找不到符合的文字。";return}checkpoint();state.blocks.forEach(b=>{if(b.type==="table")b.cells=(b.cells||[]).map(cell=>cell.split(term).join(replacement));else b.text=String(b.text||"").split(term).join(replacement)});render();$("find-result").textContent=`已完成 ${total} 處取代。`}
  function update(changes,history=true){ const b=selected(); if(!b)return; if(history)checkpoint(); Object.assign(b,changes); render(); }
  function addText(){ checkpoint(); const n=state.blocks.length,b={id:uid(),page:state.currentPage,x:80+(n%3)*16,y:180+(n%10)*48,w:320,h:96,text:"在此輸入文字",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.6}; state.blocks.push(b); state.selectedId=b.id; render(); }
  const fileDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
  const imageElement=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
  async function normalizeImageFile(file,{maxPixels=1400,quality=.84,photoMode=false}={}){if(!file?.type.startsWith("image/"))throw new Error("not image");const original=await fileDataUrl(file),image=await imageElement(original),scale=Math.min(1,maxPixels/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext("2d");if(photoMode){context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height)}context.drawImage(image,0,0,canvas.width,canvas.height);const mime=photoMode?"image/jpeg":file.type==="image/png"?"image/png":"image/jpeg",src=canvas.toDataURL(mime,mime==="image/jpeg"?quality:undefined);return{src,name:file.name||"圖片",ratio:image.naturalWidth/image.naturalHeight,fit:"contain"}}
  async function addImageFile(file){try{const imageData=await normalizeImageFile(file),target=selected();if(target?.type==="table"&&state.activeCell?.blockId===target.id){checkpoint();if(!Array.isArray(target.cellImages))target.cellImages=[];target.cellImages[masterIndex(target,state.activeCell.index)]=imageData;render();notify("圖片已放入選取的儲存格");return}let w=Math.min(420,PAGE_W-128),h=w/imageData.ratio;if(h>PAGE_H-128){h=PAGE_H-128;w=h*imageData.ratio}const n=state.blocks.length,x=clamp(80+(n%3)*16,0,PAGE_W-w),y=clamp(180+(n%8)*48,0,PAGE_H-h),b={id:uid(),page:state.currentPage,type:"image",...imageData,positionX:50,positionY:50,wrap:"front",x:Math.round(x),y:Math.round(y),w:Math.round(w),h:Math.round(h)};checkpoint();state.blocks.push(b);state.selectedId=b.id;state.activeCell=null;render();notify("圖片已插入，可拖曳、縮放或裁切")}catch(error){console.error(error);notify("無法讀取這張圖片")}}
  function resizeTable(rows,cols){const b=selected();if(b?.type!=="table")return;rows=clamp(+rows||b.rows,1,12);cols=clamp(+cols||b.cols,1,8);if(rows===b.rows&&cols===b.cols)return;checkpoint();const oldRows=b.rows,oldCols=b.cols,oldCells=b.cells||[],oldImages=b.cellImages||[],oldColWidths=tableWeights(b.colWidths,oldCols),oldRowHeights=tableWeights(b.rowHeights,oldRows),cells=Array(rows*cols).fill(""),cellImages=Array(rows*cols).fill(null);for(let row=0;row<Math.min(rows,oldRows);row++)for(let col=0;col<Math.min(cols,oldCols);col++){const oldIndex=row*oldCols+col,newIndex=row*cols+col;cells[newIndex]=oldCells[oldIndex]||"";cellImages[newIndex]=oldImages[oldIndex]||null}const cellW=b.w/oldCols,cellH=b.h/oldRows;b.rows=rows;b.cols=cols;b.cells=cells;b.cellImages=cellImages;b.merges=[];b.colWidths=tableWeights(oldColWidths,cols);b.rowHeights=tableWeights(oldRowHeights,rows);b.w=Math.round(clamp(cellW*cols,80,PAGE_W-b.x));b.h=Math.round(clamp(cellH*rows,rows*28,PAGE_H-b.y));if(state.activeCell?.blockId===b.id&&state.activeCell.index>=rows*cols)state.activeCell=null;render();notify(`表格已調整為 ${rows} × ${cols}`)}
  function addTable(){checkpoint();const rows=clamp(+$("table-rows").value||3,1,12),cols=clamp(+$("table-cols").value||3,1,8),n=state.blocks.length,w=Math.min(480,PAGE_W-128),h=Math.min(PAGE_H-96,Math.max(96,rows*48)),x=clamp(80+(n%3)*16,0,PAGE_W-w),y=clamp(180+(n%8)*48,0,PAGE_H-h),b={id:uid(),page:state.currentPage,type:"table",rows,cols,cells:Array(rows*cols).fill(""),cellImages:Array(rows*cols).fill(null),merges:[],colWidths:Array(cols).fill(1),rowHeights:Array(rows).fill(1),x,y,w,h,fontSize:13,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"center",color:"#263541",lineHeight:1.35};state.blocks.push(b);state.selectedId=b.id;state.activeCell={blockId:b.id,index:0};render();notify(`已插入 ${rows} × ${cols} 表格`)}
  function activeTableCell(){const b=selected();if(b?.type!=="table")return null;const raw=state.activeCell?.blockId===b.id?state.activeCell.index:0,index=masterIndex(b,clamp(raw,0,b.rows*b.cols-1));return{b,index,row:Math.floor(index/b.cols),col:index%b.cols}}
  function insertTableAxis(axis){const active=activeTableCell();if(!active)return;const{b,row,col}=active;if(axis==="row"&&b.rows>=12){notify("表格最多 12 列");return}if(axis==="col"&&b.cols>=8){notify("表格最多 8 欄");return}checkpoint();b.merges=[];const oldRows=b.rows,oldCols=b.cols,oldCells=b.cells.slice(),oldImages=(b.cellImages||[]).slice();if(axis==="row"){const at=row+1;b.rows+=1;b.cells=Array(b.rows*b.cols).fill("");b.cellImages=Array(b.rows*b.cols).fill(null);for(let r=0;r<oldRows;r++)for(let c=0;c<oldCols;c++){const nr=r>=at?r+1:r;b.cells[nr*b.cols+c]=oldCells[r*oldCols+c]||"";b.cellImages[nr*b.cols+c]=oldImages[r*oldCols+c]||null}b.rowHeights.splice(at,0,b.rowHeights[row]||1);b.h=clamp(Math.round(b.h/oldRows*b.rows),b.rows*28,PAGE_H-b.y);state.activeCell={blockId:b.id,index:at*b.cols+col}}else{const at=col+1;b.cols+=1;b.cells=Array(b.rows*b.cols).fill("");b.cellImages=Array(b.rows*b.cols).fill(null);for(let r=0;r<oldRows;r++)for(let c=0;c<oldCols;c++){const nc=c>=at?c+1:c;b.cells[r*b.cols+nc]=oldCells[r*oldCols+c]||"";b.cellImages[r*b.cols+nc]=oldImages[r*oldCols+c]||null}b.colWidths.splice(at,0,b.colWidths[col]||1);b.w=clamp(Math.round(b.w/oldCols*b.cols),80,PAGE_W-b.x);state.activeCell={blockId:b.id,index:row*b.cols+at}}render();notify(axis==="row"?"已在下方新增一列":"已在右側新增一欄")}
  function deleteTableAxis(axis){const active=activeTableCell();if(!active)return;const{b,row,col}=active;if(axis==="row"&&b.rows===1||axis==="col"&&b.cols===1){notify("表格至少需要一列與一欄");return}checkpoint();b.merges=[];const oldRows=b.rows,oldCols=b.cols,oldCells=b.cells.slice(),oldImages=(b.cellImages||[]).slice();if(axis==="row"){b.rows-=1;b.cells=[];b.cellImages=[];for(let r=0;r<oldRows;r++)if(r!==row)for(let c=0;c<oldCols;c++){b.cells.push(oldCells[r*oldCols+c]||"");b.cellImages.push(oldImages[r*oldCols+c]||null)}b.rowHeights.splice(row,1);b.h=Math.max(b.rows*28,Math.round(b.h/oldRows*b.rows));state.activeCell={blockId:b.id,index:Math.min(row,b.rows-1)*b.cols+col}}else{b.cols-=1;b.cells=[];b.cellImages=[];for(let r=0;r<oldRows;r++)for(let c=0;c<oldCols;c++)if(c!==col){b.cells.push(oldCells[r*oldCols+c]||"");b.cellImages.push(oldImages[r*oldCols+c]||null)}b.colWidths.splice(col,1);b.w=Math.max(80,Math.round(b.w/oldCols*b.cols));state.activeCell={blockId:b.id,index:row*b.cols+Math.min(col,b.cols-1)}}render();notify(axis==="row"?"此列已刪除":"此欄已刪除")}
  function mergeCell(direction){const active=activeTableCell();if(!active)return;const{b,index}=active,a=cellRegion(b,index),targetIndex=direction==="right"?a.row*b.cols+a.col+a.colSpan:(a.row+a.rowSpan)*b.cols+a.col;if(direction==="right"&&a.col+a.colSpan>=b.cols||direction==="down"&&a.row+a.rowSpan>=b.rows){notify("這個方向沒有可合併的儲存格");return}const other=cellRegion(b,targetIndex),compatible=direction==="right"?other.row===a.row&&other.rowSpan===a.rowSpan&&other.col===a.col+a.colSpan:other.col===a.col&&other.colSpan===a.colSpan&&other.row===a.row+a.rowSpan;if(!compatible){notify("只能合併邊界一致的相鄰儲存格");return}checkpoint();const first=a.row*b.cols+a.col,second=other.row*b.cols+other.col;if(String(b.cells[second]||"").trim())b.cells[first]=[b.cells[first],b.cells[second]].filter(Boolean).join("\n");if(!b.cellImages[first]&&b.cellImages[second])b.cellImages[first]=b.cellImages[second];b.cells[second]="";b.cellImages[second]=null;b.merges=tableMerges(b).filter(m=>m!==a&&m!==other);b.merges.push({row:a.row,col:a.col,rowSpan:direction==="down"?a.rowSpan+other.rowSpan:a.rowSpan,colSpan:direction==="right"?a.colSpan+other.colSpan:a.colSpan});state.activeCell={blockId:b.id,index:first};render();notify("儲存格已合併")}
  function splitCell(){const active=activeTableCell();if(!active)return;const{b,index}=active,region=cellRegion(b,index);if(region.rowSpan===1&&region.colSpan===1){notify("這個儲存格沒有合併");return}checkpoint();b.merges=tableMerges(b).filter(m=>m!==region);state.activeCell={blockId:b.id,index:region.row*b.cols+region.col};render();notify("儲存格已拆分")}
  function pageTables(){return state.blocks.filter(b=>b.type==="table"&&(b.page||0)===state.currentPage)}
  function batchPhotoTarget(){const tables=pageTables(),marked=tables.find(b=>b.photoTarget);return marked||tables.sort((a,b)=>b.w*b.h-a.w*a.h)[0]||null}
  function photoTableSlots(target){const weights=tableWeights(target.rowHeights,target.rows),total=weights.reduce((sum,value)=>sum+value,0)||1,rowHeights=weights.map(value=>target.h*value/total),largest=Math.max(...rowHeights,1),hasNarrowRows=rowHeights.some(value=>value<largest*.55);return target.cells.map((_,index)=>index).filter(index=>{if(cellIsHidden(target,index))return false;const region=cellRegion(target,index),height=rowHeights.slice(region.row,region.row+region.rowSpan).reduce((sum,value)=>sum+value,0);return !hasNarrowRows||height>=largest*.55})}
  function markPhotoTable(){const b=selected();if(b?.type!=="table")return;checkpoint();const enable=!b.photoTarget;pageTables().forEach(table=>table.photoTarget=false);b.photoTarget=enable;render();notify(enable?"已設為模板照片表格，只會填入大格":"已取消照片表格設定")}
  function clearBatchPreview(){state.batchPreviewUrls.forEach(url=>URL.revokeObjectURL(url));state.batchPreviewUrls=[];$("batch-photo-preview").innerHTML=""}
  function renderBatchPreview(){clearBatchPreview();const preview=$("batch-photo-preview"),files=state.batchFiles;$("batch-photo-summary").textContent=files.length?`已選擇 ${files.length} 張照片 · 將依左到右、上到下排列`:"尚未選擇照片";$("place-batch-photo").disabled=!files.length;files.slice(0,25).forEach((file,index)=>{const item=document.createElement("div"),image=document.createElement("img"),label=document.createElement("span"),url=URL.createObjectURL(file);state.batchPreviewUrls.push(url);item.className="batch-preview-item";image.src=url;image.alt=file.name||`照片 ${index+1}`;label.textContent=String(index+1);item.append(image,label);preview.append(item)});if(files.length>25){const more=document.createElement("div");more.className="batch-preview-item";more.textContent=`＋${files.length-25}`;preview.append(more)}}
  function openBatchPhoto(){const target=batchPhotoTarget();if(!target){notify("目前頁面沒有表格，請先插入模板表格");return}const slots=photoTableSlots(target);if(!slots.length){notify("這張表格沒有可放照片的大格");return}state.batchTargetId=target.id;state.batchFiles=[];$("batch-photo-file").value="";$("batch-target-name").textContent=`${target.photoTarget?"模板照片表格":"自動找到最大表格"} · ${slots.length} 個大格`;renderBatchPreview();$("batch-photo-modal").hidden=false}
  function closeBatchPhoto(){$("batch-photo-modal").hidden=true;state.batchFiles=[];state.batchTargetId=null;clearBatchPreview();$("batch-photo-file").value="";$("place-batch-photo").textContent="放入大格";$("place-batch-photo").disabled=true}
  async function placeBatchPhotos(){const target=state.blocks.find(b=>b.id===state.batchTargetId&&b.type==="table"),files=state.batchFiles.slice();if(!target||!files.length)return;const button=$("place-batch-photo"),slots=photoTableSlots(target);if(!slots.length){closeBatchPhoto();notify("這張表格沒有可放照片的大格");return}button.disabled=true;checkpoint();pageTables().forEach(table=>table.photoTarget=false);target.photoTarget=true;if(!Array.isArray(target.cellImages))target.cellImages=[];while(target.cellImages.length<target.rows*target.cols)target.cellImages.push(null);const images=[],skipped=[];for(let index=0;index<files.length;index++){button.textContent=`處理中 ${index+1} / ${files.length}`;try{images.push(await normalizeImageFile(files[index],{maxPixels:files.length>20?600:800,quality:.76,photoMode:true}))}catch(error){console.warn("略過無法讀取的照片",files[index]?.name,error);skipped.push(files[index])}}slots.forEach(index=>{target.cellImages[index]=null});images.slice(0,slots.length).forEach((image,index)=>{target.cellImages[slots[index]]=image});state.selectedId=target.id;state.activeCell={blockId:target.id,index:slots[0]??0};const overflow=Math.max(0,images.length-slots.length);closeBatchPhoto();render();const notes=[`已放入 ${Math.min(images.length,slots.length)} 張完整照片，大格以外未更動`];if(overflow)notes.push(`${overflow} 張超過大格數量`);if(skipped.length)notes.push(`${skipped.length} 張無法讀取`);notify(notes.join(" · "))}
  function duplicate(){ const b=selected();if(!b)return;checkpoint();const copy={...clone(b),id:uid(),page:state.currentPage,x:clamp(b.x+GRID,0,PAGE_W-b.w),y:clamp(b.y+GRID,0,PAGE_H-b.h),locked:false};state.blocks.push(copy);state.selectedId=copy.id;render() }
  function remove(){ if(!selected())return;checkpoint();state.blocks=state.blocks.filter(b=>b.id!==state.selectedId);state.selectedId="";render() }
  function copyBlock(){const b=selected();if(!b)return;state.clipboard=clone(b);notify("文字框已複製");renderRibbon()}
  function cutBlock(){const b=selected();if(!b)return;state.clipboard=clone(b);remove();notify("文字框已剪下")}
  function pasteBlock(){if(!state.clipboard)return;checkpoint();const b={...clone(state.clipboard),id:uid(),page:state.currentPage,x:clamp((state.clipboard.x||0)+GRID,0,PAGE_W-state.clipboard.w),y:clamp((state.clipboard.y||0)+GRID,0,PAGE_H-state.clipboard.h),locked:false};state.blocks.push(b);state.selectedId=b.id;render();notify("物件已貼上")}
  function toggleList(type){const b=selected();if(!b)return;if(b.type==="table"){notify("表格請在各儲存格直接輸入內容");return}checkpoint();const lines=b.text.split("\n"),bullet=/^•\s+/,number=/^\d+[.)]\s+/;const matcher=type==="bullet"?bullet:number,all=lines.filter(Boolean).every(line=>matcher.test(line));let count=1;b.text=lines.map(line=>{if(!line)return line;if(all)return line.replace(matcher,"");const clean=line.replace(bullet,"").replace(number,"");return type==="bullet"?`• ${clean}`:`${count++}. ${clean}`}).join("\n");render()}
  function startDrag(e,b,type){ if(b.locked)return;e.preventDefault();e.stopPropagation();checkpoint();state.drag={id:b.id,type,startX:e.clientX,startY:e.clientY,block:clone(b)};e.currentTarget.setPointerCapture(e.pointerId) }
  function startTableDivider(e,b,axis,index){if(b.locked)return;e.preventDefault();e.stopPropagation();checkpoint();const weights=axis==="column"?tableWeights(b.colWidths,b.cols):tableWeights(b.rowHeights,b.rows);state.drag={id:b.id,type:"table-divider",axis,index,startX:e.clientX,startY:e.clientY,block:clone(b),weights};e.currentTarget.setPointerCapture(e.pointerId)}
  window.addEventListener("pointermove",e=>{const d=state.drag;if(!d)return;const b=state.blocks.find(x=>x.id===d.id);if(!b)return;const dx=(e.clientX-d.startX)/state.zoom,dy=(e.clientY-d.startY)/state.zoom;if(d.type==="table-divider"){const weights=d.weights.slice(),total=weights.reduce((sum,value)=>sum+value,0)||1,size=d.axis==="column"?d.block.w:d.block.h,delta=(d.axis==="column"?dx:dy)*total/size,index=d.index,pair=weights[index]+weights[index+1],minimum=Math.min(pair*.45,Math.max(pair*.08,24*total/size)),first=clamp(d.weights[index]+delta,minimum,pair-minimum);weights[index]=first;weights[index+1]=pair-first;if(d.axis==="column")b.colWidths=weights;else b.rowHeights=weights;updateTableGeometry(b);return}if(d.type==="move"){b.x=clamp(snap(d.block.x+dx),0,PAGE_W-d.block.w);b.y=clamp(snap(d.block.y+dy),0,PAGE_H-d.block.h)}else{b.w=clamp(snap(d.block.w+dx),80,PAGE_W-d.block.x);b.h=clamp(snap(d.block.h+dy),b.type==="table"?b.rows*28:40,PAGE_H-d.block.y)}render()});
  window.addEventListener("pointerup",()=>{const drag=state.drag;state.drag=null;if(drag?.type==="table-divider"){render();notify(drag.axis==="column"?"欄寬已調整":"列高已調整")}});

  $("add-text").onclick=addText; $("add-cell").onclick=addTable;$("add-image").onclick=()=>$("image-file").click();$("image-file").onchange=e=>{if(e.target.files[0])addImageFile(e.target.files[0]);e.target.value=""};$("open-batch-photo").onclick=openBatchPhoto;$("close-batch-photo").onclick=closeBatchPhoto;$("cancel-batch-photo").onclick=closeBatchPhoto;$("batch-photo-modal").onclick=e=>{if(e.target===$("batch-photo-modal"))closeBatchPhoto()};$("batch-photo-file").onchange=e=>{state.batchFiles=[...e.target.files].filter(file=>file.type.startsWith("image/"));renderBatchPreview()};$("place-batch-photo").onclick=placeBatchPhotos;$("mark-photo-table").onclick=markPhotoTable;$("apply-table-size").onclick=()=>resizeTable($("selected-table-rows").value,$("selected-table-cols").value);$("add-table-row").onclick=()=>insertTableAxis("row");$("add-table-col").onclick=()=>insertTableAxis("col");$("delete-table-row").onclick=()=>deleteTableAxis("row");$("delete-table-col").onclick=()=>deleteTableAxis("col");$("merge-cell-right").onclick=()=>mergeCell("right");$("merge-cell-down").onclick=()=>mergeCell("down");$("split-cell").onclick=splitCell; $("duplicate").onclick=duplicate; $("delete").onclick=remove;
  $("undo").onclick=()=>{if(!state.history.length)return;state.future.unshift(clone(state.blocks));state.blocks=state.history.pop();state.selectedId=state.blocks[0]?.id||"";render();updateUndo()};
  $("redo").onclick=()=>{if(!state.future.length)return;state.history.push(clone(state.blocks));state.blocks=state.future.shift();state.selectedId=state.blocks[0]?.id||"";render();updateUndo()};
  $("toggle-grid").onclick=()=>{state.grid=!state.grid;$("page").classList.toggle("show-grid",state.grid);$("toggle-grid").querySelector("i").classList.toggle("active",state.grid)};
  $("toggle-snap").onclick=()=>{state.snap=!state.snap;$("toggle-snap").querySelector("i").classList.toggle("active",state.snap);$("snap-status").textContent=state.snap?"吸附中":"自由移動"};
  $("toggle-orientation").onclick=toggleOrientation;
  $("add-page").onclick=addPage;$("duplicate-page").onclick=duplicatePage;$("delete-page").onclick=deletePage;$("previous-page").onclick=()=>goToPage(state.currentPage-1);$("next-page").onclick=()=>goToPage(state.currentPage+1);
  $("zoom-out").onclick=()=>{state.zoom=clamp(state.zoom-.08,.38,1.2);updateZoom()}; $("zoom-in").onclick=()=>{state.zoom=clamp(state.zoom+.08,.38,1.2);updateZoom()};
  $("mobile-tools").onclick=e=>{e.stopPropagation();$("sidebar").classList.toggle("open")}; $("page").addEventListener("pointerdown",e=>{if(e.target===$("page")||e.target.classList.contains("safe-area")){state.selectedId="";render()}});
  $("doc-title").oninput=save;$("header-text").oninput=e=>{state.headerText=e.target.value;render()};$("footer-text").oninput=e=>{state.footerText=e.target.value;render()};$("show-page-number").onchange=e=>{state.showPageNumber=e.target.checked;render()};$("page-number-align").onchange=e=>{state.pageNumberAlign=e.target.value;render()}; $("export-toggle").onclick=e=>{e.stopPropagation();$("export-menu").hidden=!$("export-menu").hidden}; document.addEventListener("click",()=>$("export-menu").hidden=true);
  $("font-family").onchange=e=>update({fontFamily:e.target.value}); $("font-size").onchange=e=>update({fontSize:clamp(+e.target.value,8,72)}); $("line-height").onchange=e=>update({lineHeight:clamp(+e.target.value,1,2.5)}); $("color").oninput=e=>update({color:e.target.value});
  $("bold").onclick=()=>update({bold:!selected().bold}); $("italic").onclick=()=>update({italic:!selected().italic}); $("lock").onclick=()=>update({locked:!selected().locked}); document.querySelectorAll("[data-align]").forEach(btn=>btn.onclick=()=>update({align:btn.dataset.align}));
  $("image-fit").onchange=e=>update({fit:e.target.value});$("image-position-x").onchange=e=>update({positionX:+e.target.value});$("image-position-y").onchange=e=>update({positionY:+e.target.value});$("image-wrap").onchange=e=>update({wrap:e.target.value});
  [["pos-x","x",()=>0,()=>PAGE_W-selected().w],["pos-y","y",()=>0,()=>PAGE_H-selected().h],["width","w",()=>80,()=>PAGE_W-selected().x],["height","h",()=>selected().type==="table"?selected().rows*28:40,()=>PAGE_H-selected().y]].forEach(([id,key,min,max])=>$(id).onchange=e=>update({[key]:clamp(+e.target.value,min(),max())}));
  $("new-document").onclick=newDocument;$("save-now").onclick=saveNow;$("save-project").onclick=saveProject;$("open-project").onclick=()=>$("project-file").click();$("project-file").onchange=e=>{if(e.target.files[0])openProjectFile(e.target.files[0]);e.target.value=""};
  $("cut-block").onclick=cutBlock;$("copy-block").onclick=copyBlock;$("paste-block").onclick=pasteBlock;
  $("ribbon-font").onchange=e=>update({fontFamily:e.target.value});$("ribbon-size").onchange=e=>update({fontSize:clamp(+e.target.value,8,72)});$("font-smaller").onclick=()=>update({fontSize:clamp(selected().fontSize-1,8,72)});$("font-larger").onclick=()=>update({fontSize:clamp(selected().fontSize+1,8,72)});$("ribbon-bold").onclick=()=>update({bold:!selected().bold});$("ribbon-italic").onclick=()=>update({italic:!selected().italic});$("ribbon-underline").onclick=()=>update({underline:!selected().underline});$("ribbon-strike").onclick=()=>update({strike:!selected().strike});$("ribbon-color").oninput=e=>update({color:e.target.value});$("ribbon-highlight").oninput=e=>update({highlight:e.target.value});
  $("bullet-list").onclick=()=>toggleList("bullet");$("number-list").onclick=()=>toggleList("number");$("outdent").onclick=()=>update({indent:clamp((selected().indent||0)-16,0,96)});$("indent").onclick=()=>update({indent:clamp((selected().indent||0)+16,0,96)});document.querySelectorAll("[data-ribbon-align]").forEach(btn=>btn.onclick=()=>update({align:btn.dataset.ribbonAlign}));$("ribbon-line-height").onchange=e=>update({lineHeight:+e.target.value});
  $("open-find").onclick=()=>{$("find-panel").hidden=false;$('find-text').focus()};$("close-find").onclick=()=>$("find-panel").hidden=true;$("find-next").onclick=findNext;$("replace-all").onclick=replaceAll;$("find-text").addEventListener("keydown",e=>{if(e.key==="Enter")findNext()});
  document.addEventListener("keydown",e=>{const key=e.key.toLowerCase(),command=e.ctrlKey||e.metaKey,typing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(e.key==="Escape"&&!$("batch-photo-modal").hidden){closeBatchPhoto();return}if(command&&key==="s"){e.preventDefault();saveNow();return}if(command&&key==="f"){e.preventDefault();$("open-find").click();return}if(command&&key==="z"){e.preventDefault();e.shiftKey?$("redo").click():$("undo").click();return}if(command&&selected()&&["b","i","u"].includes(key)){e.preventDefault();$(key==="b"?"ribbon-bold":key==="i"?"ribbon-italic":"ribbon-underline").click();return}if(typing)return;if((e.key==="Delete"||e.key==="Backspace")&&selected()){e.preventDefault();remove()}if(command&&key==="d"){e.preventDefault();duplicate()}if(command&&key==="c"){e.preventDefault();copyBlock()}if(command&&key==="x"){e.preventDefault();cutBlock()}if(command&&key==="v"&&state.clipboard){e.preventDefault();pasteBlock()}});

  function notify(message){$("toast").querySelector("b").textContent=message;$("toast").hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$("toast").hidden=true,2400)}
  function saveTemplateStore(){try{localStorage.setItem("paper-grid-templates-v4",JSON.stringify(state.templates.filter(t=>!t.builtIn)))}catch(error){console.error(error);notify("模板圖片過大，無法儲存")}}
  function renderTemplates(){
    const list=$("template-list");list.innerHTML="";$("template-count").textContent=state.templates.length;$("template-empty").hidden=state.templates.length>0;
    state.templates.forEach(template=>{
      const card=document.createElement("article");card.className="template-card";
      const thumb=document.createElement("div");thumb.className="template-thumb";
      const previewW=template.orientation==="landscape"?1123:794,previewH=template.orientation==="landscape"?794:1123;template.blocks.filter(b=>(b.page||0)===0).forEach(b=>{const item=document.createElement("div");item.className="template-preview-item";item.textContent=b.type==="table"||b.type==="image"?"":b.text;Object.assign(item.style,{left:`${b.x/previewW*82}px`,top:`${b.y/previewH*116}px`,width:`${b.w/previewW*82}px`,height:`${b.h/previewH*116}px`,color:b.color,fontWeight:b.bold?"700":"400",textAlign:b.align,border:b.border||b.type==="table"?"1px solid #9aa8ab":"0"});if(b.type==="table"){item.style.backgroundImage="linear-gradient(#9aa8ab 1px,transparent 1px),linear-gradient(90deg,#9aa8ab 1px,transparent 1px)";item.style.backgroundSize=`100% ${100/b.rows}%,${100/b.cols}% 100%`}if(b.type==="image"){item.style.backgroundImage=`url("${b.src}")`;item.style.backgroundSize=b.fit==="cover"?"cover":"contain";item.style.backgroundPosition="center";item.style.backgroundRepeat="no-repeat"}thumb.append(item)});
      const info=document.createElement("div");info.className="template-info";const title=document.createElement("h3");title.textContent=template.name;const meta=document.createElement("p");meta.textContent=`${template.blocks.length} 個物件 · ${template.pageCount||1} 頁 · ${template.orientation==="landscape"?"橫向":"直向"}${template.builtIn?" · 官方版型":""}`;const time=document.createElement("time");time.textContent=template.createdAt;const actions=document.createElement("div");actions.className="template-actions";const use=document.createElement("button");use.className="use-template";use.textContent="建立副本";use.onclick=()=>useTemplate(template.id);actions.append(use);
      if(!template.builtIn){const edit=document.createElement("button");edit.className="edit-template";edit.textContent="編輯";edit.onclick=()=>editTemplate(template.id);actions.append(edit);const del=document.createElement("button");del.className="delete-template";del.title="刪除模板";del.textContent="×";del.onclick=()=>{if(confirm(`確定刪除「${template.name}」模板嗎？`)){state.templates=state.templates.filter(t=>t.id!==template.id);if(state.editingTemplateId===template.id){state.editingTemplateId=null;updateEditingUI()}saveTemplateStore();renderTemplates();notify("模板已刪除")}};actions.append(del)}
      info.append(title,meta,time,actions);card.append(thumb,info);list.append(card);
    });
  }
  function openTemplates(){renderTemplates();$("template-panel").hidden=false;$("template-scrim").hidden=false;$("sidebar").classList.remove("open")}
  function closeTemplates(){$("template-panel").hidden=true;$("template-scrim").hidden=true}
  function saveAsTemplate(){const field=$("template-name"),name=field.value.trim()||`${$("doc-title").value.trim()||"未命名文件"} 模板`;state.templates.push({id:uid(),name,blocks:clone(state.blocks),orientation:state.orientation,pageCount:state.pageCount,headerText:state.headerText,footerText:state.footerText,showPageNumber:state.showPageNumber,pageNumberAlign:state.pageNumberAlign,createdAt:new Date().toLocaleDateString("zh-TW"),builtIn:false});saveTemplateStore();field.value="";renderTemplates();notify(`已儲存模板「${name}」`)}
  function updateEditingUI(){const editing=!!state.editingTemplateId;$("save-template-changes").hidden=!editing;$("save-status").textContent=editing?"正在編輯模板":"已自動儲存";document.body.classList.toggle("editing-template",editing)}
  function applyTemplateMeta(template){state.pageCount=Math.max(1,+template.pageCount||1);state.currentPage=0;state.headerText=template.headerText||"";state.footerText=template.footerText||"";state.showPageNumber=template.showPageNumber!==false;state.pageNumberAlign=template.pageNumberAlign||"right";$("header-text").value=state.headerText;$("footer-text").value=state.footerText;$("show-page-number").checked=state.showPageNumber;$("page-number-align").value=state.pageNumberAlign}
  function useTemplate(id){const template=state.templates.find(t=>t.id===id);if(!template)return;checkpoint();state.editingTemplateId=null;setOrientation(template.orientation==="landscape"?"landscape":"portrait");applyTemplateMeta(template);state.blocks=clone(template.blocks).map((b,index)=>({...b,id:`${uid()}-${index}`,page:b.page||0}));state.selectedId=state.blocks.find(b=>(b.page||0)===0)?.id||"";$("doc-title").value=`${template.name} - 副本`;updateEditingUI();closeTemplates();render();save();notify("已建立可編輯的模板副本")}
  function editTemplate(id){const template=state.templates.find(t=>t.id===id&&!t.builtIn);if(!template)return;checkpoint();state.editingTemplateId=id;setOrientation(template.orientation==="landscape"?"landscape":"portrait");applyTemplateMeta(template);state.blocks=clone(template.blocks).map((b,index)=>({...b,id:`${uid()}-${index}`,page:b.page||0}));state.selectedId=state.blocks.find(b=>(b.page||0)===0)?.id||"";$("doc-title").value=template.name;updateEditingUI();closeTemplates();render();save();notify("正在編輯模板，完成後請儲存變更")}
  function saveTemplateChanges(){const template=state.templates.find(t=>t.id===state.editingTemplateId);if(!template)return;const name=$("doc-title").value.trim()||template.name;Object.assign(template,{name,blocks:clone(state.blocks),orientation:state.orientation,pageCount:state.pageCount,headerText:state.headerText,footerText:state.footerText,showPageNumber:state.showPageNumber,pageNumberAlign:state.pageNumberAlign,createdAt:`更新於 ${new Date().toLocaleDateString("zh-TW")}`});state.editingTemplateId=null;saveTemplateStore();updateEditingUI();renderTemplates();save();notify(`模板「${name}」已更新`)}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
  function exportWord(){try{const title=$("doc-title").value||"A4文件",bytes=window.PaperGridDocx.buildDocx(state.blocks,title,{width:PAGE_W,height:PAGE_H,pageCount:state.pageCount,headerText:state.headerText,footerText:state.footerText,showPageNumber:state.showPageNumber,pageNumberAlign:state.pageNumberAlign});download(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),`${title}.docx`);notify(`Word DOCX 已匯出（${state.pageCount} 頁）`)}catch(error){console.error(error);notify("Word 匯出失敗")}}
  function wrapText(ctx,text,maxWidth){const lines=[];text.split("\n").forEach(paragraph=>{if(paragraph===""){lines.push("");return}let line="";for(const char of paragraph){const test=line+char;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=char}else line=test}lines.push(line)});return lines}
  function drawCanvasText(ctx,b,text,rx,ry,rw,rh,scale){ctx.save();ctx.beginPath();ctx.rect(rx*scale,ry*scale,rw*scale,rh*scale);ctx.clip();if(b.highlight){ctx.fillStyle=b.highlight;ctx.fillRect(rx*scale,ry*scale,rw*scale,rh*scale)}ctx.fillStyle=b.color;ctx.font=`${b.italic?"italic ":""}${b.bold?"700":"400"} ${b.fontSize*scale}px "${b.fontFamily}",sans-serif`;ctx.textBaseline="top";ctx.textAlign=b.align==="justify"?"left":b.align;const pad=(b.type==="table"?5:8)*scale,indent=(b.indent||0)*scale,x=b.align==="center"?(rx+rw/2)*scale:b.align==="right"?(rx+rw)*scale-pad:rx*scale+pad+indent,y=ry*scale+pad,max=rw*scale-pad*2-indent,lineH=b.fontSize*b.lineHeight*scale;wrapText(ctx,String(text||""),max).forEach((line,i)=>{const lineY=y+i*lineH;ctx.fillText(line,x,lineY,max);if(b.underline||b.strike){const width=Math.min(ctx.measureText(line).width,max),start=b.align==="center"?x-width/2:b.align==="right"?x-width:x;ctx.beginPath();ctx.lineWidth=Math.max(1,scale);if(b.underline){ctx.moveTo(start,lineY+b.fontSize*scale*1.05);ctx.lineTo(start+width,lineY+b.fontSize*scale*1.05)}if(b.strike){ctx.moveTo(start,lineY+b.fontSize*scale*.55);ctx.lineTo(start+width,lineY+b.fontSize*scale*.55)}ctx.strokeStyle=b.color;ctx.stroke()}});ctx.restore()}
  function drawImageInBox(ctx,image,rx,ry,rw,rh,scale,padding=0,fit="contain",positionX=50,positionY=50){const boxW=Math.max(1,rw-padding*2),boxH=Math.max(1,rh-padding*2),ratio=fit==="cover"?Math.max(boxW/image.naturalWidth,boxH/image.naturalHeight):Math.min(boxW/image.naturalWidth,boxH/image.naturalHeight),dw=image.naturalWidth*ratio,dh=image.naturalHeight*ratio,dx=rx+padding+(boxW-dw)*(positionX/100),dy=ry+padding+(boxH-dh)*(positionY/100);ctx.save();ctx.beginPath();ctx.rect((rx+padding)*scale,(ry+padding)*scale,boxW*scale,boxH*scale);ctx.clip();ctx.drawImage(image,dx*scale,dy*scale,dw*scale,dh*scale);ctx.restore()}
  function drawPageDecorations(ctx,pageIndex,scale){ctx.save();ctx.fillStyle="#6f7d83";ctx.strokeStyle="#dbe2e3";ctx.lineWidth=scale;ctx.font=`${10*scale}px "Noto Sans TC",sans-serif`;ctx.textBaseline="middle";if(state.headerText){ctx.fillText(state.headerText,56*scale,32*scale);ctx.beginPath();ctx.moveTo(56*scale,45*scale);ctx.lineTo((PAGE_W-56)*scale,45*scale);ctx.stroke()}if(state.footerText||state.showPageNumber){const y=(PAGE_H-30)*scale;ctx.beginPath();ctx.moveTo(56*scale,(PAGE_H-43)*scale);ctx.lineTo((PAGE_W-56)*scale,(PAGE_H-43)*scale);ctx.stroke();if(state.footerText)ctx.fillText(state.footerText,56*scale,y);if(state.showPageNumber){ctx.textAlign=state.pageNumberAlign;const x=state.pageNumberAlign==="left"?56:state.pageNumberAlign==="center"?PAGE_W/2:PAGE_W-56;ctx.fillText(String(pageIndex+1),x*scale,y)}}ctx.restore()}
  async function renderCanvas(pageIndex){const scale=2,canvas=document.createElement("canvas");canvas.width=PAGE_W*scale;canvas.height=PAGE_H*scale;const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);drawPageDecorations(ctx,pageIndex,scale);const blocks=state.blocks.filter(b=>(b.page||0)===pageIndex).sort((a,b)=>(a.type==="image"&&a.wrap==="behind"?-1:0)-(b.type==="image"&&b.wrap==="behind"?-1:0));for(const b of blocks){if(b.type==="image"){const image=await imageElement(b.src);drawImageInBox(ctx,image,b.x,b.y,b.w,b.h,scale,0,b.fit||"contain",b.positionX??50,b.positionY??50);continue}if(b.type==="table"){const columns=tableTracks(tableWeights(b.colWidths,b.cols),b.w),rows=tableTracks(tableWeights(b.rowHeights,b.rows),b.h);for(let index=0;index<(b.cells||[]).length;index++){if(cellIsHidden(b,index))continue;const region=cellRegion(b,index),rx=b.x+columns.offsets[region.col],ry=b.y+rows.offsets[region.row],rw=columns.offsets[region.col+region.colSpan]-columns.offsets[region.col],rh=rows.offsets[region.row+region.rowSpan]-rows.offsets[region.row],cellImage=b.cellImages?.[index];if(cellImage){const image=await imageElement(cellImage.src);drawImageInBox(ctx,image,rx,ry,rw,rh,scale,4)}drawCanvasText(ctx,b,b.cells[index],rx,ry,rw,rh,scale);ctx.save();ctx.strokeStyle="#7f9095";ctx.lineWidth=1.2*scale;ctx.strokeRect(rx*scale,ry*scale,rw*scale,rh*scale);ctx.restore()}}else{drawCanvasText(ctx,b,b.text,b.x,b.y,b.w,b.h,scale);if(b.border){ctx.save();ctx.strokeStyle="#9aa8ab";ctx.lineWidth=1.5*scale;ctx.strokeRect(b.x*scale+.75*scale,b.y*scale+.75*scale,b.w*scale-1.5*scale,b.h*scale-1.5*scale);ctx.restore()}}}return canvas}
  function makePdf(dataUrls){const images=dataUrls.map(dataUrl=>{const binary=atob(dataUrl.split(",")[1]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}),pagePtW=state.orientation==="landscape"?841.89:595.28,pagePtH=state.orientation==="landscape"?595.28:841.89,enc=new TextEncoder(),chunks=[],offsets=[0];let offset=0;const push=x=>{const bytes=typeof x==="string"?enc.encode(x):x;chunks.push(bytes);offset+=bytes.length},obj=(id,body)=>{offsets[id]=offset;push(`${id} 0 obj\n`);typeof body==="function"?body():push(body);push("\nendobj\n")};push("%PDF-1.4\n");obj(1,"<< /Type /Catalog /Pages 2 0 R >>");const pageIds=images.map((_,i)=>3+i*3);obj(2,`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${images.length} >>`);images.forEach((image,i)=>{const pageId=3+i*3,imageId=pageId+1,contentId=pageId+2,name=`Im${i}`;obj(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pagePtW} ${pagePtH}] /Resources << /XObject << /${name} ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);obj(imageId,()=>{push(`<< /Type /XObject /Subtype /Image /Width ${PAGE_W*2} /Height ${PAGE_H*2} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`);push(image);push("\nendstream")});const content=`q\n${pagePtW} 0 0 ${pagePtH} 0 0 cm\n/${name} Do\nQ`;obj(contentId,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`)});const size=3+images.length*3,xref=offset;push(`xref\n0 ${size}\n0000000000 65535 f \n`);for(let i=1;i<size;i++)push(`${String(offsets[i]).padStart(10,"0")} 00000 n \n`);push(`trailer\n<< /Size ${size} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const out=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let pos=0;chunks.forEach(c=>{out.set(c,pos);pos+=c.length});return new Blob([out],{type:"application/pdf"})}
  async function exportPdf(){try{const title=$("doc-title").value||"A4文件",jpegs=[];for(let page=0;page<state.pageCount;page++)jpegs.push((await renderCanvas(page)).toDataURL("image/jpeg",.96));download(makePdf(jpegs),`${title}.pdf`);notify(`PDF 已匯出（${state.pageCount} 頁）`)}catch(error){console.error(error);notify("PDF 匯出失敗")}}
  $("export-word").onclick=e=>{e.stopPropagation();exportWord();$("export-menu").hidden=true}; $("export-pdf").onclick=e=>{e.stopPropagation();exportPdf();$("export-menu").hidden=true};
  $("open-templates").onclick=openTemplates;$("mobile-templates").onclick=e=>{e.stopPropagation();openTemplates()};$("close-templates").onclick=closeTemplates;$("template-scrim").onclick=closeTemplates;$("save-template").onclick=saveAsTemplate;$("template-name").addEventListener("keydown",e=>{if(e.key==="Enter")saveAsTemplate()});$("save-template-changes").onclick=saveTemplateChanges;
  updateZoom(); updateUndo();updateEditingUI(); render();renderTemplates();
})();
