(function(root,factory){
  const api=factory(typeof module!=="undefined"&&module.exports?require("./domain/finance-domain.js"):root.FinanceDomain);
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
  root.FinanceUiModel=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(Domain){
  "use strict";
  const ERROR_MESSAGES=Object.freeze({
    INVALID_AMOUNT:"金額必須大於 0，且只能輸入整數。",INVALID_DATE:"請輸入有效日期。",SAME_TRANSFER_ACCOUNT:"轉出與轉入帳戶不可相同。",
    INVALID_ACCOUNT_REFERENCE:"找不到指定帳戶，請重新選擇。",INVALID_CATEGORY_REFERENCE:"找不到指定分類，請重新選擇。",INVALID_CREDIT_CARD_REFERENCE:"找不到指定信用卡，請重新選擇。",
    ARCHIVED_REFERENCE:"已封存的帳戶、信用卡或分類不可用於新交易。",DUPLICATE_ID:"資料識別值重複，請再試一次。",DATABASE_UNAVAILABLE:"此瀏覽器無法使用離線資料庫。",
    DATABASE_OPEN_FAILED:"無法開啟理財資料庫，請重新整理後再試。",DATABASE_BLOCKED:"其他分頁正在使用舊版資料庫，請關閉後再試。",
    NOT_FOUND:"找不到這筆資料，可能已在其他分頁變更。",VALIDATION_FAILED:"請檢查輸入內容。"
  });
  const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
  const localMonth=(date=new Date())=>localDate(date).slice(0,7);
  function monthRange(offset=0){const date=new Date();date.setDate(1);date.setMonth(date.getMonth()+offset);const start=localDate(date);date.setMonth(date.getMonth()+1);date.setDate(0);return {start,end:localDate(date)};}
  function recentMonths(count=6){const result=[];for(let offset=count-1;offset>=0;offset--){const date=new Date();date.setDate(1);date.setMonth(date.getMonth()-offset);result.push(localMonth(date));}return result;}
  function parsePositiveInteger(value,{allowZero=false}={}){const text=String(value??"").trim();if(!/^\d+$/.test(text))return null;const number=Number(text);return Number.isSafeInteger(number)&&(allowZero?number>=0:number>0)?number:null;}
  function validateAccountDraft(input){const errors={};if(typeof input.name!=="string"||!input.name.trim())errors.name="請輸入帳戶名稱。";if(!Domain.ACCOUNT_TYPES.includes(input.type))errors.type="請選擇有效的帳戶類型。";const initialBalance=parsePositiveInteger(input.initialBalance,{allowZero:true});if(initialBalance===null)errors.initialBalance="初始餘額必須是 0 或正整數。";if(input.last4&&!/^\d{4}$/.test(input.last4))errors.last4="請輸入 4 位數字，或留空。";return {valid:!Object.keys(errors).length,errors,value:{...input,name:input.name?.trim(),bankName:input.bankName?.trim()||"",last4:input.last4?.trim()||"",initialBalance,currency:"TWD",includeInAssets:input.includeInAssets===true}};}
  function validateCardDraft(input,references={}){const errors={},creditLimit=parsePositiveInteger(input.creditLimit??"0",{allowZero:true}),closingDay=parsePositiveInteger(input.closingDay),dueDay=parsePositiveInteger(input.dueDay);if(!input.name?.trim())errors.name="請輸入卡片名稱。";if(input.last4&&!/^\d{4}$/.test(input.last4))errors.last4="請輸入 4 位數字，或留空。";if(creditLimit===null)errors.creditLimit="信用額度必須是 0 或正整數。";if(closingDay===null||closingDay>31)errors.closingDay="結帳日必須是 1 到 31。";if(dueDay===null||dueDay>31)errors.dueDay="繳款日必須是 1 到 31。";if(input.linkedPaymentAccountId&&!references.accounts?.some(row=>row.id===input.linkedPaymentAccountId))errors.linkedPaymentAccountId="找不到付款帳戶。";return {valid:!Object.keys(errors).length,errors,value:{name:input.name?.trim(),bankName:input.bankName?.trim()||"",last4:input.last4?.trim()||"",creditLimit,closingDay,dueDay,linkedPaymentAccountId:input.linkedPaymentAccountId||""}};}
  function validateCategoryDraft(input){const errors={};if(!input.name?.trim())errors.name="請輸入分類名稱。";if(!Domain.CATEGORY_TYPES.includes(input.type))errors.type="請選擇收入或支出分類。";return {valid:!Object.keys(errors).length,errors,value:{name:input.name?.trim(),type:input.type,icon:input.icon?.trim().slice(0,2)||input.name?.trim().slice(0,1)||"類"}};}
  function transactionValue(input){const amount=parsePositiveInteger(input.amount),base={type:input.type,date:input.date,amount:amount??Number.NaN,note:input.note?.trim()||""};if(["income","expense"].includes(input.type))return {...base,categoryId:input.categoryId,accountId:input.accountId};if(input.type==="transfer")return {...base,fromAccountId:input.fromAccountId,toAccountId:input.toAccountId};if(input.type==="credit_card_purchase")return {...base,creditCardId:input.creditCardId,categoryId:input.categoryId};if(input.type==="credit_card_payment")return {...base,fromAccountId:input.fromAccountId||input.accountId,creditCardId:input.creditCardId};return base;}
  function validateTransactionDraft(input,references){const value=transactionValue(input),result=Domain.validateTransaction(value,references),errors={};for(const item of result.errors)errors[item.field||"form"]=ERROR_MESSAGES[item.code]||item.message;const category=references?.categories?.find?.(row=>row.id===value.categoryId),typedCategory=category&&Domain.CATEGORY_TYPES.includes(category.type);if(value.type==="income"&&typedCategory&&category.type!=="income")errors.categoryId="收入必須使用收入分類。";if(["expense","credit_card_purchase"].includes(value.type)&&typedCategory&&category.type!=="expense")errors.categoryId="支出必須使用支出分類。";return {valid:result.valid&&!Object.keys(errors).length,errors,value};}
  function sortTransactions(rows){return [...rows].sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt||"").localeCompare(String(a.createdAt||"")));}
  function transactionDateRange(preset,customStart="",customEnd=""){if(preset==="month")return monthRange(0);if(preset==="previous")return monthRange(-1);return {start:customStart||"",end:customEnd||""};}
  function filterTransactions(rows,filters={},lookups={}){const {start,end}=transactionDateRange(filters.period||"month",filters.start,filters.end),query=String(filters.query||"").trim().toLocaleLowerCase("zh-TW");return sortTransactions(rows).filter(row=>(!start||row.date>=start)&&(!end||row.date<=end)&&(!filters.type||row.type===filters.type)&&(!query||[row.note,lookups.categories?.get(row.categoryId)?.name,lookups.accounts?.get(row.accountId)?.name,lookups.accounts?.get(row.fromAccountId)?.name,lookups.accounts?.get(row.toAccountId)?.name,lookups.cards?.get(row.creditCardId)?.name].some(value=>String(value||"").toLocaleLowerCase("zh-TW").includes(query))));}
  function userError(error){if(ERROR_MESSAGES[error?.code])return ERROR_MESSAGES[error.code];return error?.name==="FinanceStorageError"?"無法儲存資料，請檢查後再試。":"發生未預期錯誤，請稍後再試。";}
  return Object.freeze({ERROR_MESSAGES,localDate,localMonth,monthRange,recentMonths,parsePositiveInteger,validateAccountDraft,validateCardDraft,validateCategoryDraft,validateTransactionDraft,sortTransactions,transactionDateRange,filterTransactions,userError});
});
