(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.EngineeringSupervisionFoundationModels=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
  class SupervisionFoundationError extends Error{constructor(code,message){super(message);this.name="SupervisionFoundationError";this.code=code;}}
  const text=(value,name,max=300,required=true)=>{const result=String(value??"").trim();if(required&&!result||result.length>max)throw new SupervisionFoundationError("SUPERVISION_FOUNDATION_INVALID",`${name} 無效。`);return result;};
  const stamp=(value,name,required=true)=>{const result=text(value,name,40,required);if(result&&!Number.isFinite(Date.parse(result)))throw new SupervisionFoundationError("SUPERVISION_FOUNDATION_INVALID",`${name} 無效。`);return result||null;};
  const metadata=value=>value&&typeof value==="object"&&!Array.isArray(value)?clone(value):{};
  const enumValue=(value,allowed,name)=>{const result=String(value||"");if(!allowed.includes(result))throw new SupervisionFoundationError("SUPERVISION_FOUNDATION_INVALID",`${name} 無效。`);return result;};
  const model=(fields,normalize)=>Object.freeze({FIELDS:Object.freeze(fields),create:input=>Object.freeze(normalize(input||{})),toRecord(value){const normalized=normalize(value||{});return Object.fromEntries(fields.map(field=>[field,clone(normalized[field])]));}});
  const common=input=>({id:text(input.id,"ID",180),project_id:text(input.project_id,"Project ID",180),created_at:stamp(input.created_at,"建立時間"),updated_at:stamp(input.updated_at,"更新時間"),metadata:metadata(input.metadata)});
  const Profile=model(["id","project_id","contract_no","contract_name","planned_start_at","planned_end_at","status","created_at","updated_at","metadata"],input=>{const value={...common(input),contract_no:text(input.contract_no,"契約編號",120,false)||null,contract_name:text(input.contract_name,"契約名稱",200),planned_start_at:stamp(input.planned_start_at,"預定開始日期",false),planned_end_at:stamp(input.planned_end_at,"預定完成日期",false),status:enumValue(input.status||"active",["active","archived"],"狀態")};if(value.planned_start_at&&value.planned_end_at&&value.planned_start_at>value.planned_end_at)throw new SupervisionFoundationError("SUPERVISION_PROFILE_DATE_RANGE_INVALID","預定完成日期不得早於開始日期。");return value;});
  const Party=model(["id","project_id","party_type","display_name","contact_ref","status","created_at","updated_at","metadata"],input=>({...common(input),party_type:enumValue(input.party_type,["owner","contractor","supervisor","other"],"參與單位類型"),display_name:text(input.display_name,"參與單位名稱",200),contact_ref:text(input.contact_ref,"聯絡參照",300,false)||null,status:enumValue(input.status||"active",["active","archived"],"狀態")}));
  const hierarchy=(input,kind)=>({...common(input),code:text(input.code,"編碼",80).toUpperCase(),name:text(input.name,"名稱",200),parent_id:text(input.parent_id,"上層 ID",180,false)||null,status:enumValue(input.status||"active",["active","archived"],"狀態"),sort_order:Number.isFinite(Number(input.sort_order))?Number(input.sort_order):0,...kind(input)});
  const WorkItem=model(["id","project_id","code","name","parent_id","unit","status","sort_order","created_at","updated_at","metadata"],input=>hierarchy(input,value=>({unit:text(value.unit,"單位",40,false)||null})));
  const SiteLocation=model(["id","project_id","code","name","parent_id","location_type","status","sort_order","created_at","updated_at","metadata"],input=>hierarchy(input,value=>({location_type:text(value.location_type,"位置類型",80,false)||null})));
  const Relation=model(["id","project_id","source_type","source_id","target_type","target_id","relation_type","status","created_at","updated_at","revoked_at","metadata"],input=>({...common(input),source_type:enumValue(input.source_type,["inspection","defect"],"來源類型"),source_id:text(input.source_id,"來源 ID",180),target_type:enumValue(input.target_type,["work_item","site_location","contract_party"],"目標類型"),target_id:text(input.target_id,"目標 ID",180),relation_type:enumValue(input.relation_type,["applies_to_work_item","located_at","responsible_party"],"關聯類型"),status:enumValue(input.status||"active",["active","revoked"],"狀態"),revoked_at:stamp(input.revoked_at,"撤銷時間",false)}));
  return Object.freeze({SupervisionFoundationError,Profile,Party,WorkItem,SiteLocation,Relation});
});
