(function(root,factory){const isNode=typeof module==="object"&&module.exports,api=factory(isNode?require("./checklists/site-inspection-checklist.js"):root.EngineeringSupervisionSiteChecklist,isNode?require("./inspections/inspection-model.js"):root.EngineeringSupervisionInspectionModel,isNode?require("./defects/defect-model.js"):root.EngineeringSupervisionDefectModel,isNode?require("./foundation-models.js"):root.EngineeringSupervisionFoundationModels,isNode?require("./inspections/inspection-workflow-models.js"):root.EngineeringSupervisionInspectionWorkflowModels);if(isNode)module.exports=api;else root.EngineeringSupervisionService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(Checklist,InspectionModel,DefectModel,Foundation,WorkflowModels){
  "use strict";class SupervisionServiceError extends Error{constructor(code,message,cause){super(message,{cause});this.name="SupervisionServiceError";this.code=code;}}
  function create({projectService,inspectionRepository,defectRepository,attachmentRepository,workflowService,profileRepository=null,partyRepository=null,workItemRepository=null,locationRepository=null,relationRepository=null,revisionRepository=null,inspectionReviewRepository=null,inspectionEventRepository=null,now=()=>new Date().toISOString(),idGenerator=()=>globalThis.crypto?.randomUUID?.()||`supervision-${Date.now()}-${Math.random().toString(16).slice(2)}`}={}){if(!projectService||!inspectionRepository||!defectRepository||!attachmentRepository||!workflowService)throw new TypeError("Supervision Service dependencies are required");
    async function project(projectId){const value=await projectService.getProject(String(projectId));if(!value.module_ids.includes("supervision"))throw new SupervisionServiceError("SUPERVISION_MODULE_DISABLED","此專案尚未啟用監造模組。");return value;}
    async function owned(repository,projectId,id,code){await project(projectId);const value=await repository.getById(String(id));if(!value||value.project_id!==String(projectId)||value.module_id!=="supervision")throw new SupervisionServiceError(code,"找不到此專案的監造資料。");return value;}
    async function attachments(projectId,ids=[]){for(const id of ids){const value=await attachmentRepository.getById(String(id));if(!value||value.project_id!==String(projectId))throw new SupervisionServiceError("SUPERVISION_ATTACHMENT_INVALID","附件不存在或屬於其他專案。");}}
    async function createInspection(projectId,data={}){await project(projectId);const results=Checklist.validate(data.checklist_results),snapshot=Checklist.snapshot(results),stamp=now();await attachments(projectId,[...(data.attachment_ids||[]),...results.flatMap(row=>row.attachment_ids)]);return inspectionRepository.create(InspectionModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",checklist_template_id:snapshot.template_id,checklist_template_version:snapshot.template_version,checklist_snapshot:snapshot,related_task_ids:[],status:data.status||"completed",created_at:stamp,updated_at:stamp}));}
    async function updateInspection(projectId,id,data={}){const current=await owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND");if(["pending_review","returned","reviewed","cancelled"].includes(current.status))throw new SupervisionServiceError("SUPERVISION_INSPECTION_EDIT_FORBIDDEN","此 Inspection 狀態不可直接修改，請使用正式審查流程。");const attachment_ids=data.attachment_ids??current.attachment_ids;await attachments(projectId,attachment_ids);return inspectionRepository.update(InspectionModel.create({...current,...data,id:current.id,project_id:current.project_id,module_id:"supervision",created_at:current.created_at,checklist_template_id:current.checklist_template_id,checklist_template_version:current.checklist_template_version,checklist_snapshot:current.checklist_snapshot,updated_at:now()}));}
    async function archiveInspection(projectId,id){const current=await owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND");if(!["reviewed","cancelled","completed"].includes(current.status))throw new SupervisionServiceError("SUPERVISION_INSPECTION_ARCHIVE_FORBIDDEN","僅可封存已審查、已取消或舊版完成資料。");return inspectionRepository.update(InspectionModel.create({...current,status:"archived",updated_at:now()}));}
    async function createDefect(projectId,data={}){await project(projectId);await owned(inspectionRepository,projectId,data.inspection_id,"SUPERVISION_INSPECTION_NOT_FOUND");await attachments(projectId,data.attachment_ids||[]);const stamp=now();return defectRepository.create(DefectModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",status:"open",related_task_id:null,created_at:stamp,updated_at:stamp,resolved_at:null}));}
    async function transitionDefect(projectId,id,target){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");return defectRepository.update(DefectModel.transition(current,String(target),now()));}
    async function createTaskForDefect(projectId,id,data,actorId){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");if(current.related_task_id)throw new SupervisionServiceError("SUPERVISION_TASK_ALREADY_LINKED","此缺失已關聯 Task。");const task=await workflowService.createTask(projectId,{...data,related_entity_type:"module_entity",related_entity_id:`supervision:defect:${current.id}`,metadata:{...(data?.metadata||{}),source_module:"supervision",source_entity:"defect"}},actorId);try{await defectRepository.update(DefectModel.create({...current,related_task_id:task.id,updated_at:now()}));}catch(error){throw new SupervisionServiceError("SUPERVISION_TASK_LINK_SAVE_FAILED","Task 已建立，但缺失反向連結保存失敗；Task 關聯仍可用於修復。",error);}return task;}
    const requireFoundation=(repository,name)=>{if(!repository)throw new SupervisionServiceError("SUPERVISION_FOUNDATION_UNAVAILABLE",`${name} 儲存服務尚未啟用。`);return repository;};
    async function foundationOwned(repository,projectId,id,code){await project(projectId);const value=await requireFoundation(repository,"監造主檔").getById(String(id));if(!value||value.project_id!==String(projectId))throw new SupervisionServiceError(code,"找不到此專案的監造主檔。");return value;}
    const audit=data=>({...data,metadata:{...(data?.metadata||{}),change_source:data?.metadata?.change_source||"manual-ui"}});
    async function getProfile(projectId){await project(projectId);if(!profileRepository)return null;return(await profileRepository.listByProject(String(projectId)))[0]||null;}
    async function saveProfile(projectId,data={}){await project(projectId);const stamp=now(),current=await getProfile(projectId),value=Foundation.Profile.create(audit({...current,...data,id:`supervision-profile:${projectId}`,project_id:String(projectId),status:data.status||current?.status||"active",created_at:current?.created_at||stamp,updated_at:stamp}));return current?profileRepository.update(value):requireFoundation(profileRepository,"工程資訊").create(value);}
    async function archiveProfile(projectId){const current=await getProfile(projectId);if(!current)throw new SupervisionServiceError("SUPERVISION_PROFILE_NOT_FOUND","找不到此專案的工程資訊。");return profileRepository.update(Foundation.Profile.create({...current,status:"archived",updated_at:now()}));}
    async function createParty(projectId,data={}){await project(projectId);const stamp=now();return requireFoundation(partyRepository,"參與單位").create(Foundation.Party.create(audit({...data,id:idGenerator(),project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp})));}
    async function updateParty(projectId,id,data={}){const current=await foundationOwned(partyRepository,projectId,id,"SUPERVISION_PARTY_NOT_FOUND");return partyRepository.update(Foundation.Party.create(audit({...current,...data,id:current.id,project_id:current.project_id,created_at:current.created_at,updated_at:now()})));}
    const archiveParty=(projectId,id)=>updateParty(projectId,id,{status:"archived"});
    async function validateHierarchy(repository,projectId,id,parentId){if(!parentId)return;if(String(id)===String(parentId))throw new SupervisionServiceError("SUPERVISION_HIERARCHY_CYCLE","項目不可成為自己的上層。");let cursor=await foundationOwned(repository,projectId,parentId,"SUPERVISION_PARENT_NOT_FOUND"),seen=new Set([String(id)]);while(cursor){if(seen.has(cursor.id))throw new SupervisionServiceError("SUPERVISION_HIERARCHY_CYCLE","階層不可形成循環。");seen.add(cursor.id);cursor=cursor.parent_id?await foundationOwned(repository,projectId,cursor.parent_id,"SUPERVISION_PARENT_NOT_FOUND"):null;}}
    async function createHierarchy(repository,model,projectId,data={}){await project(projectId);const stamp=now(),id=idGenerator();await validateHierarchy(repository,projectId,id,data.parent_id);return requireFoundation(repository,"階層主檔").create(model.create(audit({...data,id,project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp})));}
    async function updateHierarchy(repository,model,projectId,id,data={}){const current=await foundationOwned(repository,projectId,id,"SUPERVISION_HIERARCHY_NOT_FOUND"),next={...current,...data,id:current.id,project_id:current.project_id,created_at:current.created_at,updated_at:now()};await validateHierarchy(repository,projectId,id,next.parent_id);return repository.update(model.create(audit(next)));}
    const createWorkItem=(projectId,data)=>createHierarchy(workItemRepository,Foundation.WorkItem,projectId,data),updateWorkItem=(projectId,id,data)=>updateHierarchy(workItemRepository,Foundation.WorkItem,projectId,id,data),archiveWorkItem=(projectId,id)=>updateWorkItem(projectId,id,{status:"archived"});
    const createLocation=(projectId,data)=>createHierarchy(locationRepository,Foundation.SiteLocation,projectId,data),updateLocation=(projectId,id,data)=>updateHierarchy(locationRepository,Foundation.SiteLocation,projectId,id,data),archiveLocation=(projectId,id)=>updateLocation(projectId,id,{status:"archived"});
    const relationRule=Object.freeze({applies_to_work_item:["work_item"],located_at:["site_location"],responsible_party:["contract_party"]});
    async function relationEndpoint(projectId,type,id){const repositories={work_item:workItemRepository,site_location:locationRepository,contract_party:partyRepository};if(!repositories[type])throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","不支援的關聯端點。");return foundationOwned(repositories[type],projectId,id,"SUPERVISION_RELATION_TARGET_NOT_FOUND");}
    async function relationSource(projectId,type,id){const repositories={inspection:inspectionRepository,defect:defectRepository};if(!repositories[type])throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","不支援的來源類型。");return owned(repositories[type],projectId,id,"SUPERVISION_RELATION_SOURCE_NOT_FOUND");}
    async function addRelation(projectId,data={}){await project(projectId);if(!relationRule[data.relation_type]?.includes(data.target_type))throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","關聯類型與目標類型不相容。");await Promise.all([relationSource(projectId,data.source_type,data.source_id),relationEndpoint(projectId,data.target_type,data.target_id)]);const repository=requireFoundation(relationRepository,"監造關聯"),rows=await repository.listByProject(String(projectId)),same=rows.find(item=>item.source_type===data.source_type&&item.source_id===String(data.source_id)&&item.target_type===data.target_type&&item.target_id===String(data.target_id)&&item.relation_type===data.relation_type),stamp=now();if(same)return same.status==="active"?same:repository.update(Foundation.Relation.create({...same,status:"active",revoked_at:null,updated_at:stamp}));return repository.create(Foundation.Relation.create(audit({...data,id:idGenerator(),project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp,revoked_at:null})));}
    async function revokeRelation(projectId,id){const current=await foundationOwned(relationRepository,projectId,id,"SUPERVISION_RELATION_NOT_FOUND"),stamp=now();if(current.status==="revoked")return current;return relationRepository.update(Foundation.Relation.create({...current,status:"revoked",updated_at:stamp,revoked_at:stamp}));}
    async function actor(projectId,actorId){const workflow=await workflowService.listProjectWorkflow(String(projectId)),value=workflow.members.find(item=>item.id===String(actorId));if(!value||value.status!=="active")throw new SupervisionServiceError("SUPERVISION_ACTOR_FORBIDDEN","操作者不屬於此專案或已封存。");return value;}
    const elevated=value=>["owner","manager"].includes(value.role),reviewer=value=>["owner","manager","reviewer"].includes(value.role);
    async function ensureDraftOwner(projectId,current,actorId){const value=await actor(projectId,actorId),creator=current?.metadata?.created_by_member_id;if(current&&creator&&creator!==value.id&&!elevated(value))throw new SupervisionServiceError("SUPERVISION_DRAFT_FORBIDDEN","只有建立者或管理角色可修改此草稿。");return value;}
    const workflowRequired=(repository,name)=>{if(!WorkflowModels||!repository)throw new SupervisionServiceError("SUPERVISION_INSPECTION_WORKFLOW_UNAVAILABLE",`${name}尚未啟用。`);return repository;};
    async function eventByAction(projectId,actionId){if(!actionId||!inspectionEventRepository)return null;return(await inspectionEventRepository.listByProject(String(projectId))).find(item=>item.action_id===String(actionId))||null;}
    async function appendEvent(projectId,inspectionId,event_type,actor_ref,{revisionId=null,actionId=null,metadata={}}={}){return workflowRequired(inspectionEventRepository,"Inspection Audit").create(WorkflowModels.Event.create({id:idGenerator(),project_id:String(projectId),inspection_id:String(inspectionId),inspection_revision_id:revisionId,event_type,actor_ref,action_id:actionId,created_at:now(),metadata}));}
    async function replaceDraftRelation(projectId,inspectionId,targetType,targetId,relationType){if(!relationRepository)return null;const rows=await relationRepository.listByProject(String(projectId)),current=rows.filter(item=>item.source_type==="inspection"&&item.source_id===String(inspectionId)&&item.relation_type===relationType&&item.status==="active");if(targetId)await relationEndpoint(projectId,targetType,targetId);for(const row of current){if(!targetId||row.target_id!==String(targetId))await revokeRelation(projectId,row.id);}if(!targetId)return null;return addRelation(projectId,{source_type:"inspection",source_id:String(inspectionId),target_type:targetType,target_id:String(targetId),relation_type:relationType});}
    async function saveDraft(projectId,data={},actorId){await project(projectId);const current=data.id?await owned(inspectionRepository,projectId,data.id,"SUPERVISION_INSPECTION_NOT_FOUND"):null;if(current&&!['draft'].includes(current.status))throw new SupervisionServiceError("SUPERVISION_INSPECTION_EDIT_FORBIDDEN","只有 draft 可以修改。");const editor=await ensureDraftOwner(projectId,current,actorId),results=data.checklist_results||Checklist.template.items.map(item=>({item_key:item.key,result:"unverified",note:"",attachment_ids:[]})),snapshot=Checklist.snapshot(results,{allowUnverified:true}),stamp=now(),allAttachments=[...(data.attachment_ids||[]),...results.flatMap(row=>row.attachment_ids||[])];await attachments(projectId,allAttachments);if(data.work_item_id)await relationEndpoint(projectId,"work_item",data.work_item_id);if(data.site_location_id)await relationEndpoint(projectId,"site_location",data.site_location_id);const value=InspectionModel.create({...current,...data,id:current?.id||idGenerator(),project_id:String(projectId),module_id:"supervision",checklist_template_id:snapshot.template_id,checklist_template_version:snapshot.template_version,checklist_snapshot:snapshot,related_task_ids:current?.related_task_ids||[],status:"draft",current_revision:current?.current_revision||0,submitted_revision_id:current?.submitted_revision_id||null,submitted_by:current?.submitted_by||null,submitted_at:current?.submitted_at||null,reviewed_at:null,cancelled_at:null,created_at:current?.created_at||stamp,updated_at:stamp,metadata:{...(current?.metadata||{}),...(data.metadata||{}),created_by_member_id:current?.metadata?.created_by_member_id||editor.id,change_source:"manual-ui"}});let saved;try{saved=current?await inspectionRepository.update(value):await inspectionRepository.create(value);await replaceDraftRelation(projectId,saved.id,"work_item",data.work_item_id||null,"applies_to_work_item");await replaceDraftRelation(projectId,saved.id,"site_location",data.site_location_id||null,"located_at");await appendEvent(projectId,saved.id,"draft_saved",editor.id);return saved;}catch(error){if(!current&&saved)try{await inspectionRepository.delete(saved.id);}catch{}if(current&&saved)try{await inspectionRepository.update(current);}catch{}throw error;}}
    async function submissionSnapshots(projectId,inspection){const rows=relationRepository?await relationRepository.listByProject(String(projectId)):[],active=rows.filter(item=>item.source_type==="inspection"&&item.source_id===inspection.id&&item.status==="active"),workRelation=active.find(item=>item.relation_type==="applies_to_work_item"),locationRelation=active.find(item=>item.relation_type==="located_at"),work=workRelation?await foundationOwned(workItemRepository,projectId,workRelation.target_id,"SUPERVISION_RELATION_TARGET_NOT_FOUND"):null,location=locationRelation?await foundationOwned(locationRepository,projectId,locationRelation.target_id,"SUPERVISION_RELATION_TARGET_NOT_FOUND"):null;return{work_item_snapshot:work?{id:work.id,code:work.code,name:work.name,status:work.status}:null,site_location_snapshot:location?{id:location.id,code:location.code,name:location.name,status:location.status}:null};}
    async function submitInspection(projectId,id,actorId,actionId){const duplicate=await eventByAction(projectId,actionId);if(duplicate)return{inspection:await getInspection(projectId,duplicate.inspection_id),revision:duplicate.inspection_revision_id?await revisionRepository.getById(duplicate.inspection_revision_id):null,duplicate:true};const current=await getInspection(projectId,id);if(current.status!=="draft")throw new SupervisionServiceError("SUPERVISION_INSPECTION_TRANSITION_INVALID","只有 draft 可以提交。");const submitter=await ensureDraftOwner(projectId,current,actorId),template=Checklist.resolve(current.checklist_template_id,current.checklist_template_version);if(!template)throw new SupervisionServiceError("SUPERVISION_CHECKLIST_VERSION_UNKNOWN","Checklist 版本不存在。");const item_results=Checklist.validate(current.checklist_snapshot.results,{items:current.checklist_snapshot.items});await attachments(projectId,[...current.attachment_ids,...item_results.flatMap(row=>row.attachment_ids)]);const stamp=now(),revisionNumber=current.current_revision+1,snapshots=await submissionSnapshots(projectId,current),revision=WorkflowModels.Revision.create({id:idGenerator(),inspection_id:current.id,project_id:String(projectId),revision:revisionNumber,checklist_template_id:current.checklist_template_id,checklist_template_version:current.checklist_template_version,item_results,attachment_ids:current.attachment_ids,location_snapshot:current.location,...snapshots,created_by:submitter.id,created_at:stamp,content_hash:null,metadata:{change_source:"manual-ui"}}),next=InspectionModel.create({...current,status:"pending_review",current_revision:revisionNumber,submitted_revision_id:revision.id,submitted_by:submitter.id,submitted_at:stamp,reviewed_at:null,updated_at:stamp});let savedRevision,savedInspection,savedEvent;try{savedRevision=await workflowRequired(revisionRepository,"Inspection Revision").create(revision);savedInspection=await inspectionRepository.update(next);savedEvent=await appendEvent(projectId,current.id,"submitted",submitter.id,{revisionId:revision.id,actionId});return{inspection:savedInspection,revision:savedRevision,duplicate:false};}catch(error){if(savedEvent)try{await inspectionEventRepository.delete(savedEvent.id);}catch{}if(savedInspection)try{await inspectionRepository.update(current);}catch{}if(savedRevision)try{await revisionRepository.delete(savedRevision.id);}catch{}throw error;}}
    async function reviewInspection(projectId,id,decision,reason,reviewerId,actionId,expectedRevisionId){const duplicate=await eventByAction(projectId,actionId);if(duplicate)return{inspection:await getInspection(projectId,duplicate.inspection_id),review:(await inspectionReviewRepository.listByProject(String(projectId))).find(item=>item.action_id===String(actionId))||null,duplicate:true};const current=await getInspection(projectId,id);if(current.status!=="pending_review")throw new SupervisionServiceError("SUPERVISION_INSPECTION_TRANSITION_INVALID","只有 pending_review 可以審查。");if(!current.submitted_revision_id||String(expectedRevisionId||current.submitted_revision_id)!==current.submitted_revision_id)throw new SupervisionServiceError("SUPERVISION_INSPECTION_REVISION_STALE","送審版本已更新，請重新載入。");const member=await actor(projectId,reviewerId);if(!reviewer(member))throw new SupervisionServiceError("SUPERVISION_REVIEW_FORBIDDEN","此角色沒有查驗審查權限。");if(member.id===current.submitted_by)throw new SupervisionServiceError("SUPERVISION_SELF_REVIEW_FORBIDDEN","提交者不可核准或退回自己的查驗。");const stamp=now(),review=WorkflowModels.Review.create({id:idGenerator(),inspection_id:current.id,inspection_revision_id:current.submitted_revision_id,project_id:String(projectId),decision,reason,reviewer_ref:member.id,reviewed_at:stamp,action_id:actionId,metadata:{change_source:"manual-ui"}}),next=InspectionModel.create({...current,status:decision==="approved"?"reviewed":"returned",reviewed_at:decision==="approved"?stamp:null,updated_at:stamp});let savedReview,savedInspection,savedEvent;try{savedReview=await workflowRequired(inspectionReviewRepository,"Inspection Review").create(review);savedInspection=await inspectionRepository.update(next);savedEvent=await appendEvent(projectId,current.id,decision==="approved"?"approved":"returned",member.id,{revisionId:current.submitted_revision_id,actionId,metadata:{reason:review.reason}});return{inspection:savedInspection,review:savedReview,duplicate:false};}catch(error){if(savedEvent)try{await inspectionEventRepository.delete(savedEvent.id);}catch{}if(savedInspection)try{await inspectionRepository.update(current);}catch{}if(savedReview)try{await inspectionReviewRepository.delete(savedReview.id);}catch{}throw error;}}
    const returnInspection=(projectId,id,reason,reviewerId,actionId,expectedRevisionId)=>reviewInspection(projectId,id,"returned",reason,reviewerId,actionId,expectedRevisionId);
    const approveInspection=(projectId,id,reviewerId,actionId,expectedRevisionId)=>reviewInspection(projectId,id,"approved",null,reviewerId,actionId,expectedRevisionId);
    async function reviseInspection(projectId,id,actorId){const current=await getInspection(projectId,id);if(current.status!=="returned")throw new SupervisionServiceError("SUPERVISION_INSPECTION_TRANSITION_INVALID","只有 returned 可以開始修訂。");const editor=await ensureDraftOwner(projectId,current,actorId),next=InspectionModel.create({...current,status:"draft",updated_at:now()});await inspectionRepository.update(next);try{await appendEvent(projectId,id,"revision_started",editor.id,{revisionId:current.submitted_revision_id});}catch(error){await inspectionRepository.update(current);throw error;}return next;}
    async function cancelInspection(projectId,id,actorId,actionId){const duplicate=await eventByAction(projectId,actionId);if(duplicate)return getInspection(projectId,duplicate.inspection_id);const current=await getInspection(projectId,id);if(!["draft","returned"].includes(current.status))throw new SupervisionServiceError("SUPERVISION_INSPECTION_TRANSITION_INVALID","只有 draft 或 returned 可以取消。");const member=await ensureDraftOwner(projectId,current,actorId),stamp=now(),next=InspectionModel.create({...current,status:"cancelled",cancelled_at:stamp,updated_at:stamp});await inspectionRepository.update(next);try{await appendEvent(projectId,id,"cancelled",member.id,{revisionId:current.submitted_revision_id,actionId});}catch(error){await inspectionRepository.update(current);throw error;}return next;}
    async function listInspectionHistory(projectId,id){await getInspection(projectId,id);const[revisions,reviews,events]=await Promise.all([workflowRequired(revisionRepository,"Inspection Revision").listByProject(String(projectId)),workflowRequired(inspectionReviewRepository,"Inspection Review").listByProject(String(projectId)),workflowRequired(inspectionEventRepository,"Inspection Audit").listByProject(String(projectId))]);return{revisions:revisions.filter(item=>item.inspection_id===String(id)).sort((a,b)=>a.revision-b.revision),reviews:reviews.filter(item=>item.inspection_id===String(id)),events:events.filter(item=>item.inspection_id===String(id)).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)))};}
    async function getInspection(projectId,id){return owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND");}async function getDefect(projectId,id){return owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");}
    async function listProjectData(projectId){await project(projectId);const optional=repository=>repository?repository.listByProject(projectId):Promise.resolve([]),[inspections,defects,profiles,parties,work_items,locations,relations,revisions,reviews,inspection_events]=await Promise.all([inspectionRepository.listByProject(projectId),defectRepository.listByProject(projectId),optional(profileRepository),optional(partyRepository),optional(workItemRepository),optional(locationRepository),optional(relationRepository),optional(revisionRepository),optional(inspectionReviewRepository),optional(inspectionEventRepository)]);return{inspections,defects,profile:profiles[0]||null,parties,work_items,locations,relations,revisions,reviews,inspection_events,checklist:Checklist.template};}
    return Object.freeze({createInspection,updateInspection,archiveInspection,saveDraft,submitInspection,returnInspection,reviseInspection,approveInspection,cancelInspection,listInspectionHistory,createDefect,transitionDefect,createTaskForDefect,getInspection,getDefect,getProfile,saveProfile,archiveProfile,createParty,updateParty,archiveParty,createWorkItem,updateWorkItem,archiveWorkItem,createLocation,updateLocation,archiveLocation,addRelation,revokeRelation,listProjectData});
  }
  return Object.freeze({SupervisionServiceError,create});
});
