(function(root,factory){const isNode=typeof module==="object"&&module.exports,api=factory(isNode?require("./checklists/site-inspection-checklist.js"):root.EngineeringSupervisionSiteChecklist,isNode?require("./inspections/inspection-model.js"):root.EngineeringSupervisionInspectionModel,isNode?require("./defects/defect-model.js"):root.EngineeringSupervisionDefectModel);if(isNode)module.exports=api;else root.EngineeringSupervisionService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(Checklist,InspectionModel,DefectModel){
  "use strict";class SupervisionServiceError extends Error{constructor(code,message,cause){super(message,{cause});this.name="SupervisionServiceError";this.code=code;}}
  function create({projectService,inspectionRepository,defectRepository,attachmentRepository,workflowService,now=()=>new Date().toISOString(),idGenerator=()=>globalThis.crypto?.randomUUID?.()||`supervision-${Date.now()}-${Math.random().toString(16).slice(2)}`}={}){if(!projectService||!inspectionRepository||!defectRepository||!attachmentRepository||!workflowService)throw new TypeError("Supervision Service dependencies are required");
    async function project(projectId){const value=await projectService.getProject(String(projectId));if(!value.module_ids.includes("supervision"))throw new SupervisionServiceError("SUPERVISION_MODULE_DISABLED","此專案尚未啟用監造模組。");return value;}
    async function owned(repository,projectId,id,code){await project(projectId);const value=await repository.getById(String(id));if(!value||value.project_id!==String(projectId)||value.module_id!=="supervision")throw new SupervisionServiceError(code,"找不到此專案的監造資料。");return value;}
    async function attachments(projectId,ids=[]){for(const id of ids){const value=await attachmentRepository.getById(String(id));if(!value||value.project_id!==String(projectId))throw new SupervisionServiceError("SUPERVISION_ATTACHMENT_INVALID","附件不存在或屬於其他專案。");}}
    async function createInspection(projectId,data={}){await project(projectId);const results=Checklist.validate(data.checklist_results),snapshot=Checklist.snapshot(results),stamp=now();await attachments(projectId,[...(data.attachment_ids||[]),...results.flatMap(row=>row.attachment_ids)]);return inspectionRepository.create(InspectionModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",checklist_template_id:snapshot.template_id,checklist_template_version:snapshot.template_version,checklist_snapshot:snapshot,related_task_ids:[],status:data.status||"completed",created_at:stamp,updated_at:stamp}));}
    async function updateInspection(projectId,id,data={}){const current=await owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND"),attachment_ids=data.attachment_ids??current.attachment_ids;await attachments(projectId,attachment_ids);return inspectionRepository.update(InspectionModel.create({...current,...data,id:current.id,project_id:current.project_id,module_id:"supervision",created_at:current.created_at,checklist_template_id:current.checklist_template_id,checklist_template_version:current.checklist_template_version,checklist_snapshot:current.checklist_snapshot,updated_at:now()}));}
    async function archiveInspection(projectId,id){return updateInspection(projectId,id,{status:"archived"});}
    async function createDefect(projectId,data={}){await project(projectId);await owned(inspectionRepository,projectId,data.inspection_id,"SUPERVISION_INSPECTION_NOT_FOUND");await attachments(projectId,data.attachment_ids||[]);const stamp=now();return defectRepository.create(DefectModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",status:"open",related_task_id:null,created_at:stamp,updated_at:stamp,resolved_at:null}));}
    async function transitionDefect(projectId,id,target){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");return defectRepository.update(DefectModel.transition(current,String(target),now()));}
    async function createTaskForDefect(projectId,id,data,actorId){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");if(current.related_task_id)throw new SupervisionServiceError("SUPERVISION_TASK_ALREADY_LINKED","此缺失已關聯 Task。");const task=await workflowService.createTask(projectId,{...data,related_entity_type:"module_entity",related_entity_id:`supervision:defect:${current.id}`,metadata:{...(data?.metadata||{}),source_module:"supervision",source_entity:"defect"}},actorId);try{await defectRepository.update(DefectModel.create({...current,related_task_id:task.id,updated_at:now()}));}catch(error){throw new SupervisionServiceError("SUPERVISION_TASK_LINK_SAVE_FAILED","Task 已建立，但缺失反向連結保存失敗；Task 關聯仍可用於修復。",error);}return task;}
    async function getInspection(projectId,id){return owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND");}async function getDefect(projectId,id){return owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");}
    async function listProjectData(projectId){await project(projectId);const[inspections,defects]=await Promise.all([inspectionRepository.listByProject(projectId),defectRepository.listByProject(projectId)]);return{inspections,defects,checklist:Checklist.template};}
    return Object.freeze({createInspection,updateInspection,archiveInspection,createDefect,transitionDefect,createTaskForDefect,getInspection,getDefect,listProjectData});
  }
  return Object.freeze({SupervisionServiceError,create});
});
