(function(root,factory){const isNode=typeof module==="object"&&module.exports,api=factory(isNode?require("./checklists/site-inspection-checklist.js"):root.EngineeringSupervisionSiteChecklist,isNode?require("./inspections/inspection-model.js"):root.EngineeringSupervisionInspectionModel,isNode?require("./defects/defect-model.js"):root.EngineeringSupervisionDefectModel,isNode?require("./foundation-models.js"):root.EngineeringSupervisionFoundationModels);if(isNode)module.exports=api;else root.EngineeringSupervisionService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(Checklist,InspectionModel,DefectModel,Foundation){
  "use strict";class SupervisionServiceError extends Error{constructor(code,message,cause){super(message,{cause});this.name="SupervisionServiceError";this.code=code;}}
  function create({projectService,inspectionRepository,defectRepository,attachmentRepository,workflowService,profileRepository=null,partyRepository=null,workItemRepository=null,locationRepository=null,relationRepository=null,now=()=>new Date().toISOString(),idGenerator=()=>globalThis.crypto?.randomUUID?.()||`supervision-${Date.now()}-${Math.random().toString(16).slice(2)}`}={}){if(!projectService||!inspectionRepository||!defectRepository||!attachmentRepository||!workflowService)throw new TypeError("Supervision Service dependencies are required");
    async function project(projectId){const value=await projectService.getProject(String(projectId));if(!value.module_ids.includes("supervision"))throw new SupervisionServiceError("SUPERVISION_MODULE_DISABLED","此專案尚未啟用監造模組。");return value;}
    async function owned(repository,projectId,id,code){await project(projectId);const value=await repository.getById(String(id));if(!value||value.project_id!==String(projectId)||value.module_id!=="supervision")throw new SupervisionServiceError(code,"找不到此專案的監造資料。");return value;}
    async function attachments(projectId,ids=[]){for(const id of ids){const value=await attachmentRepository.getById(String(id));if(!value||value.project_id!==String(projectId))throw new SupervisionServiceError("SUPERVISION_ATTACHMENT_INVALID","附件不存在或屬於其他專案。");}}
    async function createInspection(projectId,data={}){await project(projectId);const results=Checklist.validate(data.checklist_results),snapshot=Checklist.snapshot(results),stamp=now();await attachments(projectId,[...(data.attachment_ids||[]),...results.flatMap(row=>row.attachment_ids)]);return inspectionRepository.create(InspectionModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",checklist_template_id:snapshot.template_id,checklist_template_version:snapshot.template_version,checklist_snapshot:snapshot,related_task_ids:[],status:data.status||"completed",created_at:stamp,updated_at:stamp}));}
    async function updateInspection(projectId,id,data={}){const current=await owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND"),attachment_ids=data.attachment_ids??current.attachment_ids;await attachments(projectId,attachment_ids);return inspectionRepository.update(InspectionModel.create({...current,...data,id:current.id,project_id:current.project_id,module_id:"supervision",created_at:current.created_at,checklist_template_id:current.checklist_template_id,checklist_template_version:current.checklist_template_version,checklist_snapshot:current.checklist_snapshot,updated_at:now()}));}
    async function archiveInspection(projectId,id){return updateInspection(projectId,id,{status:"archived"});}
    async function createDefect(projectId,data={}){await project(projectId);await owned(inspectionRepository,projectId,data.inspection_id,"SUPERVISION_INSPECTION_NOT_FOUND");await attachments(projectId,data.attachment_ids||[]);const stamp=now();return defectRepository.create(DefectModel.create({...data,id:idGenerator(),project_id:String(projectId),module_id:"supervision",status:"open",related_task_id:null,created_at:stamp,updated_at:stamp,resolved_at:null}));}
    async function transitionDefect(projectId,id,target){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");return defectRepository.update(DefectModel.transition(current,String(target),now()));}
    async function createTaskForDefect(projectId,id,data,actorId){const current=await owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");if(current.related_task_id)throw new SupervisionServiceError("SUPERVISION_TASK_ALREADY_LINKED","此缺失已關聯 Task。");const task=await workflowService.createTask(projectId,{...data,related_entity_type:"module_entity",related_entity_id:`supervision:defect:${current.id}`,metadata:{...(data?.metadata||{}),source_module:"supervision",source_entity:"defect"}},actorId);try{await defectRepository.update(DefectModel.create({...current,related_task_id:task.id,updated_at:now()}));}catch(error){throw new SupervisionServiceError("SUPERVISION_TASK_LINK_SAVE_FAILED","Task 已建立，但缺失反向連結保存失敗；Task 關聯仍可用於修復。",error);}return task;}
    const requireFoundation=(repository,name)=>{if(!repository)throw new SupervisionServiceError("SUPERVISION_FOUNDATION_UNAVAILABLE",`${name} 儲存服務尚未啟用。`);return repository;};
    async function foundationOwned(repository,projectId,id,code){await project(projectId);const value=await requireFoundation(repository,"監造主檔").getById(String(id));if(!value||value.project_id!==String(projectId))throw new SupervisionServiceError(code,"找不到此專案的監造主檔。");return value;}
    const audit=data=>({...data,metadata:{...(data?.metadata||{}),change_source:data?.metadata?.change_source||"manual-ui"}});
    async function getProfile(projectId){await project(projectId);if(!profileRepository)return null;return(await profileRepository.listByProject(String(projectId)))[0]||null;}
    async function saveProfile(projectId,data={}){await project(projectId);const stamp=now(),current=await getProfile(projectId),value=Foundation.Profile.create(audit({...current,...data,id:`supervision-profile:${projectId}`,project_id:String(projectId),status:data.status||current?.status||"active",created_at:current?.created_at||stamp,updated_at:stamp}));return current?profileRepository.update(value):requireFoundation(profileRepository,"工程資訊").create(value);}
    async function archiveProfile(projectId){const current=await getProfile(projectId);if(!current)throw new SupervisionServiceError("SUPERVISION_PROFILE_NOT_FOUND","找不到此專案的工程資訊。");return profileRepository.update(Foundation.Profile.create({...current,status:"archived",updated_at:now()}));}
    async function createParty(projectId,data={}){await project(projectId);const stamp=now();return requireFoundation(partyRepository,"參與單位").create(Foundation.Party.create(audit({...data,id:idGenerator(),project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp})));}
    async function updateParty(projectId,id,data={}){const current=await foundationOwned(partyRepository,projectId,id,"SUPERVISION_PARTY_NOT_FOUND");return partyRepository.update(Foundation.Party.create(audit({...current,...data,id:current.id,project_id:current.project_id,created_at:current.created_at,updated_at:now()})));}
    const archiveParty=(projectId,id)=>updateParty(projectId,id,{status:"archived"});
    async function validateHierarchy(repository,projectId,id,parentId){if(!parentId)return;if(String(id)===String(parentId))throw new SupervisionServiceError("SUPERVISION_HIERARCHY_CYCLE","項目不可成為自己的上層。");let cursor=await foundationOwned(repository,projectId,parentId,"SUPERVISION_PARENT_NOT_FOUND"),seen=new Set([String(id)]);while(cursor){if(seen.has(cursor.id))throw new SupervisionServiceError("SUPERVISION_HIERARCHY_CYCLE","階層不可形成循環。");seen.add(cursor.id);cursor=cursor.parent_id?await foundationOwned(repository,projectId,cursor.parent_id,"SUPERVISION_PARENT_NOT_FOUND"):null;}}
    async function createHierarchy(repository,model,projectId,data={}){await project(projectId);const stamp=now(),id=idGenerator();await validateHierarchy(repository,projectId,id,data.parent_id);return requireFoundation(repository,"階層主檔").create(model.create(audit({...data,id,project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp})));}
    async function updateHierarchy(repository,model,projectId,id,data={}){const current=await foundationOwned(repository,projectId,id,"SUPERVISION_HIERARCHY_NOT_FOUND"),next={...current,...data,id:current.id,project_id:current.project_id,created_at:current.created_at,updated_at:now()};await validateHierarchy(repository,projectId,id,next.parent_id);return repository.update(model.create(audit(next)));}
    const createWorkItem=(projectId,data)=>createHierarchy(workItemRepository,Foundation.WorkItem,projectId,data),updateWorkItem=(projectId,id,data)=>updateHierarchy(workItemRepository,Foundation.WorkItem,projectId,id,data),archiveWorkItem=(projectId,id)=>updateWorkItem(projectId,id,{status:"archived"});
    const createLocation=(projectId,data)=>createHierarchy(locationRepository,Foundation.SiteLocation,projectId,data),updateLocation=(projectId,id,data)=>updateHierarchy(locationRepository,Foundation.SiteLocation,projectId,id,data),archiveLocation=(projectId,id)=>updateLocation(projectId,id,{status:"archived"});
    const relationRule=Object.freeze({applies_to_work_item:["work_item"],located_at:["site_location"],responsible_party:["contract_party"]});
    async function relationEndpoint(projectId,type,id){const repositories={work_item:workItemRepository,site_location:locationRepository,contract_party:partyRepository};if(!repositories[type])throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","不支援的關聯端點。");return foundationOwned(repositories[type],projectId,id,"SUPERVISION_RELATION_TARGET_NOT_FOUND");}
    async function relationSource(projectId,type,id){const repositories={inspection:inspectionRepository,defect:defectRepository};if(!repositories[type])throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","不支援的來源類型。");return owned(repositories[type],projectId,id,"SUPERVISION_RELATION_SOURCE_NOT_FOUND");}
    async function addRelation(projectId,data={}){await project(projectId);if(!relationRule[data.relation_type]?.includes(data.target_type))throw new SupervisionServiceError("SUPERVISION_RELATION_TYPE_INVALID","關聯類型與目標類型不相容。");await Promise.all([relationSource(projectId,data.source_type,data.source_id),relationEndpoint(projectId,data.target_type,data.target_id)]);const repository=requireFoundation(relationRepository,"監造關聯"),rows=await repository.listByProject(String(projectId)),same=rows.find(item=>item.source_type===data.source_type&&item.source_id===String(data.source_id)&&item.target_type===data.target_type&&item.target_id===String(data.target_id)&&item.relation_type===data.relation_type),stamp=now();if(same)return same.status==="active"?same:repository.update(Foundation.Relation.create({...same,status:"active",revoked_at:null,updated_at:stamp}));return repository.create(Foundation.Relation.create(audit({...data,id:idGenerator(),project_id:String(projectId),status:"active",created_at:stamp,updated_at:stamp,revoked_at:null})));}
    async function revokeRelation(projectId,id){const current=await foundationOwned(relationRepository,projectId,id,"SUPERVISION_RELATION_NOT_FOUND"),stamp=now();if(current.status==="revoked")return current;return relationRepository.update(Foundation.Relation.create({...current,status:"revoked",updated_at:stamp,revoked_at:stamp}));}
    async function getInspection(projectId,id){return owned(inspectionRepository,projectId,id,"SUPERVISION_INSPECTION_NOT_FOUND");}async function getDefect(projectId,id){return owned(defectRepository,projectId,id,"SUPERVISION_DEFECT_NOT_FOUND");}
    async function listProjectData(projectId){await project(projectId);const optional=repository=>repository?repository.listByProject(projectId):Promise.resolve([]),[inspections,defects,profiles,parties,work_items,locations,relations]=await Promise.all([inspectionRepository.listByProject(projectId),defectRepository.listByProject(projectId),optional(profileRepository),optional(partyRepository),optional(workItemRepository),optional(locationRepository),optional(relationRepository)]);return{inspections,defects,profile:profiles[0]||null,parties,work_items,locations,relations,checklist:Checklist.template};}
    return Object.freeze({createInspection,updateInspection,archiveInspection,createDefect,transitionDefect,createTaskForDefect,getInspection,getDefect,getProfile,saveProfile,archiveProfile,createParty,updateParty,archiveParty,createWorkItem,updateWorkItem,archiveWorkItem,createLocation,updateLocation,archiveLocation,addRelation,revokeRelation,listProjectData});
  }
  return Object.freeze({SupervisionServiceError,create});
});
