import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import path from"node:path";import{fileURLToPath}from"node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const TemplateValidator=await import("../parametric/template-validator.js").then(m=>m.default),Registry=await import("../parametric/template-registry.js").then(m=>m.default),Parameters=await import("../parametric/parameter-validator.js").then(m=>m.default),Derived=await import("../parametric/derived-model.js").then(m=>m.default),Design=await import("../parametric/design-model.js").then(m=>m.default),DesignRepo=await import("../storage/design-repository.js").then(m=>m.default),Service=await import("../parametric/design-service.js").then(m=>m.default),Template=await import("../modules/woodworking/templates/open-box-cabinet.js").then(m=>m.default),Database=await import("../storage/engineering-db.js").then(m=>m.default),Workspace=await import("../pages/project-workspace.js").then(m=>m.default),Woodworking=await import("../modules/woodworking/module.js").then(m=>m.default);
const validParameters={width:800,height:900,depth:400,panel_thickness:18,shelf_count:2};
function memoryPersistence(){const rows=new Map();return{rows,async addData(store,row){assert.equal(store,"designs");if(rows.has(row.id))throw new Error("duplicate");rows.set(row.id,structuredClone(row));},async putData(store,row){assert.equal(store,"designs");rows.set(row.id,structuredClone(row));},async getData(store,id){assert.equal(store,"designs");return structuredClone(rows.get(id));},async listDataByProject(store,projectId){assert.equal(store,"designs");return structuredClone([...rows.values()].filter(row=>row.project_id===projectId));}};}
const projectService={async getProject(id){if(id==="missing")throw new Error("missing");return{id,module_ids:id==="unlinked"?[]:["woodworking"]};}};
function fixture({repository,registry,now}={}){const templateRegistry=registry||Registry.createRegistry();if(!registry)templateRegistry.registerTemplate(Template);const persistence=memoryPersistence(),designRepository=repository||DesignRepo.create({persistence}),service=Service.create({templateRegistry,designRepository,projectService,now:now||(()=>"2026-10-04T00:00:00.000Z"),idGenerator:()=>"d1"});return{templateRegistry,persistence,designRepository,service};}
const designData=overrides=>({id:"d1",project_id:"a",module_id:"woodworking",template_id:Template.id,template_version:Template.version,name:"箱體",parameters:validParameters,derived_snapshot:Template.derive(validParameters),revision:1,status:"draft",created_at:"2026-10-04T00:00:00.000Z",updated_at:"2026-10-04T00:00:00.000Z",metadata:{},...overrides});

test("E5-01 Template contract accepts the approved definition",()=>assert.equal(TemplateValidator.validate(Template).id,Template.id));
test("E5-02 Template requires a stable id",()=>assert.throws(()=>TemplateValidator.validate({...Template,id:""}),error=>error.code==="TEMPLATE_FIELD_REQUIRED"));
test("E5-03 Template requires semver",()=>assert.throws(()=>TemplateValidator.validate({...Template,version:"v1"}),error=>error.code==="TEMPLATE_VERSION_INVALID"));
test("E5-04 Template requires Parameter Schema",()=>assert.throws(()=>TemplateValidator.validate({...Template,parameter_schema:null}),error=>error.code==="TEMPLATE_SCHEMA_INVALID"));
test("E5-05 Template requires validate",()=>assert.throws(()=>TemplateValidator.validate({...Template,validate:null}),error=>error.code==="TEMPLATE_VALIDATE_INVALID"));
test("E5-06 Template requires pure derive contract",()=>assert.throws(()=>TemplateValidator.validate({...Template,derive:null}),error=>error.code==="TEMPLATE_DERIVE_INVALID"));
test("E5-07 Registry stores exact id and version",()=>{const registry=Registry.createRegistry();registry.registerTemplate(Template);const stored=registry.getTemplate(Template.id,Template.version);assert.equal(stored.id,Template.id);assert.equal(stored.version,Template.version);});
test("E5-08 Registry rejects duplicate id and version",()=>{const registry=Registry.createRegistry();registry.registerTemplate(Template);assert.throws(()=>registry.registerTemplate(Template),error=>error.code==="TEMPLATE_DUPLICATE");});
test("E5-09 Registry permits a new version without replacing old",()=>{const registry=Registry.createRegistry();registry.registerTemplate(Template);registry.registerTemplate({...Template,version:"1.1.0"});assert.equal(registry.listTemplates().length,2);assert.equal(registry.getTemplate(Template.id,"1.0.0").version,"1.0.0");});
test("E5-10 Registry unknown version returns null",()=>assert.equal(Registry.createRegistry().getTemplate("unknown","1.0.0"),null));
test("E5-11 Registry failure isolation records an error",()=>{const registry=Registry.createRegistry();registry.recordFailure(new Error("broken"));assert.equal(registry.failures()[0].message,"broken");});

test("E5-12 Parameter defaults normalize to canonical numbers",()=>assert.deepEqual({...Parameters.normalize(Template.parameter_schema,{})},{width:800,height:900,depth:400,panel_thickness:18,shelf_count:2}));
test("E5-13 numeric strings normalize",()=>assert.equal(Parameters.normalize(Template.parameter_schema,{...validParameters,width:"810"}).width,810));
test("E5-14 missing required parameter fails without a default",()=>assert.throws(()=>Parameters.normalize({fields:{x:{type:"number",required:true}}},{}),error=>error.code==="VALIDATION_ERROR"));
test("E5-15 NaN fails",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,width:NaN}),error=>error.issues[0].code==="PARAMETER_NOT_FINITE"));
test("E5-16 Infinity fails",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,width:Infinity}),error=>error.issues[0].code==="PARAMETER_NOT_FINITE"));
test("E5-17 negative and zero values fail minimum rules",()=>{for(const width of[-1,0])assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,width}),error=>error.issues[0].code==="PARAMETER_MIN");});
test("E5-18 maximum is enforced",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,width:3001}),error=>error.issues[0].code==="PARAMETER_MAX"));
test("E5-19 integer parameter rejects fractions",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,shelf_count:1.5}),error=>error.issues[0].code==="PARAMETER_INTEGER_REQUIRED"));
test("E5-20 unsupported unit is rejected",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,width:{value:80,unit:"cm"}}),error=>error.issues[0].code==="PARAMETER_UNIT_UNSUPPORTED"));
test("E5-21 unknown parameters are rejected",()=>assert.throws(()=>Parameters.normalize(Template.parameter_schema,{...validParameters,door_count:2}),error=>error.issues[0].code==="PARAMETER_UNKNOWN"));
test("E5-22 impossible internal width is domain validation",()=>assert.equal(Template.validate({...validParameters,width:200,panel_thickness:100})[0].code,"IMPOSSIBLE_INTERNAL_WIDTH"));
test("E5-23 impossible internal height is domain validation",()=>assert.equal(Template.validate({...validParameters,height:200,panel_thickness:100})[0].code,"IMPOSSIBLE_INTERNAL_HEIGHT"));

test("E5-24 derive is deterministic",()=>assert.deepEqual(Template.derive(validParameters),Template.derive(validParameters)));
test("E5-25 derive does not mutate input",()=>{const input={...validParameters};Template.derive(input);assert.deepEqual(input,validParameters);});
test("E5-26 Derived Model pins template identity",()=>{const result=Template.derive(validParameters);assert.equal(result.template_id,Template.id);assert.equal(result.template_version,"1.0.0");});
test("E5-27 overall dimensions use parameters as truth",()=>assert.deepEqual(Template.derive(validParameters).overall,{width_mm:800,height_mm:900,depth_mm:400,internal_width_mm:764,internal_height_mm:864}));
test("E5-28 stable logical part keys are unique",()=>{const keys=Template.derive(validParameters).parts.map(part=>part.key);assert.equal(new Set(keys).size,keys.length);assert.deepEqual(keys,["side-left","side-right","top","bottom","shelves"]);});
test("E5-29 shelf count is a derived quantity",()=>assert.equal(Template.derive({...validParameters,shelf_count:4}).parts.find(part=>part.key==="shelves").quantity,4));
test("E5-30 material reference remains a future placeholder",()=>assert.ok(Template.derive(validParameters).parts.every(part=>part.material_ref===null)));
test("E5-31 large span produces a professional warning",()=>assert.equal(Template.derive({...validParameters,width:1500}).warnings[0].code,"LARGE_UNVERIFIED_SPAN"));
test("E5-32 all approved golden samples pass",()=>{for(const sample of Template.metadata.golden_samples){const result=Template.derive(sample.parameters),shelf=result.parts.find(part=>part.key==="shelves");assert.equal(result.overall.internal_width_mm,sample.expected.internal_width_mm);assert.equal(result.parts.length,sample.expected.parts);assert.equal(shelf.quantity,sample.expected.shelf_quantity);assert.equal(result.warnings.length,sample.expected.warnings);}});
test("E5-33 template explicitly excludes unapproved features",()=>{for(const feature of["back_panel","doors","hardware","joinery","bom","quote"])assert.ok(Template.metadata.excluded_features.includes(feature));});
test("E5-34 Derived Model rejects duplicate part identities",()=>{const data=structuredClone(Template.derive(validParameters));data.parts[1].key=data.parts[0].key;assert.throws(()=>Derived.create(data),error=>error.code==="DERIVED_PART_KEY_DUPLICATE");});
test("E5-35 Derived Model rejects invalid quantity",()=>{const data=structuredClone(Template.derive(validParameters));data.parts[0].quantity=1.5;assert.throws(()=>Derived.create(data),error=>error.code==="DERIVED_PART_QUANTITY_INVALID");});

test("E5-36 ParametricDesign preserves parameters and snapshot",()=>{const design=Design.create(designData());assert.equal(design.parameters.width,800);assert.equal(design.derived_snapshot.template_version,"1.0.0");});
test("E5-37 ParametricDesign requires positive revision",()=>assert.throws(()=>Design.create(designData({revision:0})),error=>error.code==="DESIGN_REVISION_INVALID"));
test("E5-38 Design repository persists through a new instance",async()=>{const persistence=memoryPersistence();await DesignRepo.create({persistence}).create(designData());assert.equal((await DesignRepo.create({persistence}).getById("d1")).name,"箱體");});
test("E5-39 Design repository isolates projects",async()=>{const persistence=memoryPersistence(),repo=DesignRepo.create({persistence});await repo.create(designData());await repo.create(designData({id:"d2",project_id:"b"}));assert.equal((await repo.listByProject("a")).length,1);});
test("E5-40 Design repository archives without deleting snapshot",async()=>{const persistence=memoryPersistence(),repo=DesignRepo.create({persistence}),created=await repo.create(designData()),archived=await repo.archive(created);assert.equal(archived.status,"archived");assert.equal((await repo.getById("d1")).derived_snapshot.template_version,"1.0.0");});
test("E5-41 preview normalizes validates and derives",async()=>assert.equal((await fixture().service.preview({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:validParameters})).derived_snapshot.overall.internal_width_mm,764));
test("E5-42 invalid parameters never save",async()=>{const fx=fixture();await assert.rejects(fx.service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:{...validParameters,width:0}}),error=>error.code==="VALIDATION_ERROR");assert.equal(fx.persistence.rows.size,0);});
test("E5-43 unlinked module cannot create a design",async()=>await assert.rejects(fixture().service.preview({project_id:"unlinked",template_id:Template.id,template_version:Template.version,parameters:validParameters}),error=>error.code==="TEMPLATE_MODULE_NOT_LINKED"));
test("E5-44 save pins template version and snapshot",async()=>{const saved=await fixture().service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,name:"A",parameters:validParameters});assert.equal(saved.template_version,"1.0.0");assert.equal(saved.derived_snapshot.overall.width_mm,800);});
test("E5-45 draft update increments revision without changing template",async()=>{const fx=fixture(),saved=await fx.service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,name:"A",parameters:validParameters}),updated=await fx.service.updateDraft("a",saved.id,{name:"B",parameters:{...validParameters,width:900}});assert.equal(updated.revision,2);assert.equal(updated.template_version,"1.0.0");assert.equal(updated.derived_snapshot.overall.width_mm,900);});
test("E5-46 cross-project design access is blocked",async()=>{const fx=fixture();await fx.service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:validParameters});await assert.rejects(fx.service.getDesign("b","d1"),error=>error.code==="DESIGN_NOT_FOUND");});
test("E5-47 exact snapshot has no drift",async()=>{const fx=fixture();await fx.service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:validParameters});assert.equal((await fx.service.detectDrift("a","d1")).drift,false);});
test("E5-48 altered snapshot is detected without rewriting",async()=>{const fx=fixture(),saved=await fx.service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:validParameters});fx.persistence.rows.get("d1").derived_snapshot.overall.width_mm=999;assert.equal((await fx.service.detectDrift("a",saved.id)).drift,true);assert.equal(fx.persistence.rows.get("d1").derived_snapshot.overall.width_mm,999);});
test("E5-49 unknown template version keeps old snapshot readable",async()=>{const registry=Registry.createRegistry(),persistence=memoryPersistence(),repo=DesignRepo.create({persistence});await repo.create(designData());const service=Service.create({templateRegistry:registry,designRepository:repo,projectService});const result=await service.getDesign("a","d1");assert.match(result.compatibility_warning,/UNKNOWN_TEMPLATE_VERSION/);assert.equal(result.design.derived_snapshot.overall.width_mm,800);});
test("E5-50 derive throw maps to DESIGN_DERIVATION_ERROR",async()=>{const registry=Registry.createRegistry();registry.registerTemplate({...Template,id:"woodworking.broken",derive(){throw new Error("broken");}});await assert.rejects(fixture({registry}).service.preview({project_id:"a",template_id:"woodworking.broken",template_version:"1.0.0",parameters:validParameters}),error=>error.code==="DESIGN_DERIVATION_ERROR");});
test("E5-51 save failure retains preview in error details",async()=>{const repository={async create(){throw new Error("disk");}},service=fixture({repository}).service;await assert.rejects(service.saveDraft({project_id:"a",template_id:Template.id,template_version:Template.version,parameters:validParameters}),error=>error.code==="DESIGN_SAVE_FAILED"&&error.details.preview.derived_snapshot.overall.width_mm===800);});

test("E5-52 Engineering DB keeps Phase 5 designs alongside later stores",()=>{assert.equal(Database.DB_VERSION,12);assert.equal(Database.STORES.designs,"designs");for(const name of["projects","calculations","measurements","notes","attachments","project_records"])assert.equal(Database.STORES[name],name);});
test("E5-53 designs store has project and template indexes",()=>{const source=read("engineering/storage/engineering-db.js");assert.match(source,/createProjectDataStore\(STORES\.designs,\["template_id","status","updated_at"\]\)/);assert.match(source,/store\.createIndex\("project_id"/);});
test("E5-54 later migration creates commercial stores without removing designs",async()=>{const existing=new Set(["projects","settings","calculations","measurements","notes","attachments","project_records","designs"]),created=[],db={objectStoreNames:{contains:name=>existing.has(name)},createObjectStore(name){created.push(name);existing.add(name);return{createIndex(){}};},close(){},transaction(){throw new Error("unused");}},request={result:db};const indexedDBImpl={open(name,version){assert.equal(version,12);queueMicrotask(()=>{request.onupgradeneeded?.();request.onsuccess?.();});return request;}};await Database.openDatabase(indexedDBImpl);assert.deepEqual(created,["boms","price_entries","quotes","project_members","tasks","task_reviews","workflow_events","ai_drafts","ai_actions","ai_events","supervision_inspections","supervision_defects","supervision_profiles","supervision_parties","supervision_work_items","supervision_locations","supervision_relations","supervision_inspection_revisions","supervision_inspection_reviews","supervision_inspection_events","supervision_corrective_rounds","supervision_defect_reviews","supervision_defect_events","sync_outbox","sync_state","sync_conflicts","sync_receipts","sync_audit"]);});
test("E5-55 Workspace renders Furniture Designs only for linked Woodworking",()=>{const project={id:"a",name:"A",status:"active",workspace_id:"w",module_ids:["woodworking"],created_at:"2026-10-04T00:00:00Z",updated_at:"2026-10-04T00:00:00Z"},html=Workspace.render({project,modules:[Woodworking],furniture:{templates:[Template],designs:[],templateKey:`${Template.id}@${Template.version}`,parameters:{},preview:null}});assert.match(html,/家具設計/);assert.match(html,/開放式箱體/);assert.doesNotMatch(Workspace.render({...{project:{...project,module_ids:[]},modules:[Woodworking]}}),/PARAMETRIC FURNITURE/);});
test("E5-56 UI displays structured derived parts without drawing",()=>{const project={id:"a",name:"A",status:"active",workspace_id:"w",module_ids:["woodworking"],created_at:"2026-10-04T00:00:00Z",updated_at:"2026-10-04T00:00:00Z"},html=Workspace.render({project,modules:[Woodworking],furniture:{templates:[Template],designs:[],templateKey:`${Template.id}@${Template.version}`,parameters:validParameters,preview:{derived_snapshot:Template.derive(validParameters)}}});assert.match(html,/Logical Key/);assert.match(html,/side-left/);assert.doesNotMatch(html,/canvas|WebGL|DXF/);});
test("E5-57 UI never derives geometry or writes IndexedDB",()=>{const source=read("engineering/pages/project-workspace.js");assert.doesNotMatch(source,/\.derive\(|indexedDB|openDatabase|putData|addData/);});
test("E5-58 production load order is Registry to Template to runtime",()=>{const source=read("index.html"),registry=source.indexOf("parametric/template-registry.js"),template=source.indexOf("templates/open-box-cabinet.js"),runtime=source.indexOf("engineering/engineering.js?v=16");assert.ok(registry>0&&registry<template&&template<runtime);});
test("E5-59 Engineering core has no furniture special case",()=>{const source=fs.readdirSync(path.join(root,"engineering/core"),{recursive:true}).filter(file=>String(file).endsWith(".js")).map(file=>read(`engineering/core/${file}`)).join("\n");assert.doesNotMatch(source,/open-box-cabinet|panel_thickness|shelf_count|woodworking\.open-box/i);});
test("E5-60 Phase 5 does not implement forbidden systems",()=>{const source=["engineering/parametric","engineering/modules/woodworking/templates","engineering/storage/design-repository.js"].flatMap(target=>{const full=path.join(root,target);return fs.statSync(full).isDirectory()?fs.readdirSync(full).filter(file=>file.endsWith(".js")).map(file=>fs.readFileSync(path.join(full,file),"utf8")):[fs.readFileSync(full,"utf8")];}).join("\n");assert.doesNotMatch(source,/WebGL|DXF|Supabase|photo recognition|price book|quote_pdf|callAI/i);assert.match(read("finance/storage/finance-db.js"),/DB_VERSION=1/);});
