import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import path from"node:path";import{fileURLToPath}from"node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const Template=await import("../modules/woodworking/templates/open-box-cabinet-v1.1.js").then(m=>m.default),Legacy=await import("../modules/woodworking/templates/open-box-cabinet.js").then(m=>m.default),BomModel=await import("../core/bom/bom-model.js").then(m=>m.default),BomAdapter=await import("../modules/woodworking/bom/woodworking-bom-adapter.js").then(m=>m.default),BomService=await import("../core/bom/bom-service.js").then(m=>m.default),PriceModel=await import("../core/quotes/price-model.js").then(m=>m.default),QuoteModel=await import("../core/quotes/quote-model.js").then(m=>m.default),QuoteService=await import("../core/quotes/quote-service.js").then(m=>m.default),Publisher=await import("../core/quotes/quote-publisher.js").then(m=>m.default),Pdf=await import("../documents/quote-pdf-renderer.js").then(m=>m.default),Workspace=await import("../pages/project-workspace.js").then(m=>m.default),Db=await import("../storage/engineering-db.js").then(m=>m.default);
const parameters={width:800,height:900,depth:400,panel_thickness:18,shelf_count:2};const snapshot=Template.derive(parameters);const design={id:"design-p7",project_id:"project-a",template_id:Template.id,template_version:Template.version,revision:2,derived_snapshot:snapshot};const legacyDesign={...design,id:"legacy-p7",template_version:Legacy.version,derived_snapshot:Legacy.derive(parameters)};
const clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value));function memory(){const rows=new Map();return{rows,async addData(store,row){if(rows.has(`${store}:${row.id}`))throw Error("duplicate");rows.set(`${store}:${row.id}`,clone(row));},async putData(store,row){rows.set(`${store}:${row.id}`,clone(row));},async getData(store,id){return clone(rows.get(`${store}:${id}`));},async listDataByProject(store,projectId){return [...rows.values()].filter(row=>row.project_id===projectId&&Object.keys(row).length).map(clone);}};}
function repos(){const persistence=memory();const bomRepository={async create(row){await persistence.addData("boms",row);return row;},async getById(id){return persistence.getData("boms",id);},async listByProject(projectId){return persistence.listDataByProject("boms",projectId);},async listByDesign(projectId,designId){return(await this.listByProject(projectId)).filter(row=>row.design_id===designId);}};const quoteRepository={async create(row){await persistence.addData("quotes",row);return row;},async getById(id){return persistence.getData("quotes",id);},async listByProject(projectId){return persistence.listDataByProject("quotes",projectId);},async updateDraft(row){await persistence.putData("quotes",row);return row;},async publish(_,row){await persistence.putData("quotes",row);return row;}};return{persistence,bomRepository,quoteRepository};}
const project={id:"project-a",name:"Project A",status:"active",module_ids:["woodworking"]};
function price(item,index=1){return PriceModel.create({id:`price-${item.id}-${index}`,project_id:project.id,bom_item_id:item.id,description:item.description,pricing_basis:"per_piece",unit_price:100*index,currency:"TWD",effective_at:"2026-10-04T00:00:00.000Z",version:index,source:"manual",metadata:{}});}

test("P7-01 BOM source is saved derived snapshot",()=>{const before=clone(design);const value=BomAdapter.fromDesign(design);assert.equal(value.items.length,5);assert.deepEqual(design,before);});
test("P7-02 one logical part becomes one BOM line",()=>assert.deepEqual(BomAdapter.fromDesign(design).items.map(item=>item.logical_part_key),snapshot.parts.map(part=>part.key)));
test("P7-03 BOM copies quantity from snapshot",()=>assert.deepEqual(BomAdapter.fromDesign(design).items.map(item=>item.quantity),snapshot.parts.map(part=>part.quantity)));
test("P7-04 BOM copies source dimensions",()=>{const item=BomAdapter.fromDesign(design).items[0];assert.deepEqual(item.dimensions,snapshot.parts[0].dimensions);});
test("P7-05 BOM material boundary keeps ref null",()=>assert.ok(BomAdapter.fromDesign(design).items.every(item=>item.material_ref===null&&item.material_label==="")));
test("P7-06 BOM unit is piece and does not infer trade units",()=>assert.ok(BomAdapter.fromDesign(design).items.every(item=>item.unit==="piece")));
test("P7-07 BOM source hash is deterministic",()=>assert.equal(BomAdapter.hashSnapshot(snapshot),BomAdapter.hashSnapshot(clone(snapshot))));
test("P7-08 BOM model pins design and template revision",()=>{const fx=repos(),service=BomService.create({repository:fx.bomRepository,adapter:BomAdapter,idGenerator:()=>"bom-1",now:()=>"2026-10-04T00:00:00Z"});return service.generate(project.id,design).then(value=>{assert.equal(value.design_revision,2);assert.equal(value.template_version,"1.1.0");assert.equal(value.version,1);});});
test("P7-09 BOM regeneration creates a new version",async()=>{const fx=repos(),service=BomService.create({repository:fx.bomRepository,adapter:BomAdapter,idGenerator:(()=>{let n=0;return()=>`bom-${++n};`;})(),now:()=>"2026-10-04T00:00:00Z"});const first=await service.generate(project.id,design),second=await service.generate(project.id,design);assert.equal(first.version,1);assert.equal(second.version,2);});
test("P7-10 invalid snapshot is rejected",()=>{assert.throws(()=>BomAdapter.fromDesign({...design,derived_snapshot:{parts:[]}}),error=>error.code==="BOM_SOURCE_INVALID");});
test("P7-11 old v1.0 snapshot remains readable for BOM",()=>assert.equal(BomAdapter.fromDesign(legacyDesign).items.length,5));
test("P7-12 BOM has no cabinet geometry formula",()=>{const code=read("engineering/modules/woodworking/bom/woodworking-bom-adapter.js");assert.doesNotMatch(code,/innerWidth|panel_thickness|width\s*[-+*]/);});
test("P7-13 BOM does not aggregate logical keys",()=>assert.equal(new Set(BomAdapter.fromDesign(design).items.map(item=>item.logical_part_key)).size,5));
test("P7-14 BOM model rejects duplicate logical keys",()=>assert.throws(()=>BomModel.create({...BomAdapter.fromDesign(design),id:"b",project_id:"p",design_id:"d",design_revision:1,template_id:"t",template_version:"1.0.0",version:1,created_at:"x",items:[...BomAdapter.fromDesign(design).items,{...BomAdapter.fromDesign(design).items[0],id:"duplicate"}],source_snapshot_hash:"h"}),error=>error.code==="BOM_LOGICAL_KEY_DUPLICATE"));

test("P7-15 price entry accepts manual per-piece TWD",()=>assert.equal(price(BomAdapter.fromDesign(design).items[0]).pricing_basis,"per_piece"));
test("P7-16 unsupported pricing basis is rejected",()=>assert.throws(()=>PriceModel.create({...price(BomAdapter.fromDesign(design).items[0]),pricing_basis:"per_area"}),error=>error.code==="PRICE_BASIS_UNSUPPORTED"));
test("P7-17 unsupported currency is rejected",()=>assert.throws(()=>PriceModel.create({...price(BomAdapter.fromDesign(design).items[0]),currency:"USD"}),error=>error.code==="PRICE_CURRENCY_UNSUPPORTED"));
test("P7-18 negative price is rejected",()=>assert.throws(()=>PriceModel.create({...price(BomAdapter.fromDesign(design).items[0]),unit_price:-1}),error=>error.code==="PRICE_INVALID"));
test("P7-19 fractional TWD price is rejected",()=>assert.throws(()=>PriceModel.create({...price(BomAdapter.fromDesign(design).items[0]),unit_price:1.5}),error=>error.code==="PRICE_INVALID"));
test("P7-20 price versions are retained",()=>assert.notEqual(price(BomAdapter.fromDesign(design).items[0],1).version,price(BomAdapter.fromDesign(design).items[0],2).version));
test("P7-21 missing price remains null",()=>{const bom={...BomAdapter.fromDesign(design),id:"bom-p7",project_id:project.id,design_id:design.id,design_revision:2,template_id:Template.id,template_version:Template.version,version:1,created_at:"2026-10-04",metadata:{}};const lines=QuoteService.priceLines(bom,[]);assert.ok(lines.every(line=>line.unit_price===null&&line.line_total===null));});
test("P7-22 latest price version resolves deterministically",()=>{const item=BomAdapter.fromDesign(design).items[0],one=price(item,1),two={...price(item,2),id:"newer"};assert.equal(QuoteService.priceLines({...BomAdapter.fromDesign(design),id:"bom",project_id:project.id,design_id:design.id,design_revision:2,template_id:Template.id,template_version:Template.version,version:1,created_at:"x",metadata:{}},[one,two])[0].unit_price,200);});
test("P7-23 quote uses fixed rounding policy",()=>assert.equal(QuoteService.ROUNDING_POLICY,"TWD-0-HALF-UP"));

async function bomFixture(){const fx=repos(),bomService=BomService.create({repository:fx.bomRepository,adapter:BomAdapter,idGenerator:()=>"bom-p7",now:()=>"2026-10-04T00:00:00Z"}),bom=await bomService.generate(project.id,design);const quoteService=QuoteService.create({repository:fx.quoteRepository,idGenerator:(()=>{let n=0;return()=>`quote-${++n}`;})(),now:()=>"2026-10-04T00:00:00Z"});return{...fx,bom,quoteService};}
test("P7-24 quote draft can be created from persisted BOM",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.equal(draft.status,"draft");assert.equal(draft.bom_id,fx.bom.id);});
test("P7-25 quote draft has unresolved lines without prices",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.equal(draft.total,null);assert.ok(draft.lines.every(line=>line.unit_price===null));});
test("P7-26 manual prices calculate lines in domain service",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map((item,index)=>price(item,index+1)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries);assert.equal(draft.lines[0].line_total,100);assert.equal(draft.subtotal,draft.total);assert.equal(draft.tax,0);});
test("P7-27 quantity calculation is not done in UI",()=>assert.doesNotMatch(read("engineering/pages/project-workspace.js"),/quantity\s*\*|line_total\s*=|subtotal\s*=/));
test("P7-28 quote preserves BOM traceability",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.deepEqual(draft.lines.map(line=>line.source_bom_item_id),fx.bom.items.map(item=>item.id));});
test("P7-29 quote revision starts at one",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.equal(draft.version,1);});
test("P7-30 quote number includes date and revision",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.match(draft.quote_number,/^Q-20261004-[A-Z0-9]+-R1$/);});
test("P7-31 quote project isolation is enforced",async()=>{const fx=await bomFixture();await assert.rejects(fx.quoteService.get("project-b","missing"),error=>error.code==="QUOTE_NOT_FOUND");});
test("P7-32 quote missing price produces explicit validation issue",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]);assert.equal(fx.quoteService.validateForPublish(draft).filter(item=>item.code==="PRICE_MISSING").length,5);});
test("P7-33 quote invalid quantity blocks model",()=>assert.throws(()=>QuoteModel.create({...({id:"q",quote_number:"Q",project_id:"p",design_id:"d",bom_id:"b",version:1,status:"draft",currency:"TWD",lines:[{id:"l",source_bom_item_id:"i",logical_part_key:"k",description:"x",quantity:0,unit:"piece",unit_price:null,line_total:null}],subtotal:null,adjustments:[],tax:0,total:null,rounding_policy:"TWD-0-HALF-UP",created_at:"x",updated_at:"x"})}),error=>error.code==="QUOTE_QUANTITY_INVALID"));
test("P7-34 quote save failure exposes unsaved draft",async()=>{const fx=await bomFixture(),bad={...fx.quoteRepository,create(){throw Error("disk")}},service=QuoteService.create({repository:bad});await assert.rejects(service.createDraft(project.id,fx.bom,[]),error=>error.code==="QUOTE_SAVE_FAILED"&&error.details.draft.status==="draft");});
test("P7-35 draft repricing updates only draft",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]),entries=fx.bom.items.map(item=>price(item));const updated=await fx.quoteService.repriceDraft(project.id,draft.id,fx.bom,entries);assert.equal(updated.status,"draft");assert.equal(updated.total,600);});
test("P7-36 complete draft passes publish validation",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries);assert.deepEqual(fx.quoteService.validateForPublish(draft),[]);});

test("P7-37 publisher requires human-eligible complete draft",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService,now:()=>"2026-10-04T01:00:00Z"}),published=await publisher.publish(project.id,draft.id);assert.equal(published.status,"published");assert.equal(published.snapshot.status,"published");});
test("P7-38 published quote contains complete snapshot",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService}),published=await publisher.publish(project.id,draft.id);assert.equal(published.snapshot.total,published.total);assert.equal(published.snapshot.bom_id,fx.bom.id);});
test("P7-39 missing price blocks publish",async()=>{const fx=await bomFixture(),draft=await fx.quoteService.createDraft(project.id,fx.bom,[]),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService});await assert.rejects(publisher.publish(project.id,draft.id),error=>error.code==="QUOTE_PUBLISH_BLOCKED");});
test("P7-40 publish failure leaves draft",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),bad={...fx.quoteRepository,publish(){throw Error("disk")}},publisher=Publisher.create({repository:bad,quoteService:fx.quoteService});await assert.rejects(publisher.publish(project.id,draft.id),error=>error.code==="QUOTE_PUBLISH_FAILED");assert.equal((await fx.quoteRepository.getById(draft.id)).status,"draft");});
test("P7-41 published quote is immutable in repository",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService}),published=await publisher.publish(project.id,draft.id);await assert.rejects(fx.quoteService.repriceDraft(project.id,published.id,fx.bom,entries),error=>error.code==="QUOTE_IMMUTABLE");});
test("P7-42 new revision does not mutate published quote",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService}),published=await publisher.publish(project.id,draft.id),revision=await fx.quoteService.newRevision(project.id,published,fx.bom,entries);assert.equal(published.status,"published");assert.equal(revision.status,"draft");assert.equal(revision.version,2);});
test("P7-43 quote archive does not overwrite published",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService}),published=await publisher.publish(project.id,draft.id);assert.equal(published.status,"published");});
test("P7-44 price changes do not change published snapshot",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),publisher=Publisher.create({repository:fx.quoteRepository,quoteService:fx.quoteService}),published=await publisher.publish(project.id,draft.id),before=clone(published.snapshot),changed=entries.map(item=>({...item,unit_price:item.unit_price+999,version:item.version+1}));assert.deepEqual(published.snapshot,before);assert.notDeepEqual(changed,entries);});

test("P7-45 PDF document marks draft clearly",()=>{const document=Pdf.documentFromQuote({status:"draft",quote_number:"Q-R1",version:1,design_id:"d",metadata:{template_id:"t",template_version:"1.1.0"},updated_at:"2026-10-04",currency:"TWD",lines:[],subtotal:null,tax:0,total:null,rounding_policy:"TWD-0-HALF-UP"});assert.equal(document.marker,"DRAFT");});
test("P7-46 PDF document marks published clearly",()=>{const quote={status:"published",snapshot:{status:"published",quote_number:"Q",version:1,design_id:"d",template_id:"t",template_version:"1.1.0",currency:"TWD",lines:[{description:"板",quantity:1,unit:"piece",unit_price:100,line_total:100}],subtotal:100,tax:0,total:100,rounding_policy:"TWD-0-HALF-UP",published_at:"2026-10-04"},metadata:{}};assert.equal(Pdf.documentFromQuote(quote).marker,"PUBLISHED");});
test("P7-47 PDF layout wraps long descriptions",()=>{const book=Pdf.layout({marker:"DRAFT",lines:[{description:"這是一個很長很長很長很長很長很長很長很長的家具材料描述文字用來測試換行",quantity:1,unit:"piece",unit_price:null,line_total:null}],subtotal:null,tax:0,total:null,rounding_policy:"TWD-0-HALF-UP"},{rowsPerPage:18});assert.ok(book.pages[0].rows.length>1);});
test("P7-48 PDF layout paginates rows with repeated page model",()=>{const lines=Array.from({length:20},(_,i)=>({description:`項目${i}`,quantity:1,unit:"piece",unit_price:1,line_total:1})),book=Pdf.layout({marker:"PUBLISHED",lines,subtotal:20,tax:0,total:20,rounding_policy:"TWD-0-HALF-UP"},{rowsPerPage:18});assert.equal(book.pages.length,2);assert.equal(book.pages[0].showTotals,false);assert.equal(book.pages[1].showTotals,true);});
test("P7-49 PDF renderer does not calculate totals",()=>{const code=read("engineering/documents/quote-pdf-renderer.js");assert.doesNotMatch(code,/quantity\s*\*|line_total\s*=\s*[^=>]/);});
test("P7-50 PDF binary is A4 and valid PDF header",()=>{const bytes=Pdf.buildPdf([{bytes:new Uint8Array([255,216,255,217]),width:1240,height:1754}]);const text=new TextDecoder().decode(bytes);assert.equal(text.slice(0,8),"%PDF-1.4");assert.match(text,/MediaBox \[0 0 595\.28 841\.89\]/);});
test("P7-51 PDF source invalidates missing lines",()=>assert.throws(()=>Pdf.documentFromQuote({status:"draft",lines:null}),error=>error.code==="PDF_SOURCE_INVALID"));
test("P7-52 PDF failure has no quote mutation",async()=>{const fx=await bomFixture(),entries=fx.bom.items.map(item=>price(item)),draft=await fx.quoteService.createDraft(project.id,fx.bom,entries),before=clone(draft);assert.deepEqual(draft,before);});

const uiProject={...project,created_at:"2026-10-04T00:00:00Z",updated_at:"2026-10-04T00:00:00Z",workspace_id:"w"};
test("P7-53 workspace exposes BOM and Quote controls only for woodworking",()=>{const html=Workspace.render({project:uiProject,modules:[],furniture:{designs:[design]},commercial:{boms:[],quotes:[],prices:[]}});assert.match(html,/BOM · QUOTE · PDF · PHASE 7/);assert.match(html,/生成 BOM Snapshot/);});
test("P7-54 unlinked project does not expose commercial section",()=>{const html=Workspace.render({project:{...uiProject,module_ids:[]},modules:[],furniture:{designs:[design]},commercial:{}});assert.doesNotMatch(html,/BOM · QUOTE · PDF/);});
test("P7-55 draft UI includes explicit human publish action",()=>{const bom=BomAdapter.fromDesign(design);const html=Workspace.render({project:uiProject,modules:[],furniture:{designs:[design]},commercial:{boms:[{...bom,id:"b",project_id:project.id,design_id:design.id,design_revision:2,template_id:Template.id,template_version:Template.version,version:1,created_at:"2026-10-04",metadata:{}}],quotes:[{id:"q",quote_number:"Q",project_id:project.id,design_id:design.id,bom_id:"b",version:1,status:"draft",currency:"TWD",lines:[{id:"l",source_bom_item_id:"i",logical_part_key:"k",description:"x",quantity:1,unit:"piece",unit_price:100,line_total:100}],subtotal:100,adjustments:[],tax:0,total:100,rounding_policy:"TWD-0-HALF-UP",created_at:"2026-10-04",updated_at:"2026-10-04",metadata:{bom_version:1,design_revision:2,template_id:Template.id,template_version:Template.version}}]}});assert.match(html,/人工確認並發布/);});
test("P7-56 published UI includes new revision action",()=>{const html=Workspace.render({project:uiProject,modules:[],furniture:{designs:[design]},commercial:{boms:[],quotes:[{id:"q",quote_number:"Q",project_id:project.id,design_id:"d",bom_id:"b",version:1,status:"published",currency:"TWD",lines:[{id:"l",source_bom_item_id:"i",logical_part_key:"k",description:"x",quantity:1,unit:"piece",unit_price:1,line_total:1}],subtotal:1,adjustments:[],tax:0,total:1,rounding_policy:"TWD-0-HALF-UP",snapshot:{status:"published",quote_number:"Q",version:1,design_id:"d",bom_id:"b",currency:"TWD",lines:[{description:"x",quantity:1,unit:"piece",unit_price:1,line_total:1}],subtotal:1,tax:0,total:1,rounding_policy:"TWD-0-HALF-UP"},created_at:"2026-10-04",updated_at:"2026-10-04",published_at:"2026-10-04",metadata:{bom_version:1,design_revision:2,template_id:Template.id,template_version:Template.version}}]}});assert.match(html,/建立新 Revision/);assert.doesNotMatch(html,/人工確認並發布/);});
test("P7-57 migration retains all prior and new stores",()=>{assert.equal(Db.DB_VERSION,5);for(const name of["designs","boms","price_entries","quotes"])assert.equal(Db.STORES[name],name);});
test("P7-58 Finance DB remains v1 and no Finance writes are introduced",()=>{const core=fs.readdirSync(path.join(root,"engineering/core"),{recursive:true}).filter(file=>String(file).endsWith(".js")).map(file=>fs.readFileSync(path.join(root,"engineering/core",file),"utf8")).join("\n");assert.match(read("finance/storage/finance-db.js"),/DB_VERSION=1/);assert.doesNotMatch(core,/finance|transactions|FinanceStorage/i);});
test("P7-59 no AI or cloud sync participates in commercial domain",()=>{const files=["engineering/core/bom/bom-model.js","engineering/core/bom/bom-service.js","engineering/core/quotes/price-model.js","engineering/core/quotes/quote-model.js","engineering/core/quotes/quote-service.js","engineering/core/quotes/quote-publisher.js","engineering/modules/woodworking/bom/woodworking-bom-adapter.js","engineering/documents/quote-pdf-renderer.js"];const code=files.map(read).join("\n");assert.doesNotMatch(code,/callAI|Supabase|Cloudflare|cloud sync|WebGL|DXF|invoice|inventory|supplier/i);});
test("P7-60 Phase 7 architecture records the approved boundaries",()=>{const doc=read("engineering/phase7-bom-quote-architecture.md");for(const phrase of["One logical part becomes one BOM line","manual","published quote","layout only","Engineering IndexedDB upgrades from v4 to v5"])assert.match(doc,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));});
