import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";

const require=createRequire(import.meta.url),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const Database=require("../storage/engineering-db.js"),Measurement=require("../core/project-data/measurement-model.js"),Note=require("../core/project-data/note-model.js"),Attachment=require("../core/project-data/attachment-model.js"),ProjectRecord=require("../core/project-data/project-record-model.js"),Factory=require("../storage/project-data-repository.js"),MeasurementRepo=require("../storage/measurement-repository.js"),NoteRepo=require("../storage/note-repository.js"),AttachmentRepo=require("../storage/attachment-repository.js"),RecordRepo=require("../storage/project-record-repository.js"),Binary=require("../storage/attachment-storage-adapter.js"),Service=require("../core/project-data/project-data-service.js"),Workspace=require("../pages/project-workspace.js");
const stamp="2026-10-04T01:00:00.000Z";
const measurement=(changes={})=>({id:"m1",project_id:"a",type:"dimension",label:"現場寬度",values:{value:120},units:{value:"cm"},notes:"",source:"manual",created_at:stamp,updated_at:stamp,metadata:{},...changes});
const note=(changes={})=>({id:"n1",project_id:"a",title:"現場筆記",content:"牆面需複測",created_at:stamp,updated_at:stamp,metadata:{},...changes});
const attachment=(changes={})=>({id:"f1",project_id:"a",filename:"site.png",display_name:"現場照片",mime_type:"image/png",size_bytes:3,kind:"photo",storage_provider:"engineering-indexeddb",storage_key:"project/a/attachment/f1",source:"upload",created_at:stamp,updated_at:stamp,metadata:{},...changes});
const record=(changes={})=>({id:"r1",project_id:"a",record_type:"manual",title:"進場",content:"完成初勘",related_entity_type:null,related_entity_id:null,created_at:stamp,metadata:{},...changes});
function memoryPersistence(){const stores=new Map(Object.values(Database.STORES).map(name=>[name,new Map()])),clone=value=>value==null?value:structuredClone(value);return{stores,async addData(store,row){if(stores.get(store).has(row.id))throw new Error("duplicate");stores.get(store).set(row.id,clone(row));},async putData(store,row){stores.get(store).set(row.id,clone(row));},async getData(store,id){return clone(stores.get(store).get(id));},async deleteData(store,id){stores.get(store).delete(id);},async listDataByProject(store,projectId){return clone([...stores.get(store).values()].filter(row=>row.project_id===projectId));},async listData(store){return clone([...stores.get(store).values()]);}};}
function repositories(persistence=memoryPersistence()){return{persistence,measurementRepository:MeasurementRepo.create({persistence}),noteRepository:NoteRepo.create({persistence}),attachmentRepository:AttachmentRepo.create({persistence}),projectRecordRepository:RecordRepo.create({persistence})};}
function memoryBinary({failPut=null,failDelete=null}={}){const rows=new Map();return{rows,async put(key,blob){if(failPut)throw failPut;rows.set(key,blob);return key;},async get(key){return rows.get(key)||null;},async delete(key){if(failDelete)throw failDelete;rows.delete(key);return true;},async exists(key){return rows.has(key);},async listKeys(prefix=""){return[...rows.keys()].filter(key=>key.startsWith(prefix));}};}
function fixture(options={}){const repos=options.repos||repositories(),binary=options.binary||memoryBinary(),projects=new Map([["a",{id:"a"}],["b",{id:"b"}]]),projectService={async getProject(id){const project=projects.get(id);if(!project)throw new Error("missing");return project;}};let id=0;const service=Service.create({projectService,...repos,attachmentStorage:binary,now:()=>stamp,idGenerator:()=>`id-${++id}`});return{service,binary,...repos};}
function file(name,type,content="abc"){const blob=new Blob([content],{type});Object.defineProperty(blob,"name",{value:name});return blob;}

test("E4-01 MeasurementRecord accepts neutral numeric values and units",()=>assert.deepEqual(Measurement.create(measurement()).values,{value:120}));
test("E4-02 MeasurementRecord requires a stable id",()=>assert.throws(()=>Measurement.create(measurement({id:""})),error=>error.code==="PROJECT_DATA_REQUIRED"));
test("E4-03 MeasurementRecord requires project ownership",()=>assert.throws(()=>Measurement.create(measurement({project_id:""})),error=>error.code==="PROJECT_DATA_REQUIRED"));
test("E4-04 MeasurementRecord rejects unsupported types",()=>assert.throws(()=>Measurement.create(measurement({type:"wood_board"})),error=>error.code==="MEASUREMENT_TYPE_INVALID"));
test("E4-05 MeasurementRecord rejects non-finite values",()=>assert.throws(()=>Measurement.create(measurement({values:{value:Infinity}})),error=>error.code==="MEASUREMENT_VALUES_INVALID"));
test("E4-06 MeasurementRecord units must map to values",()=>assert.throws(()=>Measurement.create(measurement({units:{other:"cm"}})),error=>error.code==="MEASUREMENT_UNITS_INVALID"));
test("E4-07 invalid timestamps are rejected",()=>assert.throws(()=>Note.create(note({updated_at:"not-a-date"})),error=>error.code==="PROJECT_DATA_TIMESTAMP_INVALID"));
test("E4-08 ProjectNote contract is normalized",()=>assert.equal(Note.create(note()).content,"牆面需複測"));
test("E4-09 AttachmentMetadata contract is normalized",()=>assert.equal(Attachment.create(attachment()).storage_key,"project/a/attachment/f1"));
test("E4-10 AttachmentMetadata rejects unsupported kind",()=>assert.throws(()=>Attachment.create(attachment({kind:"executable"})),error=>error.code==="ATTACHMENT_KIND_INVALID"));
test("E4-11 ProjectRecord supports an explicit relationship",()=>assert.equal(ProjectRecord.create(record({related_entity_type:"measurement",related_entity_id:"m1"})).related_entity_id,"m1"));
test("E4-12 ProjectRecord rejects half a relationship",()=>assert.throws(()=>ProjectRecord.create(record({related_entity_type:"measurement"})),error=>error.code==="PROJECT_RECORD_RELATION_INVALID"));

test("E4-13 measurement repository creates and reloads records",async()=>{const {measurementRepository}=repositories();await measurementRepository.create(measurement());assert.equal((await measurementRepository.getById("m1")).label,"現場寬度");});
test("E4-14 measurement repository updates records",async()=>{const {measurementRepository}=repositories();await measurementRepository.create(measurement());await measurementRepository.update(measurement({label:"更新寬度"}));assert.equal((await measurementRepository.getById("m1")).label,"更新寬度");});
test("E4-15 measurement repository hard deletes consistently",async()=>{const {measurementRepository}=repositories();await measurementRepository.create(measurement());await measurementRepository.delete("m1");assert.equal(await measurementRepository.getById("m1"),null);});
test("E4-16 repository lists are isolated by project",async()=>{const {measurementRepository}=repositories();await measurementRepository.create(measurement());await measurementRepository.create(measurement({id:"m2",project_id:"b"}));assert.equal((await measurementRepository.listByProject("a")).length,1);});
test("E4-17 notes persist through a new repository instance",async()=>{const persistence=memoryPersistence();await NoteRepo.create({persistence}).create(note());assert.equal((await NoteRepo.create({persistence}).listByProject("a"))[0].title,"現場筆記");});
test("E4-18 attachment filenames are not repository keys",async()=>{const {attachmentRepository}=repositories();await attachmentRepository.create(attachment());await attachmentRepository.create(attachment({id:"f2",storage_key:"project/a/attachment/f2"}));assert.equal((await attachmentRepository.listByProject("a")).length,2);});

test("E4-19 service creates and updates a measurement",async()=>{const {service}=fixture();const created=await service.createMeasurement("a",{type:"dimension",label:"高度",values:{value:240},units:{value:"cm"}}),updated=await service.updateMeasurement("a",created.id,{label:"完成高度"});assert.equal(updated.label,"完成高度");assert.equal(updated.id,created.id);});
test("E4-20 service blocks cross-project measurement updates",async()=>{const {service}=fixture();const created=await service.createMeasurement("a",{type:"dimension",label:"高度",values:{value:240},units:{value:"cm"}});await assert.rejects(service.updateMeasurement("b",created.id,{label:"錯誤"}),error=>error.code==="PROJECT_DATA_NOT_FOUND");});
test("E4-21 note CRUD remains project scoped",async()=>{const {service}=fixture();const created=await service.createNote("a",{title:"A",content:"內容"});assert.equal((await service.listProjectData("a")).notes.length,1);await service.updateNote("a",created.id,{title:"B"});assert.equal((await service.listProjectData("a")).notes[0].title,"B");await service.deleteNote("a",created.id);assert.equal((await service.listProjectData("a")).notes.length,0);});
test("E4-22 project records create and list",async()=>{const {service}=fixture();await service.createRecord("a",{record_type:"site_issue",title:"牆面",content:"不平整"});assert.equal((await service.listProjectData("a")).records[0].record_type,"site_issue");});
test("E4-23 project records stay isolated",async()=>{const {service}=fixture();await service.createRecord("a",{title:"A",content:"A"});assert.equal((await service.listProjectData("b")).records.length,0);});

test("E4-24 MIME whitelist contains only safe MVP formats",()=>assert.deepEqual(Service.MIME_TYPES,["image/jpeg","image/png","image/webp","application/pdf"]));
test("E4-25 file size limit is 10 MiB",()=>assert.equal(Service.MAX_FILE_SIZE,10*1024*1024));
test("E4-26 valid image writes binary then metadata",async()=>{const {service,binary}=fixture(),saved=await service.addAttachment("a",file("site.png","image/png"));assert.equal(saved.kind,"photo");assert.equal(await binary.exists(saved.storage_key),true);});
test("E4-27 valid PDF is stored as document",async()=>assert.equal((await fixture().service.addAttachment("a",file("plan.pdf","application/pdf"))).kind,"document"));
test("E4-28 empty files are rejected",async()=>await assert.rejects(fixture().service.addAttachment("a",file("empty.png","image/png","")),error=>error.code==="ATTACHMENT_EMPTY"));
test("E4-29 oversize files are rejected before storage",async()=>await assert.rejects(fixture().service.addAttachment("a",{name:"large.pdf",type:"application/pdf",size:Service.MAX_FILE_SIZE+1}),error=>error.code==="ATTACHMENT_TOO_LARGE"));
test("E4-30 unsupported MIME is rejected",async()=>await assert.rejects(fixture().service.addAttachment("a",file("page.html","text/html")),error=>error.code==="ATTACHMENT_MIME_UNSUPPORTED"));
test("E4-31 duplicate filenames create distinct attachments",async()=>{const {service}=fixture(),a=await service.addAttachment("a",file("same.png","image/png")),b=await service.addAttachment("a",file("same.png","image/png"));assert.notEqual(a.id,b.id);assert.notEqual(a.storage_key,b.storage_key);});
test("E4-32 binary failure never creates metadata",async()=>{const error=Object.assign(new Error("disk"),{code:"ATTACHMENT_BINARY_WRITE_FAILED"}),repos=repositories(),{service}=fixture({repos,binary:memoryBinary({failPut:error})});await assert.rejects(service.addAttachment("a",file("a.png","image/png")));assert.equal((await repos.attachmentRepository.listByProject("a")).length,0);});
test("E4-33 metadata failure compensates by deleting binary",async()=>{const repos=repositories(),binary=memoryBinary();repos.attachmentRepository={...repos.attachmentRepository,create:async()=>{throw new Error("metadata");}};const {service}=fixture({repos,binary});await assert.rejects(service.addAttachment("a",file("a.png","image/png")),error=>error.code==="ATTACHMENT_METADATA_SAVE_FAILED");assert.equal(binary.rows.size,0);});
test("E4-34 quota failure is preserved as an explicit code",async()=>{const quota=Object.assign(new Error("quota"),{code:"ATTACHMENT_QUOTA_EXCEEDED"});await assert.rejects(fixture({binary:memoryBinary({failPut:quota})}).service.addAttachment("a",file("a.png","image/png")),error=>error.code==="ATTACHMENT_QUOTA_EXCEEDED");});
test("E4-35 attachment content can be reopened",async()=>{const {service}=fixture(),saved=await service.addAttachment("a",file("a.png","image/png"));assert.equal((await service.getAttachmentContent("a",saved.id)).blob.type,"image/png");});
test("E4-36 missing payload is explicit",async()=>{const {service,binary}=fixture(),saved=await service.addAttachment("a",file("a.png","image/png"));await binary.delete(saved.storage_key);await assert.rejects(service.getAttachmentContent("a",saved.id),error=>error.code==="ATTACHMENT_PAYLOAD_MISSING");});
test("E4-37 delete removes metadata and binary",async()=>{const {service,binary}=fixture(),saved=await service.addAttachment("a",file("a.png","image/png"));await service.deleteAttachment("a",saved.id);assert.equal(binary.rows.size,0);assert.equal((await service.listProjectData("a")).attachments.length,0);});
test("E4-38 binary delete failure leaves metadata intact",async()=>{const binary=memoryBinary(),fx=fixture({binary}),saved=await fx.service.addAttachment("a",file("a.png","image/png"));binary.delete=async()=>{throw Object.assign(new Error("fail"),{code:"ATTACHMENT_BINARY_DELETE_FAILED"});};await assert.rejects(fx.service.deleteAttachment("a",saved.id));assert.equal((await fx.service.listProjectData("a")).attachments.length,1);});
test("E4-39 metadata delete failure restores binary",async()=>{const repos=repositories(),binary=memoryBinary(),savedDelete=repos.attachmentRepository.delete;repos.attachmentRepository={...repos.attachmentRepository,delete:async()=>{throw new Error("metadata delete");}};const {service}=fixture({repos,binary}),saved=await service.addAttachment("a",file("a.png","image/png"));await assert.rejects(service.deleteAttachment("a",saved.id),error=>error.code==="ATTACHMENT_METADATA_DELETE_FAILED");assert.equal(await binary.exists(saved.storage_key),true);repos.attachmentRepository.delete=savedDelete;});
test("E4-40 diagnostics find missing payloads",async()=>{const {service,binary}=fixture(),saved=await service.addAttachment("a",file("a.png","image/png"));await binary.delete(saved.storage_key);assert.deepEqual((await service.diagnoseAttachments("a")).missing_payloads,[saved.id]);});
test("E4-41 diagnostics and cleanup find orphan binaries",async()=>{const {service,binary}=fixture();await binary.put("project/a/attachment/orphan",file("a.png","image/png"));assert.equal((await service.diagnoseAttachments("a")).orphan_binary_keys.length,1);assert.equal(await service.cleanupOrphanBinaries("a"),1);assert.equal(binary.rows.size,0);});

test("E4-42 binary adapter uses an independent database",()=>{assert.equal(Binary.DB_NAME,"lizhi-engineering-attachment-binaries");assert.equal(Binary.DB_VERSION,1);assert.equal(Binary.STORE,"payloads");});
test("E4-43 Engineering DB v3 adds four project data stores",()=>{assert.equal(Database.DB_VERSION,3);assert.deepEqual(Object.keys(Database.STORES),["projects","settings","calculations","measurements","notes","attachments","project_records"]);});
test("E4-44 all project data stores create a project_id index",()=>{const source=read("engineering/storage/engineering-db.js");assert.match(source,/createProjectDataStore\(STORES\.measurements/);assert.match(source,/store\.createIndex\("project_id"/);});
test("E4-45 v2 migration only creates missing stores and preserves old ones",async()=>{const existing=new Set(["projects","settings","calculations"]),created=[],db={objectStoreNames:{contains:name=>existing.has(name)},createObjectStore(name){created.push(name);existing.add(name);return{createIndex(){}};},close(){},transaction(){throw new Error("unused");}},request={result:db};const indexedDBImpl={open(name,version){assert.equal(name,"lizhi-engineering");assert.equal(version,3);queueMicrotask(()=>{request.onupgradeneeded?.();request.onsuccess?.();});return request;}};await Database.openDatabase(indexedDBImpl);assert.deepEqual(created,["measurements","notes","attachments","project_records"]);assert.ok(existing.has("projects")&&existing.has("calculations"));});
test("E4-46 architecture document defines compensation and rollback",()=>{const doc=read("engineering/phase4-storage-architecture.md");assert.match(doc,/Metadata 與 Binary 分離/);assert.match(doc,/compensation/);assert.match(doc,/不得刪除資料庫/);});
test("E4-47 UI renders measurements notes attachments and records",()=>{const html=Workspace.render({project:{id:"a",workspace_id:"w",name:"P",status:"active",module_ids:[],created_at:stamp,updated_at:stamp,metadata:{}},projectData:{measurements:[Measurement.create(measurement())],notes:[Note.create(note())],attachments:[{...Attachment.create(attachment()),preview_url:"blob:test"}],records:[ProjectRecord.create(record())]}});assert.match(html,/現場資料/);assert.match(html,/量測/);assert.match(html,/筆記/);assert.match(html,/附件/);assert.match(html,/專案紀錄/);});
test("E4-48 UI never accesses IndexedDB or binary adapter directly",()=>{const source=read("engineering/pages/project-workspace.js");assert.doesNotMatch(source,/indexedDB|AttachmentStorage|\.put\(|\.get\(/);});
test("E4-49 production assets load storage and service before UI runtime",()=>{const index=read("index.html");assert.match(index,/attachment-storage-adapter\.js[\s\S]*project-data-service\.js[\s\S]*project-workspace\.js\?v=5[\s\S]*engineering\.js\?v=5/);});
test("E4-50 project data core is domain neutral",()=>{const source=fs.readdirSync(path.join(root,"engineering/core/project-data")).filter(file=>file.endsWith(".js")).map(file=>read(`engineering/core/project-data/${file}`)).join("\n");assert.doesNotMatch(source,/wood_length|board_width|cabinet_height|BOM|cutting optimization|supabase|callAI/i);});
test("E4-51 protected systems remain unchanged",()=>{assert.match(read("finance/storage/finance-db.js"),/DB_VERSION=1/);assert.doesNotMatch(read("sync.js"),/engineering/i);assert.equal(fs.readdirSync(path.join(root,"supabase/migrations")).some(file=>file.includes("engineering")),false);});
