import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";

const require=createRequire(import.meta.url),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const Domain=require("../domain/finance-domain.js");
const RuleEngine=require("../domain/finance-rule-engine.js");
const Template=require("../domain/finance-transaction-template.js");
const Validator=require("../domain/finance-draft-validator.js");
const Payload=require("../domain/finance-commit-payload.js");
const Guard=require("../ai/finance-ai-output-guard.js");
const Context=require("../ai/finance-ai-context.js");
const Memory=require("../rule-memory/finance-rule-memory.js");
const Multi=require("../advanced-voice/finance-multi-transaction-parser.js");
const Session=require("../advanced-voice/finance-session-context.js");
const Basket=require("../advanced-voice/finance-review-basket.js");
const Commit=require("../domain/finance-commit-controller.js");
const Sync=require("../sync/finance-sync.js");

const accounts=[{id:"ctbc",name:"中信帳戶",type:"bank",initialBalance:10000,archived:false},{id:"first",name:"第一銀行",type:"bank",initialBalance:5000,archived:false}];
const cards=[{id:"taishin",name:"台新卡",closingDay:15,dueDay:5,archived:false}];
const categories=[{id:"transport",name:"交通",type:"expense",archived:false},{id:"food",name:"餐飲",type:"expense",archived:false}];
const references={accounts,creditCards:cards,categories};
const purchase={id:"purchase",type:"credit_card_purchase",amount:850,date:"2026-10-01",creditCardId:"taishin",categoryId:"transport"};
const payment={id:"payment",type:"credit_card_payment",amount:400,date:"2026-10-20",fromAccountId:"ctbc",creditCardId:"taishin"};
const context={currentDate:"2026-10-10",...references};
const draft=changes=>Template.sanitizeFinanceTransactionTemplate({action:"create_transaction",type:"credit_card_payment",amount:850,dateToken:"specific",date:"2026-10-10",creditCard:"台新卡",fromAccount:"中信帳戶",rawText:"台新卡費繳 850，中信帳戶",source:"text",...changes});
const validate=(value,options={})=>Validator.validateFinanceDraftForCommit(value,{references,...options});

test("CC-01 purchase is counted once in monthly spending",()=>assert.equal(Domain.calculateMonthlyExpense([purchase],"2026-10"),850));
test("CC-02 payment is excluded from monthly spending",()=>assert.equal(Domain.calculateMonthlyExpense([purchase,payment],"2026-10"),850));
test("CC-03 purchase increases card outstanding",()=>assert.equal(Domain.calculateCreditCardOutstanding("taishin",[purchase]),850));
test("CC-04 payment reduces card outstanding",()=>assert.equal(Domain.calculateCreditCardOutstanding("taishin",[purchase,payment]),450));
test("CC-05 purchase does not reduce a bank account",()=>assert.equal(Domain.calculateAccountBalance(accounts[0],[purchase]),10000));
test("CC-06 payment reduces fromAccount",()=>assert.equal(Domain.calculateAccountBalance(accounts[0],[payment]),9600));
test("CC-07 purchase lowers net worth exactly once",()=>assert.equal(Domain.calculateNetWorth([accounts[0]],cards,[purchase]),9150));
test("CC-08 payment does not lower net worth a second time",()=>assert.equal(Domain.calculateNetWorth([accounts[0]],cards,[purchase,{...payment,amount:850}]),9150));
test("CC-09 partial payment preserves remaining liability",()=>assert.equal(Domain.calculateCreditCardOutstanding("taishin",[purchase,payment]),450));
test("CC-10 overpayment requires another confirmation",()=>{const result=validate(draft({amount:900}),{transactions:[purchase]});assert.equal(result.status,"ready");assert.equal(result.commitEligible,false);assert.ok(result.warnings.some(row=>row.code==="exceeds_outstanding"));});
test("CC-11 purchase without card needs input",()=>{const value=draft({type:"credit_card_purchase",creditCard:null,category:"交通",fromAccount:null});assert.equal(validate(value).status,"needs_input");});
test("CC-12 payment without account needs input",()=>assert.equal(validate(draft({fromAccount:null,account:null})).status,"needs_input"));
test("CC-13 payment category is blocked",()=>{const result=validate(draft({category:"交通"}));assert.equal(result.status,"blocked");assert.ok(result.invalidFields.some(row=>row.code==="payment_category_forbidden"));});
test("CC-14 archived card is blocked",()=>{const result=Validator.validateFinanceDraftForCommit(draft(),{references:{...references,creditCards:[{...cards[0],archived:true}]}});assert.equal(result.status,"blocked");});
test("CC-15 duplicate active card names are ambiguous",()=>{const result=Validator.validateFinanceDraftForCommit(draft(),{references:{...references,creditCards:[cards[0],{...cards[0],id:"duplicate"}]}});assert.equal(result.status,"needs_input");assert.ok(result.issues.some(row=>row.code==="ambiguous_reference"));});
test("CC-16 explicit purchase type is locked",()=>{const result=RuleEngine.parseFinanceRulesToDraft("中油加油 850，台新卡",context);assert.equal(result.draft.type,"credit_card_purchase");assert.ok(result.lockedFields.includes("type"));});
test("CC-17 explicit payment type is locked",()=>{const result=RuleEngine.parseFinanceRulesToDraft("台新卡費繳 850，中信帳戶",context);assert.equal(result.draft.type,"credit_card_payment");assert.ok(result.lockedFields.includes("type"));});
test("CC-18 AI cannot overwrite a locked type",()=>{const rule=RuleEngine.parseFinanceRulesToDraft("台新卡費繳 850，中信帳戶",context),ai=Guard.guardFinanceAiOutput({type:"credit_card_purchase"},Context.buildFinanceAiContext({rawText:rule.draft.rawText,draft:rule.draft,ruleResult:rule,references}));assert.equal(ai.patch.type,undefined);assert.ok(ai.issues.includes("ai_attempted_locked_field:type"));});
test("CC-19 Rule Memory rejects type targets",()=>assert.throws(()=>Memory.normalizeRule({matchKind:"keyword",matchValue:"台新",targetField:"type",targetLabelSnapshot:"credit_card_payment",source:"user_confirmed"}),error=>error.code==="INVALID_TARGET_FIELD"));
test("CC-20 card liability uses Stable ID rather than name",()=>assert.equal(Domain.calculateCreditCardOutstanding("taishin",[purchase,{...purchase,id:"other",creditCardId:"same-name-other"}]),850));
test("CC-21 台新卡刷1200 is a purchase",()=>assert.equal(RuleEngine.parseFinanceRulesToDraft("台新卡刷1200買鞋",context).draft.type,"credit_card_purchase"));
test("CC-22 繳台新卡3000 is a payment",()=>{const result=RuleEngine.parseFinanceRulesToDraft("用第一銀行繳台新卡3000",context);assert.equal(result.draft.type,"credit_card_payment");assert.equal(result.draft.fromAccount,"第一銀行");});
test("CC-23 卡費850 without payment wording is not guessed",()=>{const result=RuleEngine.parseFinanceRulesToDraft("卡費850",context),ai=Context.buildFinanceAiContext({draft:result.draft,ruleResult:result,references});assert.equal(result.draft.type,null);assert.ok(result.issues.includes("payment_intent_unclear"));assert.equal(ai.shouldCallAI,false);});
test("CC-24 mixed purchase and payment split independently",async()=>{const result=await Multi.parse("中油850台新卡，然後繳台新卡費3000中信帳戶",{sessionId:"cc",parseDraft:text=>RuleEngine.parseFinanceRulesToDraft(text,context),validateDraft:value=>validate(value)});assert.equal(result.candidates.length,2);assert.deepEqual(result.candidates.map(row=>row.draft.type),["credit_card_purchase","credit_card_payment"]);});
test("CC-25 Advanced Voice exposes explicit type correction rules",()=>{const source=read("finance/pages/home.js");assert.match(source,/patch\.type=\"credit_card_payment\"/);assert.match(source,/patch\.type=\"credit_card_purchase\"/);});
test("CC-26 cancelling one candidate preserves the other",()=>{const session=Session.create({sessionId:"cc"});session.add([{draftId:"a",status:"READY",draft:{}},{draftId:"b",status:"READY",draft:{}}]);session.cancel("第一筆");assert.equal(session.get("a").status,"CANCELLED");assert.equal(session.get("b").status,"READY");});
test("CC-27 batch confirmation commits READY only",async()=>{const session=Session.create({sessionId:"cc"});session.add([{draftId:"a",status:"READY",validation:{commitEligible:true},draft:{}},{draftId:"b",status:"NEEDS_INPUT",validation:{commitEligible:false},draft:{}}]);const basket=Basket.create({session,commitCandidate:async row=>({id:row.draftId})}),result=await basket.confirmAll();assert.equal(result.committed,1);assert.equal(result.skipped,1);});
test("CC-28 duplicate confirmation is idempotent",async()=>{let writes=0;const controller=Commit.createFinanceCommitController({createTransaction:async value=>{writes++;return{id:"one",...value};}}),result=validate(draft());await controller.commit(result);const second=await controller.commit(result);assert.equal(second.code,"duplicate_transaction");assert.equal(writes,1);});
test("CC-29 production autoEntry remains disabled",()=>assert.match(read("finance/pages/home.js"),/aiAutoEntryEnabled=false/));
test("CC-30 formal write still needs confirmation",()=>{const source=read("finance/pages/home.js");assert.match(source,/data-finance-action=\"confirm-transaction\"/);assert.match(source,/data-finance-action=\"confirm-ai-transaction\"/);});
test("CC-31 purchase sync key keeps Stable ID",()=>assert.equal(Sync.keyOf("transactions",purchase.id),"transactions:purchase"));
test("CC-32 payment sync key keeps Stable ID",()=>assert.equal(Sync.keyOf("transactions",payment.id),"transactions:payment"));
test("CC-33 payment sync remains reference-first",()=>assert.match(read("finance/storage/finance-db.js"),/credit_card_payment:\[\[\"accounts\",record\.fromAccountId\|\|record\.accountId\]/));
test("CC-34 sync failure preserves local-first behavior",()=>assert.match(read("finance/sync/finance-sync.js"),/本機帳本已保留/));
test("CC-35 sync reconciliation deduplicates by kind and ID",()=>assert.match(read("finance/sync/finance-sync.js"),/const keyOf=\(kind,id\)=>`\$\{kind\}:\$\{id\}`/));
test("CC-36 tombstones remain synchronizable and cannot silently resurrect",()=>{const storage=read("finance/storage/finance-db.js"),sync=read("finance/sync/finance-sync.js");assert.match(storage,/tombstoneTransaction/);assert.match(sync,/compare\(local,cloud\)/);});
test("CC-37 existing purchase records remain valid",()=>assert.equal(Domain.validateTransaction(purchase,references).valid,true));
test("CC-38 legacy accountId payment stays excluded from expense",()=>{const legacy={...payment,fromAccountId:undefined,accountId:"ctbc"};assert.equal(Domain.validateTransaction(legacy,references).valid,true);assert.equal(Domain.calculateMonthlyExpense([purchase,legacy],"2026-10"),850);});
test("CC-39 no silent historical rewrite tool was introduced",()=>assert.doesNotMatch(read("finance/domain/finance-domain.js"),/update\(|transactions\.create|transactions\.update/));
test("CC-40 Finance DB stays v1",()=>assert.match(read("finance/storage/finance-db.js"),/DB_VERSION=1/));
test("CC-41 Dashboard spending excludes payments",()=>{assert.equal(Domain.calculateMonthlyExpense([purchase,payment],"2026-10"),850);assert.match(read("finance/pages/home.js"),/本月消費支出/);});
test("CC-42 Dashboard displays payments separately",()=>{assert.equal(Domain.calculateMonthlyCreditCardPayments([purchase,payment],"2026-10"),400);assert.match(read("finance/pages/home.js"),/本月卡費繳款/);});
test("CC-43 outstanding equals purchases minus payments",()=>assert.equal(Domain.calculateCreditCardOutstanding("taishin",[purchase,payment]),850-400));
test("CC-44 billing-cycle detail is derived when closingDay exists",()=>{const cycle=Domain.calculateCreditCardCycle(cards[0],[purchase,payment],"2026-10-20");assert.equal(cycle.available,true);assert.equal(cycle.outstanding,450);});
test("CC-45 missing closingDay never fabricates bill status",()=>{const cycle=Domain.calculateCreditCardCycle({...cards[0],closingDay:null},[purchase],"2026-10-20");assert.equal(cycle.available,false);assert.equal(cycle.unbilled,null);assert.equal(cycle.billedUnpaid,null);});
test("CC-46 partial payment status is explicit",()=>assert.equal(Domain.calculateCreditCardCycle(cards[0],[purchase,payment],"2026-10-20").paymentStatus,"partial"));
test("CC-47 390px UI remains responsive",()=>{const css=read("finance/styles/home.css"),page=read("finance/pages/home.js");assert.match(css,/@media\s*\(max-width:\s*700px\)/);assert.match(page,/目前未繳總額/);});
test("CC-48 Phase 1-10 safety boundaries remain present",()=>{assert.match(read("finance/storage/finance-db.js"),/DB_VERSION=1/);assert.match(read("finance/pages/home.js"),/aiAutoEntryEnabled=false/);assert.match(read("finance/gateway/gateway-config.mjs"),/127\.0\.0\.1/);assert.match(read("finance/rule-memory/finance-rule-memory.js"),/TARGET_FIELDS=.*category.*account.*creditCard.*merchant/);});
