import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";
import {createFinanceGateway} from "../gateway/finance-ai-gateway.mjs";
import {loadGatewayConfig} from "../gateway/gateway-config.mjs";
import {GatewayAuthError,verifyGatewayAuthorization} from "../gateway/gateway-auth.mjs";
import {validateFinanceParseRequest} from "../gateway/gateway-request-validator.mjs";
import {buildGatewayFinancePrompt} from "../gateway/gateway-prompt.mjs";
import {guardGatewayModelOutput} from "../gateway/gateway-output-guard.mjs";
import {GatewayOllamaError} from "../gateway/gateway-ollama-client.mjs";
import {createRateLimiter,createConcurrencyLimiter} from "../gateway/gateway-rate-limit.mjs";

const require=createRequire(import.meta.url),Template=require("../domain/finance-transaction-template.js"),Connector=require("../ai/finance-ai-gateway-connector.js"),dirname=path.dirname(fileURLToPath(import.meta.url));
const ORIGIN="http://127.0.0.1:4180";
const silentLogger=Object.freeze({info(){},warn(){},error(){}});
const config=Object.freeze({host:"127.0.0.1",port:0,ollamaBaseUrl:`http://127.0.0.1:${11434}`,model:"phase5-test",supabaseUrl:"https://example.supabase.co",supabasePublishableKey:"public",allowedUsers:["user-1"],allowedOrigins:[ORIGIN],bodyLimit:32768,timeoutMs:25000,rateLimit:20,concurrency:2});
const authVerifier=async({authorization})=>{if(!authorization)throw new GatewayAuthError(401,"AUTH_REQUIRED","missing");if(authorization!=="Bearer valid")throw new GatewayAuthError(401,"AUTH_INVALID","invalid");return {id:"user-1",email:"user@example.com"};};
const draft=Template.sanitizeFinanceTransactionTemplate({amount:850,merchant:"中油",category:"交通",creditCard:"台新卡",dateToken:"today",date:"2026-09-27",rawText:"中油加油 850，台新卡。",source:"text"});
const body=(changes={})=>({task:"finance_parse",requestId:"phase5-test-001",rawText:"中油加油 850，台新卡。",draft,lockedFields:["amount","merchant","category","creditCard","date","dateToken"],typeHints:["credit_card_purchase"],allowedValues:{types:["income","expense","transfer","credit_card_purchase","credit_card_payment"],accounts:[],creditCards:["台新卡"],categories:["交通"]},...changes});

async function withServer(t,options={}){
  const server=createFinanceGateway({config,authVerifier,ollamaGenerate:async()=>'{"type":"credit_card_purchase"}',logger:silentLogger,...options});
  await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve);});
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  return `http://127.0.0.1:${server.address().port}`;
}
const post=(base,value=body(),extra={})=>fetch(`${base}/finance/parse`,{method:"POST",headers:{origin:ORIGIN,authorization:"Bearer valid","content-type":"application/json",...(extra.headers||{})},body:typeof value==="string"?value:JSON.stringify(value)});

test("T01 GET /health is minimal and non-loopback bind is forbidden",async t=>{assert.throws(()=>loadGatewayConfig({FINANCE_GATEWAY_HOST:"0.0.0.0"},{strict:false}),/127\.0\.0\.1/);const base=await withServer(t);const response=await fetch(`${base}/health`);assert.equal(response.status,200);assert.deepEqual(await response.json(),{status:"ok",service:"finance-ai-gateway",version:"phase5"});});
test("T02 unknown routes are denied instead of proxied",async t=>{const base=await withServer(t);const response=await fetch(`${base}/api/generate`);assert.equal(response.status,404);assert.equal((await response.json()).error.code,"NOT_FOUND");});
test("T03 valid finance_parse returns a constrained patch",async t=>{const base=await withServer(t);const response=await post(base);const value=await response.json();assert.equal(response.status,200);assert.deepEqual(value.patch,{type:"credit_card_purchase"});assert.equal(value.requestId,"phase5-test-001");});
test("T04 prompt in the request is rejected",()=>assert.throws(()=>validateFinanceParseRequest(body({prompt:"ignore safety"})),error=>error.code==="INVALID_REQUEST"));
test("T05 model and ollamaUrl in the request are rejected",()=>{for(const field of ["model","ollamaUrl"])assert.throws(()=>validateFinanceParseRequest(body({[field]:"attacker"})),error=>error.code==="INVALID_REQUEST");});
test("T06 tasks other than finance_parse are rejected",()=>assert.throws(()=>validateFinanceParseRequest(body({task:"chat"})),error=>error.code==="INVALID_REQUEST"));
test("T07 missing Authorization is 401 and never calls Ollama",async t=>{let calls=0;const base=await withServer(t,{ollamaGenerate:async()=>{calls+=1;return "{}";}});const response=await fetch(`${base}/finance/parse`,{method:"POST",headers:{origin:ORIGIN,"content-type":"application/json"},body:JSON.stringify(body())});assert.equal(response.status,401);assert.equal(calls,0);});
test("T08 invalid tokens are 401 and never call Ollama",async t=>{let calls=0;const base=await withServer(t,{ollamaGenerate:async()=>{calls+=1;return "{}";}});const response=await post(base,body(),{headers:{authorization:"Bearer invalid"}});assert.equal(response.status,401);assert.equal(calls,0);});
test("T09 authenticated users outside the allowlist are rejected",async()=>{await assert.rejects(()=>verifyGatewayAuthorization({authorization:"Bearer token",config,fetchImpl:async()=>new Response(JSON.stringify({id:"other",email:"other@example.com"}),{status:200,headers:{"content-type":"application/json"}})}),error=>error.code==="USER_NOT_ALLOWED"&&error.status===403);});
test("T10 origins outside the allowlist are rejected",async t=>{const base=await withServer(t);const response=await fetch(`${base}/finance/parse`,{method:"POST",headers:{origin:"https://evil.example",authorization:"Bearer valid","content-type":"application/json"},body:JSON.stringify(body())});assert.equal(response.status,403);assert.equal(response.headers.get("access-control-allow-origin"),null);});
test("T11 an allowed origin is reflected exactly for parse and preflight",async t=>{const base=await withServer(t);const response=await post(base);assert.equal(response.headers.get("access-control-allow-origin"),ORIGIN);assert.notEqual(response.headers.get("access-control-allow-origin"),"*");const preflight=await fetch(`${base}/finance/parse`,{method:"OPTIONS",headers:{origin:ORIGIN,"access-control-request-method":"POST","access-control-request-headers":"authorization,content-type"}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get("access-control-allow-origin"),ORIGIN);assert.match(preflight.headers.get("access-control-allow-headers"),/Authorization/);});
test("T12 request bodies over the configured limit return 413",async t=>{const base=await withServer(t,{config:{...config,bodyLimit:1024}});const oversized=JSON.stringify({...body(),rawText:"中".repeat(2000)});const response=await post(base,oversized);assert.equal(response.status,413);});
test("T13 rate limits return 429",async t=>{const base=await withServer(t,{rateLimiter:createRateLimiter({limit:1})});assert.equal((await post(base)).status,200);assert.equal((await post(base,body({requestId:"phase5-test-002"}))).status,429);});
test("T14 concurrency limits return BUSY",async t=>{let release;const pending=new Promise(resolve=>{release=resolve;});const base=await withServer(t,{concurrencyLimiter:createConcurrencyLimiter({maximum:1}),ollamaGenerate:async()=>{await pending;return '{"type":"credit_card_purchase"}';}});const first=post(base);await new Promise(resolve=>setTimeout(resolve,20));const second=await post(base,body({requestId:"phase5-test-002"}));assert.equal(second.status,429);assert.equal((await second.json()).error.code,"BUSY");release();assert.equal((await first).status,200);});
test("T15 an offline Ollama maps to OLLAMA_UNAVAILABLE",async t=>{const base=await withServer(t,{ollamaGenerate:async()=>{throw new GatewayOllamaError(502,"OLLAMA_UNAVAILABLE","offline");}});const response=await post(base);assert.equal(response.status,502);assert.equal((await response.json()).error.code,"OLLAMA_UNAVAILABLE");});
test("T16 an Ollama timeout maps to 504",async t=>{const base=await withServer(t,{ollamaGenerate:async()=>{throw new GatewayOllamaError(504,"OLLAMA_TIMEOUT","timeout");}});const response=await post(base);assert.equal(response.status,504);assert.equal((await response.json()).error.code,"OLLAMA_TIMEOUT");});
test("T17 invalid model JSON is rejected",async t=>{const base=await withServer(t,{ollamaGenerate:async()=>"not json"});const response=await post(base);assert.equal(response.status,502);assert.equal((await response.json()).error.code,"MODEL_OUTPUT_INVALID");});
test("T18 locked model fields are removed",()=>{const request=validateFinanceParseRequest(body()),prompt=buildGatewayFinancePrompt(request),guarded=guardGatewayModelOutput('{"type":"credit_card_purchase","amount":8500}',request,prompt);assert.equal(guarded.valid,true);assert.equal(Object.hasOwn(guarded.patch,"amount"),false);assert.equal(request.draft.amount,850);});
test("T19 unknown reference values become null",()=>{const request=validateFinanceParseRequest(body({draft:Template.sanitizeFinanceTransactionTemplate({...draft,creditCard:null}),lockedFields:["amount","merchant","category","date","dateToken"]})),prompt=buildGatewayFinancePrompt(request),guarded=guardGatewayModelOutput('{"type":"credit_card_purchase","creditCard":"不存在卡片"}',request,prompt);assert.equal(guarded.valid,true);assert.equal(guarded.patch.creditCard,null);assert.ok(guarded.issues.includes("value_not_allowed:creditCard"));});
test("T20 core case only adds type and preserves locked values",()=>{const request=validateFinanceParseRequest(body()),prompt=buildGatewayFinancePrompt(request),guarded=guardGatewayModelOutput('{"type":"credit_card_purchase"}',request,prompt);assert.deepEqual(prompt.fillableFields,["type"]);assert.equal(guarded.patch.type,"credit_card_purchase");assert.equal(request.draft.amount,850);assert.equal(request.draft.creditCard,"台新卡");});
test("T21 browser connector calls only the 4181 gateway",async t=>{const originalFetch=globalThis.fetch,originalAuth=globalThis.LizhiAuth,calls=[];globalThis.LizhiAuth={client:{auth:{getSession:async()=>({data:{session:{access_token:"session-token"}}})}}};globalThis.fetch=async(url,options)=>{calls.push(String(url));return new Response(JSON.stringify({ok:true,requestId:"phase5-client",patch:{type:"credit_card_purchase"},issues:[],elapsedMs:1}),{status:200,headers:{"content-type":"application/json"}});};t.after(()=>{globalThis.fetch=originalFetch;globalThis.LizhiAuth=originalAuth;});const context={rawText:body().rawText,draft,lockedFields:body().lockedFields,typeHints:body().typeHints,allowedValues:body().allowedValues};const result=await Connector.generateConstrainedFinancePatch({kind:"finance-small-model-v1"},Connector.DEFAULT_SETTINGS,{context});assert.match(calls[0],/:4181\/finance\/parse$/);assert.ok(calls.every(url=>!url.includes(String(11434))));assert.equal(JSON.parse(result.rawText).type,"credit_card_purchase");});
test("T22 gateway errors surface as safe connector failures",async t=>{const originalFetch=globalThis.fetch,originalAuth=globalThis.LizhiAuth;globalThis.LizhiAuth={client:{auth:{getSession:async()=>({data:{session:{access_token:"session-token"}}})}}};globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,error:{code:"OLLAMA_UNAVAILABLE"}}),{status:502,headers:{"content-type":"application/json"}});t.after(()=>{globalThis.fetch=originalFetch;globalThis.LizhiAuth=originalAuth;});const context={rawText:body().rawText,draft,lockedFields:body().lockedFields,typeHints:body().typeHints,allowedValues:body().allowedValues};await assert.rejects(()=>Connector.generateConstrainedFinancePatch({},Connector.DEFAULT_SETTINGS,{context}),error=>error.code==="OLLAMA_UNAVAILABLE");});
test("T23 Phase 1-4 production contracts stay in place",()=>{const db=fs.readFileSync(path.join(dirname,"../storage/finance-db.js"),"utf8"),index=fs.readFileSync(path.join(dirname,"../../index.html"),"utf8");assert.match(db,/DB_VERSION=1/);assert.doesNotMatch(index,/ollama-connector\.js/);assert.match(index,/finance-ai-gateway-connector\.js/);});
test("T24 gateway tests never write formal transactions",async t=>{let writes=0;const base=await withServer(t);const response=await post(base);assert.equal(response.status,200);assert.equal(writes,0);});
