(function(root,factory){const api=factory(root);if(typeof module==="object"&&module.exports)module.exports=api;else root.EngineeringAIExecutionAdapter=api;})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";class AIExecutionError extends Error{constructor(code,message,cause){super(message,{cause});this.name="AIExecutionError";this.code=code;}}function create({actionRepository,actionModel=root.EngineeringAIAction,actionRegistry,workflowService,projectDataService,taskRepository,projectRecordRepository,now=()=>new Date().toISOString()}={}){if(!actionRepository||!actionModel||!actionRegistry||!workflowService||!projectDataService||!taskRepository||!projectRecordRepository)throw new TypeError("AI Execution Adapter dependencies are required");
    async function existingResult(projectId,actionType,actionId){const repository=actionType==="draft_task"?taskRepository:projectRecordRepository,rows=await repository.listByProject(projectId),entity=rows.find(item=>item.metadata?.ai_action_id===actionId);return entity||null;}
    async function markExecuted(action,entity){return actionRepository.update(actionModel.create({...action,status:"executed",result_entity_type:action.action_type==="draft_task"?"task":"project_record",result_entity_id:entity.id,error_code:null,executed_at:action.executed_at||now(),updated_at:now()}));}
    async function execute({draft,approvedPayload,actorId}={}){const proposal=draft?.structured_draft?.action;actionRegistry.assertAllowed(proposal?.action_type);const actionId=`ai-action:${draft.id}`;let action=await actionRepository.getById(actionId);if(action?.status==="executed")return Object.freeze({action,result:null,alreadyExecuted:true,code:"ALREADY_EXECUTED"});const found=await existingResult(draft.project_id,proposal.action_type,actionId);if(found){if(!action)action=await actionRepository.create(actionModel.create({id:actionId,project_id:draft.project_id,draft_id:draft.id,action_type:proposal.action_type,approved_payload:approvedPayload,original_payload:proposal.payload,status:"approved",created_at:now(),updated_at:now(),metadata:{}}));action=await markExecuted(action,found);return Object.freeze({action,result:found,alreadyExecuted:true,code:"ALREADY_EXECUTED"});}
      if(!action)action=await actionRepository.create(actionModel.create({id:actionId,project_id:draft.project_id,draft_id:draft.id,action_type:proposal.action_type,approved_payload:approvedPayload,original_payload:proposal.payload,status:"approved",created_at:now(),updated_at:now(),metadata:{human_modified:JSON.stringify(approvedPayload)!==JSON.stringify(proposal.payload)}}));action=await actionRepository.update(actionModel.create({...action,status:"executing",error_code:null,updated_at:now()}));const metadata={ai_action_id:actionId,ai_draft_id:draft.id};try{const result=proposal.action_type==="draft_task"?await workflowService.createTask(draft.project_id,{...approvedPayload,metadata},actorId):await projectDataService.createRecord(draft.project_id,{...approvedPayload,metadata});action=await markExecuted(action,result);return Object.freeze({action,result,alreadyExecuted:false,code:"EXECUTED"});}catch(error){try{action=await actionRepository.update(actionModel.create({...action,status:"failed",error_code:String(error?.code||"AI_ACTION_EXECUTION_FAILED"),updated_at:now()}));}catch{}throw new AIExecutionError("AI_ACTION_EXECUTION_FAILED","AI Approved Action 執行失敗，正式資料未回報成功。",error);}}
    return Object.freeze({execute});
  }return Object.freeze({AIExecutionError,create});
});
