(function(root,factory){const isNode=typeof module==="object"&&module.exports,api=factory(isNode?require("./parameter-validator.js"):root.EngineeringParameterValidator,isNode?require("./derived-model.js"):root.EngineeringDerivedModel,isNode?require("./design-model.js"):root.EngineeringParametricDesign);if(isNode)module.exports=api;else root.EngineeringFurnitureDesignService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(ParameterValidator,DerivedModel,DesignModel){
  "use strict";class FurnitureDesignServiceError extends Error{constructor(code,message,details={},cause){super(message,{cause});this.name="FurnitureDesignServiceError";this.code=code;this.details=Object.freeze({...details});}}
  const clone=value=>JSON.parse(JSON.stringify(value)),stable=value=>{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);},id=()=>globalThis.crypto?.randomUUID?.()||`design-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function create({templateRegistry,designRepository,projectService,now=()=>new Date().toISOString(),idGenerator=id}={}){if(!templateRegistry||!designRepository||!projectService)throw new TypeError("Furniture Design Service dependencies are required");
    async function project(projectId){try{return await projectService.getProject(String(projectId));}catch(error){throw new FurnitureDesignServiceError("PROJECT_NOT_FOUND","找不到指定工程專案。",{},error);}}
    async function templateFor(projectId,templateId,version){const current=await project(projectId),template=templateRegistry.getTemplate(templateId,version);if(!template)throw new FurnitureDesignServiceError("UNKNOWN_TEMPLATE_VERSION","找不到指定的家具 Template Version。",{templateId,version});if(!current.module_ids.includes(template.module_id))throw new FurnitureDesignServiceError("TEMPLATE_MODULE_NOT_LINKED","專案尚未關聯此家具 Template 所屬模組。",{moduleId:template.module_id});return{current,template};}
    async function preview(request){const{template}=await templateFor(request.project_id,request.template_id,request.template_version);let parameters;try{parameters=ParameterValidator.normalize(template.parameter_schema,request.parameters);}catch(error){throw new FurnitureDesignServiceError("VALIDATION_ERROR",error.message,{issues:error.issues||[]},error);}const domainIssues=template.validate(parameters)||[];if(domainIssues.length)throw new FurnitureDesignServiceError("VALIDATION_ERROR","家具參數不符合構造規則。",{issues:domainIssues});let derived;try{derived=DerivedModel.create(template.derive(parameters));}catch(error){throw new FurnitureDesignServiceError("DESIGN_DERIVATION_ERROR","家具衍生模型建立失敗。",{},error);}if(derived.template_id!==template.id||derived.template_version!==template.version)throw new FurnitureDesignServiceError("DESIGN_DERIVATION_ERROR","Derived Model 的 Template identity 不一致。");return Object.freeze({template,parameters,derived_snapshot:derived,warnings:derived.warnings});}
    async function saveDraft(request){const prepared=await preview(request),stamp=now(),design=DesignModel.create({id:idGenerator(),project_id:String(request.project_id),module_id:prepared.template.module_id,template_id:prepared.template.id,template_version:prepared.template.version,name:String(request.name||prepared.template.display_name).trim(),parameters:prepared.parameters,derived_snapshot:prepared.derived_snapshot,revision:1,status:"draft",created_at:stamp,updated_at:stamp,metadata:{}});try{return await designRepository.create(design);}catch(error){throw new FurnitureDesignServiceError("DESIGN_SAVE_FAILED","衍生預覽已完成，但家具設計未保存。",{preview:prepared},error);}}
    async function owned(projectId,designId){await project(projectId);const design=await designRepository.getById(designId);if(!design||design.project_id!==String(projectId))throw new FurnitureDesignServiceError("DESIGN_NOT_FOUND","找不到此專案的家具設計。");return design;}
    async function updateDraft(projectId,designId,request){const current=await owned(projectId,designId);if(current.status!=="draft")throw new FurnitureDesignServiceError("DESIGN_NOT_DRAFT","只有草稿可以更新。");const prepared=await preview({project_id:projectId,template_id:current.template_id,template_version:current.template_version,parameters:request.parameters});const updated=DesignModel.create({...current,name:String(request.name||current.name).trim(),parameters:prepared.parameters,derived_snapshot:prepared.derived_snapshot,revision:current.revision+1,updated_at:now()});try{return await designRepository.updateDraft(updated);}catch(error){throw new FurnitureDesignServiceError("DESIGN_SAVE_FAILED","更新預覽已完成，但家具設計未保存。",{preview:prepared},error);}}
    async function getDesign(projectId,designId){const design=await owned(projectId,designId),compatible=templateRegistry.hasTemplate(design.template_id,design.template_version);return Object.freeze({design,compatibility_warning:compatible?null:"UNKNOWN_TEMPLATE_VERSION：保留既有 Snapshot，不會使用新版 Template 重算。"});}
    async function detectDrift(projectId,designId){const{design,compatibility_warning}=await getDesign(projectId,designId);if(compatibility_warning)return Object.freeze({available:false,drift:null,warning:compatibility_warning});const prepared=await preview({project_id:projectId,template_id:design.template_id,template_version:design.template_version,parameters:design.parameters});return Object.freeze({available:true,drift:stable(clone(prepared.derived_snapshot))!==stable(clone(design.derived_snapshot)),warning:null});}
    return Object.freeze({preview,saveDraft,updateDraft,getDesign,detectDrift,listByProject:async projectId=>{await project(projectId);return designRepository.listByProject(projectId);},archiveDesign:async(projectId,designId)=>{const current=await owned(projectId,designId);return designRepository.archive({...current,updated_at:now()});}});
  }
  return Object.freeze({FurnitureDesignServiceError,create});
});
