(function(root,factory){const api=factory(root);if(typeof module==="object"&&module.exports)module.exports=api;else root.EngineeringWorkflowService=api;})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";class WorkflowServiceError extends Error{constructor(code,message,cause){super(message,{cause});this.name="WorkflowServiceError";this.code=code;}}
  const clone=value=>JSON.parse(JSON.stringify(value));
  function create({projectService,memberRepository,taskRepository,reviewRepository,eventRepository,relationResolvers={},memberModel=root.EngineeringProjectMemberModel,taskModel=root.EngineeringTaskModel,reviewModel=root.EngineeringTaskReviewModel,eventModel=root.EngineeringWorkflowEventModel,stateMachine=root.EngineeringTaskStateMachine,now=()=>new Date().toISOString(),idGenerator=()=>root.crypto?.randomUUID?.()||`workflow-${Date.now()}-${Math.random().toString(16).slice(2)}`}={}){
    if(!projectService||!memberRepository||!taskRepository||!reviewRepository||!eventRepository||!memberModel||!taskModel||!reviewModel||!eventModel||!stateMachine)throw new TypeError("Workflow Service dependencies are required");
    async function ensureProject(projectId){try{return await projectService.getProject(String(projectId));}catch(error){throw new WorkflowServiceError("WORKFLOW_PROJECT_NOT_FOUND","找不到指定工程專案。",error);}}
    async function owned(repository,projectId,id,code="WORKFLOW_ENTITY_NOT_FOUND"){await ensureProject(projectId);const value=await repository.getById(String(id));if(!value||value.project_id!==String(projectId))throw new WorkflowServiceError(code,"找不到此專案的 Workflow 資料。");return value;}
    const member=(projectId,id,active=true)=>owned(memberRepository,projectId,id,"WORKFLOW_MEMBER_NOT_FOUND").then(value=>{if(active&&value.status!=="active")throw new WorkflowServiceError("WORKFLOW_MEMBER_ARCHIVED","Member 已封存。");return value;});
    const task=(projectId,id)=>owned(taskRepository,projectId,id,"WORKFLOW_TASK_NOT_FOUND");
    async function validateRelation(projectId,type,id){if(!type&&!id)return null;const resolver=relationResolvers[type];if(!resolver)throw new WorkflowServiceError("WORKFLOW_RELATION_UNSUPPORTED","不支援此 Related Entity。");const entity=await resolver(String(id));if(!entity||entity.project_id!==String(projectId))throw new WorkflowServiceError("WORKFLOW_RELATION_INVALID","Related Entity 不存在或屬於其他專案。");return entity;}
    async function emit(taskValue,event_type,actor_id,{from_state=null,to_state=null,metadata={}}={}){return eventRepository.create(eventModel.create({id:idGenerator(),project_id:taskValue.project_id,entity_id:taskValue.id,event_type,actor_id,from_state,to_state,created_at:now(),metadata}));}
    async function changeWithAudit(current,next,actor,eventType,metadata={}){let saved;try{saved=await taskRepository.update(next);await emit(saved,eventType,actor.id,{from_state:current.status,to_state:saved.status,metadata});return saved;}catch(error){if(saved)try{await taskRepository.update(current);}catch(rollbackError){throw new WorkflowServiceError("WORKFLOW_COMPENSATION_FAILED","Task 更新失敗且無法復原。",{error,rollbackError});}throw error;}}
    async function createMember(projectId,data={}){await ensureProject(projectId);const stamp=now();return memberRepository.create(memberModel.create({id:idGenerator(),project_id:String(projectId),actor_type:"local",actor_ref:null,display_name:data.display_name,role:data.role||"member",status:"active",created_at:stamp,updated_at:stamp,metadata:{}}));}
    async function archiveMember(projectId,memberId){const current=await member(projectId,memberId,false);if(current.status==="archived")return current;return memberRepository.update(memberModel.create({...current,status:"archived",updated_at:now()}));}
    async function createTask(projectId,data={},actorId){const actor=await member(projectId,actorId);if(data.assignee_id)await member(projectId,data.assignee_id);await validateRelation(projectId,data.related_entity_type||null,data.related_entity_id||null);const stamp=now(),value=taskModel.create({id:idGenerator(),project_id:String(projectId),title:data.title,description:data.description||"",status:"todo",priority:data.priority||"normal",assignee_ids:data.assignee_id?[String(data.assignee_id)]:[],due_at:data.due_at||null,related_entity_type:data.related_entity_type||null,related_entity_id:data.related_entity_id||null,requires_review:Boolean(data.requires_review),created_by:actor.id,created_at:stamp,updated_at:stamp,completed_at:null,metadata:{}}),events=[];let saved;try{saved=await taskRepository.create(value);events.push(await emit(saved,"task_created",actor.id,{metadata:{priority:saved.priority}}));if(saved.assignee_ids.length)events.push(await emit(saved,"task_assigned",actor.id,{metadata:{assignee_id:saved.assignee_ids[0]}}));return saved;}catch(error){for(const event of events.reverse())try{await eventRepository.delete(event.id);}catch{}if(saved)try{await taskRepository.delete(saved.id);}catch(rollbackError){throw new WorkflowServiceError("WORKFLOW_COMPENSATION_FAILED","Task 建立失敗且無法清理。",{error,rollbackError});}throw error;}}
    async function updateTask(projectId,taskId,data={},actorId){const current=await task(projectId,taskId);await member(projectId,actorId);const next=taskModel.create({...current,title:data.title??current.title,description:data.description??current.description,priority:data.priority??current.priority,due_at:data.due_at===undefined?current.due_at:data.due_at,updated_at:now()});return taskRepository.update(next);}
    async function assignTask(projectId,taskId,memberId,actorId){const current=await task(projectId,taskId),actor=await member(projectId,actorId),assignee=await member(projectId,memberId);if(!["owner","manager"].includes(actor.role))throw new WorkflowServiceError("WORKFLOW_ASSIGNMENT_FORBIDDEN","只有 owner 或 manager 可指派 Task。");if(["done","cancelled"].includes(current.status))throw new WorkflowServiceError("WORKFLOW_ASSIGNMENT_FORBIDDEN","終止狀態不可重新指派。");const next=taskModel.create({...current,assignee_ids:[assignee.id],updated_at:now()});return changeWithAudit(current,next,actor,"task_assigned",{assignee_id:assignee.id});}
    async function transition(projectId,taskId,target,actorId){const current=await task(projectId,taskId),actor=await member(projectId,actorId);stateMachine.assertTransition(current,target,actor);const eventType=target==="cancelled"?"task_cancelled":target==="review"?"review_requested":target==="done"?"task_completed":"status_changed",next=taskModel.create({...current,status:target,completed_at:target==="done"?now():null,updated_at:now()});return changeWithAudit(current,next,actor,eventType);}
    async function reviewTask(projectId,taskId,decision,comment,reviewerId){const current=await task(projectId,taskId),reviewer=await member(projectId,reviewerId),target=decision==="approved"?"done":"in_progress";stateMachine.assertTransition(current,target,reviewer,{reviewDecision:decision});const review=reviewModel.create({id:idGenerator(),project_id:String(projectId),task_id:current.id,reviewer_id:reviewer.id,decision,comment,created_at:now(),metadata:{}}),next=taskModel.create({...current,status:target,completed_at:target==="done"?now():null,updated_at:now()}),events=[];let savedReview,savedTask;try{savedReview=await reviewRepository.create(review);savedTask=await taskRepository.update(next);events.push(await emit(savedTask,decision==="approved"?"review_approved":"changes_requested",reviewer.id,{from_state:current.status,to_state:target,metadata:{review_id:review.id,comment:review.comment}}));if(decision==="approved")events.push(await emit(savedTask,"task_completed",reviewer.id,{from_state:current.status,to_state:target,metadata:{review_id:review.id}}));return{task:savedTask,review:savedReview};}catch(error){for(const event of events.reverse())try{await eventRepository.delete(event.id);}catch{}if(savedTask)try{await taskRepository.update(current);}catch{}if(savedReview)try{await reviewRepository.delete(savedReview.id);}catch{}throw error;}}
    async function listProjectWorkflow(projectId){await ensureProject(projectId);const[members,tasks,reviews,events]=await Promise.all([memberRepository.listByProject(projectId),taskRepository.listByProject(projectId),reviewRepository.listByProject(projectId),eventRepository.listByProject(projectId)]);return{members,tasks,reviews,events,timeline:projectTimeline({events})};}
    function projectTimeline({events=[],projectRecords=[],quotes=[]}={}){const rows=[...events.map(item=>({id:item.id,kind:"workflow",at:item.created_at,label:item.event_type,entity_id:item.entity_id,actor_id:item.actor_id,metadata:item.metadata})),...projectRecords.map(item=>({id:`record:${item.id}`,kind:"project_record",at:item.created_at,label:item.title,entity_id:item.id,actor_id:null,metadata:{record_type:item.record_type}})),...quotes.filter(item=>item.status==="published").map(item=>({id:`quote:${item.id}`,kind:"quote",at:item.published_at||item.updated_at,label:`Published ${item.quote_number}`,entity_id:item.id,actor_id:null,metadata:{total:item.snapshot?.total,currency:item.snapshot?.currency}}))];return Object.freeze(rows.sort((a,b)=>String(b.at).localeCompare(String(a.at))||a.id.localeCompare(b.id)).map(clone));}
    return Object.freeze({createMember,archiveMember,createTask,updateTask,assignTask,transition,reviewTask,listProjectWorkflow,projectTimeline,validateRelation});
  }
  return Object.freeze({WorkflowServiceError,create});
});
